/** D-G: bounded RTK→Ras→Raf→MEK→ERK signaling over D-E topology and P3. */

import { actorId, type ScientificActor, type ScientificActorId } from "./scientific-actor.ts";
import { evaluateScientificTimeline, type MechanismSnapshotV1 } from "./p3-b-mechanism-state-kernel.ts";
import type { ScientificTimeline } from "./scientific-timeline.ts";
import { validateCellularScientificScene, type CellularScientificSceneV1 } from "./cellular-localization.ts";
import { createCanonicalMembraneProteinProgram, evaluateMembraneProteinAtTime, type MembraneProteinProgramV1 } from "./membrane-protein-topology.ts";
import { createCanonicalSecretoryPathwayProgram } from "./secretory-pathway.ts";

export const cellularSignalingSchemaVersion = "1" as const;
export const cellularSignalingOwnerId = "CELL_SIGNALING_RTK_MAPK_V1" as const;
export type SignalingEventKind = "LIGAND_BOUND" | "RECEPTOR_ACTIVATED" | "RECEPTOR_PHOSPHORYLATED" | "ADAPTOR_RECRUITED" | "SOS_RECRUITED" | "RAS_GTP_EXCHANGE" | "RAF_ACTIVATED" | "MEK_ACTIVATED" | "ERK_ACTIVATED" | "ERK_NUCLEAR_ENTRY" | "TRANSCRIPTION_FACTOR_ACTIVATED" | "TARGET_RESPONSE_ENABLED" | "ERK_DEPHOSPHORYLATED" | "RAS_GTP_HYDROLYZED";
export type ReceptorState = "INACTIVE" | "LIGAND_BOUND" | "ACTIVE" | "PHOSPHORYLATED_ACTIVE";
export type PhosphorylationState = "UNPHOSPHORYLATED" | "PHOSPHORYLATED";
export type RasNucleotideState = "GDP_BOUND_INACTIVE" | "GTP_BOUND_ACTIVE";
export type SignalingLocalization = "EXTRACELLULAR" | "PLASMA_MEMBRANE" | "CYTOSOL" | "NUCLEAR_PORE" | "NUCLEUS";

export type SignalingInteractionV1 = Readonly<{ interactionId: string; kind: "BINDS" | "RECRUITS" | "ACTIVATES" | "INHIBITS" | "PHOSPHORYLATES" | "DEPHOSPHORYLATES" | "NUCLEOTIDE_EXCHANGE" | "TRANSLOCATES"; subjectId: ScientificActorId; objectId: ScientificActorId; locality: SignalingLocalization; sourceEventId?: string }>;
export type SignalingSiteV1 = Readonly<{ siteId: string; actorId: ScientificActorId; regionId: string; state: PhosphorylationState; locality: "PLASMA_MEMBRANE" | "CYTOSOL" | "NUCLEUS"; provenanceRefs: readonly string[] }>;
export type SignalingEventV1 = Readonly<{ eventId: string; timelineEventId: string; at: number; kind: SignalingEventKind; actorIds: readonly ScientificActorId[]; dependsOnEventIds?: readonly string[] }>;
export type CellularSignalingProgramV1 = Readonly<{ schemaVersion: typeof cellularSignalingSchemaVersion; programId: string; ownerId: typeof cellularSignalingOwnerId; speciesScope: "EUKARYOTIC_CELL_SIGNALING"; membraneProteinProgram: MembraneProteinProgramV1; cellularScene: CellularScientificSceneV1; timeline: ScientificTimeline; actors: Readonly<{ ligandId: ScientificActorId; receptorId: ScientificActorId; adaptorId: ScientificActorId; sosId: ScientificActorId; rasId: ScientificActorId; rafId: ScientificActorId; mekId: ScientificActorId; erkId: ScientificActorId; transcriptionFactorId: ScientificActorId; targetGeneId: ScientificActorId; phosphataseId: ScientificActorId }>; sites: readonly SignalingSiteV1[]; interactions: readonly SignalingInteractionV1[]; events: readonly SignalingEventV1[]; fidelity: "S1_CONSTRAINED" | "S2_SCHEMATIC"; quantitativeKinetics: "NOT_MODELED" }>;
export type CellularSignalingSnapshotV1 = Readonly<{ schemaVersion: "1"; programId: string; timeSeconds: number; p3Snapshot: MechanismSnapshotV1; ligandBound: boolean; receptorState: ReceptorState; receptorPhosphorylation: PhosphorylationState; adaptorRecruited: boolean; sosRecruited: boolean; rasNucleotideState: RasNucleotideState; rafState: "INACTIVE" | "ACTIVE"; mekState: "INACTIVE" | "ACTIVE"; erkState: "INACTIVE" | "ACTIVE"; erkLocalization: SignalingLocalization; transcriptionFactorState: "INACTIVE" | "ACTIVE"; targetResponse: "TARGET_GENE_INACTIVE" | "TARGET_GENE_SIGNAL_ENABLED"; receptorTopology: { extracellularDomain: "EXTRACELLULAR"; signalingDomain: "CYTOSOLIC" }; appliedEventIds: readonly string[] }>;
export type CellularSignalingResult = Readonly<{ ok: true; snapshot: CellularSignalingSnapshotV1 }> | Readonly<{ ok: false; code: string; reasons: readonly string[] }>;
export type CellularSignalingValidation = { valid: true; issues: [] } | { valid: false; issues: Array<{ path: string; message: string }> };

const sid = (value: string): ScientificActorId => actorId(value);
const event = (eventId: string, at: number, kind: SignalingEventKind, actorIds: readonly ScientificActorId[], dependsOnEventIds?: readonly string[]): SignalingEventV1 => ({ eventId, timelineEventId: eventId, at, kind, actorIds, ...(dependsOnEventIds ? { dependsOnEventIds } : {}) });
const extraActor = (id: string, semanticTypeId: ScientificActor["semanticTypeId"], role: ScientificActor["role"] = "context", scope: ScientificActor["scope"] = "cellularContext"): ScientificActor => ({ actorId: sid(id), semanticTypeId, role, scope });

function extendScene(base: CellularScientificSceneV1, sourceId: string, actors: CellularSignalingProgramV1["actors"]): CellularScientificSceneV1 {
  const additions = [extraActor(String(actors.ligandId), "protein", "cargo"), extraActor(String(actors.adaptorId), "protein", "context", "molecularComplex"), extraActor(String(actors.sosId), "protein", "enzyme", "molecularComplex"), extraActor(String(actors.rasId), "protein", "context", "molecularComplex"), extraActor(String(actors.rafId), "protein", "enzyme", "molecularComplex"), extraActor(String(actors.mekId), "protein", "enzyme", "molecularComplex"), extraActor(String(actors.erkId), "protein", "enzyme", "molecularComplex"), extraActor(String(actors.transcriptionFactorId), "protein", "context", "molecularComplex"), extraActor(String(actors.targetGeneId), "functionalRegion", "focus", "polymer"), extraActor(String(actors.phosphataseId), "protein", "enzyme", "molecularComplex")];
  const actorList = [...base.scene.actors, ...additions];
  const compartments = [...base.cellular.compartments, { compartmentId: "nucleus", type: "NUCLEUS" as const, fidelity: "S2_SCHEMATIC" as const }, { compartmentId: "nucleoplasm", type: "NUCLEOPLASM" as const, parentCompartmentId: "nucleus", fidelity: "S2_SCHEMATIC" as const }];
  const compartmentRelations = [...base.cellular.compartmentRelations, { relationId: "nucleus-in-cytosol", kind: "CONTAINED_IN" as const, subjectId: "nucleus", objectId: "cytosol" }, { relationId: "nucleoplasm-in-nucleus", kind: "CONTAINED_IN" as const, subjectId: "nucleoplasm", objectId: "nucleus" }];
  const localizations = [...base.cellular.localizations, { actorId: actors.ligandId, compartmentId: "extracellular-space", localizationKind: "IN_COMPARTMENT" as const }, { actorId: actors.adaptorId, compartmentId: "cytosol", localizationKind: "CYTOSOLIC" as const }, { actorId: actors.sosId, compartmentId: "cytosol", localizationKind: "CYTOSOLIC" as const }, { actorId: actors.rasId, compartmentId: "plasma-membrane", localizationKind: "MEMBRANE_ASSOCIATED" as const, membraneId: "plasma-membrane", membraneSide: "CYTOSOLIC" as const }, { actorId: actors.rafId, compartmentId: "cytosol", localizationKind: "CYTOSOLIC" as const }, { actorId: actors.mekId, compartmentId: "cytosol", localizationKind: "CYTOSOLIC" as const }, { actorId: actors.erkId, compartmentId: "cytosol", localizationKind: "CYTOSOLIC" as const }, { actorId: actors.transcriptionFactorId, compartmentId: "nucleus", localizationKind: "NUCLEAR" as const }, { actorId: actors.targetGeneId, compartmentId: "nucleoplasm", localizationKind: "NUCLEAR" as const }, { actorId: actors.phosphataseId, compartmentId: "cytosol", localizationKind: "CYTOSOLIC" as const }];
  return { scene: { ...base.scene, actors: actorList, topology: { ...base.scene.topology, actorIds: actorList.map((item) => item.actorId) } }, cellular: { ...base.cellular, compartments, compartmentRelations, localizations } };
}

export function createCanonicalCellularSignalingProgram(): CellularSignalingProgramV1 {
  const membraneProteinProgram = createCanonicalMembraneProteinProgram(createCanonicalSecretoryPathwayProgram());
  const actors = { ligandId: sid("egf-ligand-1"), receptorId: membraneProteinProgram.topology.proteinId, adaptorId: sid("grb2-adaptor-1"), sosId: sid("sos-exchange-factor-1"), rasId: sid("ras-1"), rafId: sid("raf-1"), mekId: sid("mek-1"), erkId: sid("erk-1"), transcriptionFactorId: sid("elk1-transcription-factor-1"), targetGeneId: sid("target-gene-1"), phosphataseId: sid("erk-phosphatase-1") } as const;
  const sourceId = membraneProteinProgram.secretoryProgram.cellularScene.scene.fidelityProvenance.sources[0]!.sourceId;
  const cellularScene = extendScene(membraneProteinProgram.secretoryProgram.cellularScene, sourceId, actors);
  const events = [event("ligand-bound", 18, "LIGAND_BOUND", [actors.ligandId, actors.receptorId]), event("receptor-activated", 18.3, "RECEPTOR_ACTIVATED", [actors.receptorId], ["ligand-bound"]), event("receptor-phosphorylated", 18.6, "RECEPTOR_PHOSPHORYLATED", [actors.receptorId], ["receptor-activated"]), event("adaptor-recruited", 19, "ADAPTOR_RECRUITED", [actors.adaptorId, actors.receptorId], ["receptor-phosphorylated"]), event("sos-recruited", 19.2, "SOS_RECRUITED", [actors.sosId, actors.adaptorId], ["adaptor-recruited"]), event("ras-gdp-to-gtp", 19.6, "RAS_GTP_EXCHANGE", [actors.rasId, actors.sosId], ["sos-recruited"]), event("raf-activated", 20, "RAF_ACTIVATED", [actors.rafId, actors.rasId], ["ras-gdp-to-gtp"]), event("mek-activated", 20.4, "MEK_ACTIVATED", [actors.mekId, actors.rafId], ["raf-activated"]), event("erk-activated", 20.8, "ERK_ACTIVATED", [actors.erkId, actors.mekId], ["mek-activated"]), event("erk-nuclear-entry", 21.3, "ERK_NUCLEAR_ENTRY", [actors.erkId], ["erk-activated"]), event("tf-activated", 21.7, "TRANSCRIPTION_FACTOR_ACTIVATED", [actors.transcriptionFactorId, actors.erkId], ["erk-nuclear-entry"]), event("target-response-enabled", 22, "TARGET_RESPONSE_ENABLED", [actors.targetGeneId, actors.transcriptionFactorId], ["tf-activated"]), event("erk-dephosphorylated", 23, "ERK_DEPHOSPHORYLATED", [actors.erkId, actors.phosphataseId], ["target-response-enabled"]), event("ras-gtp-hydrolyzed", 23.2, "RAS_GTP_HYDROLYZED", [actors.rasId], ["erk-dephosphorylated"])] as const;
  const timelineEvents = [...membraneProteinProgram.secretoryProgram.timeline.events, ...events.map((item) => ({ eventId: item.timelineEventId, at: item.at, kind: "stateEntered" as const, actorIds: [...item.actorIds] }))].sort((a, b) => a.at - b.at || a.eventId.localeCompare(b.eventId));
  const timeline: ScientificTimeline = { ...membraneProteinProgram.secretoryProgram.timeline, timelineId: "cellular-signaling-rtk-mapk-timeline", clock: { ...membraneProteinProgram.secretoryProgram.timeline.clock, duration: 24 }, events: timelineEvents };
  const sites = [{ siteId: "rtk-cytosolic-phosphosite-1", actorId: actors.receptorId, regionId: "c-domain", state: "UNPHOSPHORYLATED" as const, locality: "PLASMA_MEMBRANE" as const, provenanceRefs: [sourceId] }, { siteId: "erk-activation-site-1", actorId: actors.erkId, regionId: "erk-activation-loop", state: "UNPHOSPHORYLATED" as const, locality: "CYTOSOL" as const, provenanceRefs: [sourceId] }];
  const interactions: SignalingInteractionV1[] = [{ interactionId: "ligand-receptor-binding", kind: "BINDS", subjectId: actors.ligandId, objectId: actors.receptorId, locality: "EXTRACELLULAR", sourceEventId: "ligand-bound" }, { interactionId: "receptor-adaptor-recruitment", kind: "RECRUITS", subjectId: actors.receptorId, objectId: actors.adaptorId, locality: "PLASMA_MEMBRANE", sourceEventId: "adaptor-recruited" }, { interactionId: "sos-ras-exchange", kind: "NUCLEOTIDE_EXCHANGE", subjectId: actors.sosId, objectId: actors.rasId, locality: "PLASMA_MEMBRANE", sourceEventId: "ras-gdp-to-gtp" }, { interactionId: "erk-nuclear-translocation", kind: "TRANSLOCATES", subjectId: actors.erkId, objectId: sid("nucleus"), locality: "NUCLEAR_PORE", sourceEventId: "erk-nuclear-entry" }];
  return { schemaVersion: "1", programId: "canonical-rtk-ras-mapk", ownerId: cellularSignalingOwnerId, speciesScope: "EUKARYOTIC_CELL_SIGNALING", membraneProteinProgram, cellularScene, timeline, actors, sites, interactions, events, fidelity: "S1_CONSTRAINED", quantitativeKinetics: "NOT_MODELED" };
}

const reached = (program: CellularSignalingProgramV1, kind: SignalingEventKind, t: number) => program.events.some((item) => item.kind === kind && item.at <= t);
const applied = (program: CellularSignalingProgramV1, t: number) => program.events.filter((item) => item.at <= t).sort((a, b) => a.at - b.at || a.eventId.localeCompare(b.eventId)).map((item) => item.eventId);

export function evaluateCellularSignalingAtTime(program: CellularSignalingProgramV1, timeSeconds: number): CellularSignalingResult {
  if (!Number.isFinite(timeSeconds) || timeSeconds < 0 || timeSeconds > program.timeline.clock.duration) return { ok: false, code: "SIGNALING_TIME_INVALID", reasons: ["time is outside the signaling timeline"] };
  const scene = validateCellularScientificScene(program.cellularScene, program.timeline); if (!scene.valid) return { ok: false, code: "SIGNALING_SCENE_INVALID", reasons: scene.issues.map((item) => `${item.path}: ${item.message}`) };
  const p3 = evaluateScientificTimeline({ scientificScene: program.cellularScene.scene, timeline: program.timeline, timeSeconds }); if (!p3.ok) return { ok: false, code: "SIGNALING_P3_UNAVAILABLE", reasons: p3.reasons };
  const topology = evaluateMembraneProteinAtTime(program.membraneProteinProgram, Math.min(timeSeconds, program.membraneProteinProgram.secretoryProgram.timeline.clock.duration)); if (!topology.ok) return { ok: false, code: "SIGNALING_RECEPTOR_TOPOLOGY_UNAVAILABLE", reasons: topology.reasons };
  const ligandBound = reached(program, "LIGAND_BOUND", timeSeconds); const receptorActive = reached(program, "RECEPTOR_ACTIVATED", timeSeconds); const receptorPhosphorylated = reached(program, "RECEPTOR_PHOSPHORYLATED", timeSeconds); const rasActive = reached(program, "RAS_GTP_EXCHANGE", timeSeconds) && !reached(program, "RAS_GTP_HYDROLYZED", timeSeconds); const erkActive = reached(program, "ERK_ACTIVATED", timeSeconds) && !reached(program, "ERK_DEPHOSPHORYLATED", timeSeconds);
  return { ok: true, snapshot: { schemaVersion: "1", programId: program.programId, timeSeconds, p3Snapshot: p3.snapshot, ligandBound, receptorState: receptorPhosphorylated ? "PHOSPHORYLATED_ACTIVE" : receptorActive ? "ACTIVE" : ligandBound ? "LIGAND_BOUND" : "INACTIVE", receptorPhosphorylation: receptorPhosphorylated ? "PHOSPHORYLATED" : "UNPHOSPHORYLATED", adaptorRecruited: reached(program, "ADAPTOR_RECRUITED", timeSeconds), sosRecruited: reached(program, "SOS_RECRUITED", timeSeconds), rasNucleotideState: rasActive ? "GTP_BOUND_ACTIVE" : "GDP_BOUND_INACTIVE", rafState: reached(program, "RAF_ACTIVATED", timeSeconds) && !reached(program, "RAS_GTP_HYDROLYZED", timeSeconds) ? "ACTIVE" : "INACTIVE", mekState: reached(program, "MEK_ACTIVATED", timeSeconds) && !reached(program, "RAS_GTP_HYDROLYZED", timeSeconds) ? "ACTIVE" : "INACTIVE", erkState: erkActive ? "ACTIVE" : "INACTIVE", erkLocalization: reached(program, "ERK_NUCLEAR_ENTRY", timeSeconds) && erkActive ? "NUCLEUS" : "CYTOSOL", transcriptionFactorState: reached(program, "TRANSCRIPTION_FACTOR_ACTIVATED", timeSeconds) && erkActive ? "ACTIVE" : "INACTIVE", targetResponse: reached(program, "TARGET_RESPONSE_ENABLED", timeSeconds) && erkActive ? "TARGET_GENE_SIGNAL_ENABLED" : "TARGET_GENE_INACTIVE", receptorTopology: { extracellularDomain: "EXTRACELLULAR", signalingDomain: "CYTOSOLIC" }, appliedEventIds: applied(program, timeSeconds) } };
}

export function validateCellularSignalingProgram(program: CellularSignalingProgramV1): CellularSignalingValidation {
  const issues: Array<{ path: string; message: string }> = []; const issue = (path: string, message: string) => issues.push({ path, message });
  if (program.ownerId !== cellularSignalingOwnerId || program.speciesScope !== "EUKARYOTIC_CELL_SIGNALING") issue("program", "unsupported D-G signaling identity");
  if (program.membraneProteinProgram.topology.proteinId !== program.actors.receptorId) issue("actors.receptorId", "receptor must preserve the D-E membrane-protein identity");
  const byId = new Map(program.events.map((item) => [item.eventId, item])); for (const item of program.events) for (const dependency of item.dependsOnEventIds ?? []) if (!byId.has(dependency) || byId.get(dependency)!.at > item.at) issue(`events.${item.eventId}`, "dependency is missing or occurs after event");
  const order: Array<[SignalingEventKind, SignalingEventKind]> = [["RECEPTOR_ACTIVATED", "LIGAND_BOUND"], ["RECEPTOR_PHOSPHORYLATED", "RECEPTOR_ACTIVATED"], ["ADAPTOR_RECRUITED", "RECEPTOR_PHOSPHORYLATED"], ["SOS_RECRUITED", "ADAPTOR_RECRUITED"], ["RAS_GTP_EXCHANGE", "SOS_RECRUITED"], ["RAF_ACTIVATED", "RAS_GTP_EXCHANGE"], ["MEK_ACTIVATED", "RAF_ACTIVATED"], ["ERK_ACTIVATED", "MEK_ACTIVATED"], ["ERK_NUCLEAR_ENTRY", "ERK_ACTIVATED"], ["TARGET_RESPONSE_ENABLED", "TRANSCRIPTION_FACTOR_ACTIVATED"]];
  for (const [later, earlier] of order) { const a = program.events.find((item) => item.kind === later); const b = program.events.find((item) => item.kind === earlier); if (a && (!b || a.at <= b.at)) issue(`events.${later}`, `must follow ${earlier}`); }
  if (!program.sites.every((site) => site.actorId && site.regionId && site.provenanceRefs.length)) issue("sites", "modification sites require actor, region, and provenance");
  const scene = validateCellularScientificScene(program.cellularScene, program.timeline); if (!scene.valid) scene.issues.forEach((item) => issue(item.path, item.message));
  const final = evaluateCellularSignalingAtTime(program, program.timeline.clock.duration); if (!final.ok) issue("evaluation", `${final.code}: ${final.reasons.join("; ")}`);
  return issues.length ? { valid: false, issues } : { valid: true, issues: [] };
}
export function serializeCellularSignalingProgram(program: CellularSignalingProgramV1): string { return JSON.stringify(program); }
export function serializeCellularSignalingSnapshot(snapshot: CellularSignalingSnapshotV1): string { return JSON.stringify(snapshot); }
