import assert from "node:assert/strict";
import test from "node:test";
import { createCanonicalCellularSignalingProgram, evaluateCellularSignalingAtTime, validateCellularSignalingProgram, serializeCellularSignalingProgram } from "./cellular-signaling.ts";
import { createCanonicalCellularSignalingProductionProgram, projectCellularSignalingProductionAtTime } from "./cellular-signaling-production.ts";
import { applyCellularSignalingExactFrame } from "./p4-b-exact-frame-runtime.ts";

test("D-G canonical RTK/MAPK program validates and preserves D-E receptor topology", () => { const program = createCanonicalCellularSignalingProgram(); assert.deepEqual(validateCellularSignalingProgram(program), { valid: true, issues: [] }); assert.equal(program.actors.receptorId, program.membraneProteinProgram.topology.proteinId); const state = evaluateCellularSignalingAtTime(program, 22); assert.equal(state.ok, true); if (state.ok) assert.deepEqual(state.snapshot.receptorTopology, { extracellularDomain: "EXTRACELLULAR", signalingDomain: "CYTOSOLIC" }); });

test("D-G exact boundaries prevent downstream future leakage", () => { const program = createCanonicalCellularSignalingProgram(); const times = [17, 18, 18.6, 19, 19.6, 20, 20.4, 20.8, 21.3, 22] as const; const states = times.map((time) => evaluateCellularSignalingAtTime(program, time)); assert.equal(states[0]!.ok && states[0]!.snapshot.ligandBound, false); assert.equal(states[1]!.ok && states[1]!.snapshot.receptorState, "LIGAND_BOUND"); assert.equal(states[2]!.ok && states[2]!.snapshot.receptorPhosphorylation, "PHOSPHORYLATED"); assert.equal(states[3]!.ok && states[3]!.snapshot.adaptorRecruited, true); assert.equal(states[4]!.ok && states[4]!.snapshot.rasNucleotideState, "GTP_BOUND_ACTIVE"); assert.equal(states[5]!.ok && states[5]!.snapshot.rafState, "ACTIVE"); assert.equal(states[6]!.ok && states[6]!.snapshot.mekState, "ACTIVE"); assert.equal(states[7]!.ok && states[7]!.snapshot.erkState, "ACTIVE"); assert.equal(states[8]!.ok && states[8]!.snapshot.erkLocalization, "NUCLEUS"); assert.equal(states[9]!.ok && states[9]!.snapshot.targetResponse, "TARGET_GENE_SIGNAL_ENABLED"); });

test("D-G deactivation returns Ras/kinase/nuclear response to inactive states", () => { const state = evaluateCellularSignalingAtTime(createCanonicalCellularSignalingProgram(), 23.2); assert.equal(state.ok, true); if (state.ok) { assert.equal(state.snapshot.rasNucleotideState, "GDP_BOUND_INACTIVE"); assert.equal(state.snapshot.rafState, "INACTIVE"); assert.equal(state.snapshot.mekState, "INACTIVE"); assert.equal(state.snapshot.erkState, "INACTIVE"); assert.equal(state.snapshot.erkLocalization, "CYTOSOL"); assert.equal(state.snapshot.targetResponse, "TARGET_GENE_INACTIVE"); } });

test("D-G production, P4, serialization, and no-ligand control are deterministic", () => { const program = createCanonicalCellularSignalingProductionProgram(); const production = projectCellularSignalingProductionAtTime(program, 21.3); assert.equal(production.ok, true); if (production.ok) { const frame = applyCellularSignalingExactFrame(production.projection, { width: 1280, height: 720, pixelRatio: 1, background: { mode: "opaque", color: "#101820" } }); assert.equal(frame.ok, true); } assert.equal(JSON.parse(serializeCellularSignalingProgram(program)).actors.rasId, "ras-1"); const noLigand = { ...program, events: program.events.filter((event) => event.at < 18) }; const state = evaluateCellularSignalingAtTime(noLigand, 22); assert.equal(state.ok, true); if (state.ok) assert.equal(state.snapshot.targetResponse, "TARGET_GENE_INACTIVE"); });

test("D-G malformed causal order is rejected", () => { const program = createCanonicalCellularSignalingProgram(); const invalid = { ...program, events: program.events.map((event) => event.kind === "ERK_ACTIVATED" ? { ...event, at: 19 } : event) }; const result = validateCellularSignalingProgram(invalid); assert.equal(result.valid, false); if (!result.valid) assert.ok(result.issues.some((issue) => issue.path.includes("ERK_ACTIVATED"))); });
