/** D-E display projection over the canonical membrane-topology state. */

import type { ScientificActorId } from "./scientific-actor.ts";
import { evaluateMembraneProteinAtTime, type MembraneProteinProgramV1, type MembraneProteinSnapshotV1, type ProteinDomainSide } from "./membrane-protein-topology.ts";

export const membraneProteinProductionOwnerId = "SECRETORY_PATHWAY_CELLULAR_V1" as const;
export type MembraneProteinProductionProjectionV1 = Readonly<{ schemaVersion: "1"; ownerId: typeof membraneProteinProductionOwnerId; programId: string; timeSeconds: number; focus: "ER_INSERTION" | "TOPOLOGY" | "ER_QUALITY" | "GOLGI" | "PLASMA_MEMBRANE"; fidelity: "S2_SCHEMATIC"; proteinId: ScientificActorId; activeMembrane: MembraneProteinSnapshotV1["activeMembrane"]; insertionState: MembraneProteinSnapshotV1["insertionState"]; regions: Readonly<{ nDomain: Readonly<{ regionId: string; side: ProteinDomainSide }>; transmembrane: Readonly<{ regionId: string; side: "MEMBRANE" | "UNRESOLVED" }>; cDomain: Readonly<{ regionId: string; side: ProteinDomainSide }> }>; glycosylationState: MembraneProteinSnapshotV1["glycosylationState"]; disulfideState: MembraneProteinSnapshotV1["disulfideState"]; qualityState: MembraneProteinSnapshotV1["qualityState"]; sourceEventIds: readonly string[] }>;
export type MembraneProteinProductionResult = Readonly<{ ok: true; projection: MembraneProteinProductionProjectionV1 }> | Readonly<{ ok: false; code: string; reasons: readonly string[] }>;
const focus = (snapshot: MembraneProteinSnapshotV1): MembraneProteinProductionProjectionV1["focus"] => snapshot.finalPlasmaMembrane ? "PLASMA_MEMBRANE" : snapshot.activeMembrane?.includes("GOLGI") ? "GOLGI" : snapshot.qualityState === "PASS" ? "ER_QUALITY" : snapshot.insertionState === "INSERTED" || snapshot.insertionState === "PARTIALLY_INSERTED" ? "TOPOLOGY" : "ER_INSERTION";
export function projectMembraneProteinProductionAtTime(program: MembraneProteinProgramV1, timeSeconds: number): MembraneProteinProductionResult { const result = evaluateMembraneProteinAtTime(program, timeSeconds); if (!result.ok) return result; const snapshot = result.snapshot; return { ok: true, projection: { schemaVersion: "1", ownerId: membraneProteinProductionOwnerId, programId: program.programId, timeSeconds, focus: focus(snapshot), fidelity: "S2_SCHEMATIC", proteinId: snapshot.proteinId, activeMembrane: snapshot.activeMembrane, insertionState: snapshot.insertionState, regions: { nDomain: { regionId: "n-domain", side: snapshot.regionSides["n-domain"]! }, transmembrane: { regionId: "tm-helix-1", side: snapshot.regionSides["tm-helix-1"] === "UNRESOLVED" ? "UNRESOLVED" : "MEMBRANE" }, cDomain: { regionId: "c-domain", side: snapshot.regionSides["c-domain"]! } }, glycosylationState: snapshot.glycosylationState, disulfideState: snapshot.disulfideState, qualityState: snapshot.qualityState, sourceEventIds: snapshot.appliedEventIds } }; }
export function validateMembraneProteinProductionProjection(program: MembraneProteinProgramV1, projection: MembraneProteinProductionProjectionV1): MembraneProteinProductionResult { const expected = projectMembraneProteinProductionAtTime(program, projection.timeSeconds); if (!expected.ok) return expected; if (JSON.stringify(expected.projection) !== JSON.stringify(projection)) return { ok: false, code: "MEMBRANE_PRODUCTION_INVALID", reasons: ["production projection contradicts canonical topology state"] }; return expected; }
export function membraneProteinProductionStateAtFrame(program: MembraneProteinProgramV1, frameIndex: number, fps: number): MembraneProteinProductionResult { if (!Number.isInteger(frameIndex) || frameIndex < 0 || !Number.isInteger(fps) || fps <= 0) return { ok: false, code: "MEMBRANE_PRODUCTION_INVALID", reasons: ["frameIndex and fps must be non-negative integers"] }; return projectMembraneProteinProductionAtTime(program, frameIndex / fps); }
export function serializeMembraneProteinProductionProjection(projection: MembraneProteinProductionProjectionV1): string { return JSON.stringify(projection); }
