/** P1-G7 sealed corpus. This module is intentionally excluded from all
 * semantic evaluation/tuning runners. Expectations are independently authored
 * semantic dimensions, not parser outputs. */
import type { BiochemicalDirection, BiologicalStateId, IntentAct, MechanismId, PhenomenonId, ScreenDirection, SemanticEntityId, MisconceptionStatus } from "./foundation-semantic-vocabulary.ts";
import type { ScientificClaimOutcome } from "./semantic-misconception-policy.ts";

export type P1G7Category = "lexicalParaphrase" | "implicitEntity" | "ambiguityClarification" | "mechanismDistinction" | "compoundAssociation" | "acts" | "claims" | "biochemicalDirection" | "localChemistry" | "crossDomain" | "misconceptionValidity" | "multiIntent";
export type P1G7Difficulty = "MEDIUM" | "HARD" | "ADVERSARIAL";
export type P1G7Domain = "DNA" | "RNA" | "CROSS_DOMAIN";
export type P1G7Requirement = "REQUIRED" | "OPTIONAL" | "ALLOWED_ALTERNATIVE" | "UNREPRESENTABLE_IN_F1";
export type P1G7Field<T> = { requirement: P1G7Requirement; value?: T; alternatives?: readonly T[] };
export type P1G7Claim = { rawText: string; status: MisconceptionStatus };
export type P1G7Expected = {
  acts: P1G7Field<IntentAct[]>;
  entities: P1G7Field<SemanticEntityId[]>;
  phenomena: P1G7Field<PhenomenonId[]>;
  mechanisms: P1G7Field<MechanismId[]>;
  states?: P1G7Field<BiologicalStateId[]>;
  biochemicalDirection?: P1G7Field<BiochemicalDirection>;
  screenDirection?: P1G7Field<ScreenDirection>;
  claims?: P1G7Field<P1G7Claim[]>;
  clarification: P1G7Field<boolean>;
  misconceptionOutcome: P1G7Field<ScientificClaimOutcome>;
  multiIntentInvariants?: P1G7Field<{ preserveActs: IntentAct[]; preservePhenomena: PhenomenonId[]; preserveMechanisms: MechanismId[]; noInventedSequence: boolean }>;
  unrepresentable?: readonly { field: string; reason: string }[];
};
export type P1G7HoldoutCase = { id: string; prompt: string; category: P1G7Category; difficulty: P1G7Difficulty; domain: P1G7Domain; expected: P1G7Expected };

const req = <T>(value: T): P1G7Field<T> => ({ requirement: "REQUIRED", value });
const opt = <T>(value: T): P1G7Field<T> => ({ requirement: "OPTIONAL", value });
const alt = <T>(alternatives: readonly T[]): P1G7Field<T> => ({ requirement: "ALLOWED_ALTERNATIVE", alternatives });
const unrep = <T>(): P1G7Field<T> => ({ requirement: "UNREPRESENTABLE_IN_F1" });
const claim = (rawText: string, status: MisconceptionStatus): P1G7Claim[] => [{ rawText, status }];
const expected = (acts: IntentAct[], entities: SemanticEntityId[], phenomena: PhenomenonId[], mechanisms: MechanismId[], clarification = false, outcome: ScientificClaimOutcome = "ACCEPT", extra: Partial<P1G7Expected> = {}): P1G7Expected => ({ acts: req(acts), entities: req(entities), phenomena: req(phenomena), mechanisms: req(mechanisms), clarification: req(clarification), misconceptionOutcome: req(outcome), ...extra });

export const p1G7HoldoutV3: readonly P1G7HoldoutCase[] = [
  { id: "h3-lex-001", prompt: "Make a clean picture of the inherited-information molecule with both rails intact.", category: "lexicalParaphrase", difficulty: "MEDIUM", domain: "DNA", expected: expected(["show"], ["dna", "strand", "duplex"], [], []) },
  { id: "h3-lex-002", prompt: "I need the RNA message's sugar and phosphate chain, not a protein sketch.", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: expected(["show"], ["rna", "mRNA", "ribose", "phosphate"], ["backboneChemistry"], ["phosphodiesterLinkage"]) },
  { id: "h3-lex-003", prompt: "Can you make the A–U contact in an RNA strand visible and local?", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: expected(["show"], ["rna", "adenine", "uracil"], ["canonicalBasePairing"], ["hydrogenBonding"], false, "ACCEPT", { states: req(["paired"]) }) },
  { id: "h3-lex-004", prompt: "Talk me through what the little cap at a messenger's 5-prime end is for.", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: expected(["explain"], ["mRNA", "cap"], ["rnaProcessing"], ["rnaCapping"], false, "ACCEPT", { states: req(["capped"]) }) },

  { id: "h3-ent-001", prompt: "Show the molecule that carries the instructions passed from parent to child, including its opposite rails.", category: "implicitEntity", difficulty: "HARD", domain: "DNA", expected: expected(["show"], ["dna", "strand", "duplex"], ["polarity"], ["antiparallelOrganization"]) },
  { id: "h3-ent-002", prompt: "Which sugar carries the two-prime hydroxyl in the RNA message?", category: "implicitEntity", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["rna", "mRNA", "ribose", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h3-ent-003", prompt: "At the copying fork, show the motor that unwinds the template and the machine that extends the daughter chain.", category: "implicitEntity", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show"], ["dna", "replicationFork", "helicase", "polymerase", "strand"], ["replication", "strandSeparation"], ["dnaReplication", "strandOpening"]) },
  { id: "h3-ent-004", prompt: "Point out the product just leaving the DNA instructions while it is still being made.", category: "implicitEntity", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show", "inspect"], ["dna", "rna", "mRNA"], ["transcription"], ["transcriptionElongation"], false, "ACCEPT", { states: req(["nascent"]), unrepresentable: [{ field: "fineGrainedTemplateRole", reason: "F1-v1 does not encode template/coding strand roles at this granularity." }] }) },

  { id: "h3-amb-001", prompt: "This chain changed somehow—was one internal link cut, or did an end get nibbled away?", category: "ambiguityClarification", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["explain"], ["strand"], ["cleavage", "exonucleaseDegradation"], ["rnaCleavage", "terminalExonucleaseAction"], true) },
  { id: "h3-amb-002", prompt: "When these RNA and DNA pieces touch, should I understand a hybrid or only nearby molecules?", category: "ambiguityClarification", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], true, "ACCEPT", { unrepresentable: [{ field: "genericAssociation", reason: "F1-v1 has no generic co-localization phenomenon; do not score it as a hidden hybrid." }] }) },
  { id: "h3-amb-003", prompt: "What opened the helix here—the replication motor or the transcription machinery?", category: "ambiguityClarification", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "duplex", "helicase", "rnaPolymerase"], ["strandSeparation", "transcription"], ["strandOpening", "transcriptionElongation"], true) },
  { id: "h3-amb-004", prompt: "Pair this base; I did not tell you whether the molecule is DNA or RNA.", category: "ambiguityClarification", difficulty: "MEDIUM", domain: "CROSS_DOMAIN", expected: expected(["show"], ["base", "dna", "rna"], ["basePairing"], ["hydrogenBonding"], true) },

  { id: "h3-mech-001", prompt: "Explain the difference between an RNA backbone cut and shortening from a terminus.", category: "mechanismDistinction", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["explain", "compare"], ["rna", "phosphodiesterLinkage"], ["cleavage", "exonucleaseDegradation"], ["rnaCleavage", "terminalExonucleaseAction", "phosphodiesterLinkage"], true) },
  { id: "h3-mech-002", prompt: "Show fork-driven DNA opening, not the small bubble used while RNA is transcribed.", category: "mechanismDistinction", difficulty: "HARD", domain: "DNA", expected: expected(["show"], ["dna", "replicationFork", "helicase", "transcriptionBubble", "rnaPolymerase"], ["strandSeparation", "replication", "transcription"], ["strandOpening", "dnaReplication", "transcriptionElongation"], true) },
  { id: "h3-mech-003", prompt: "Are these polymers actually hybridized, or just colocated for the lesson?", category: "mechanismDistinction", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], true) },
  { id: "h3-mech-004", prompt: "Separate the stacking forces from the hydrogen bonds in this DNA pair.", category: "mechanismDistinction", difficulty: "HARD", domain: "DNA", expected: expected(["explain", "compare"], ["dna", "duplex", "base", "stackingFace"], ["basePairing", "helixStabilization"], ["hydrogenBonding", "baseStacking"], false, "ACCEPT", { states: req(["paired"]) }) },

  { id: "h3-comp-001", prompt: "Show the copying fork, explain the unwinding, and keep the new strand's extension in the same account.", category: "compoundAssociation", difficulty: "HARD", domain: "DNA", expected: expected(["show", "explain"], ["dna", "replicationFork", "helicase", "polymerase", "strand"], ["replication", "strandSeparation"], ["dnaReplication", "strandOpening"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["replication", "strandSeparation"], preserveMechanisms: ["dnaReplication", "strandOpening"], noInventedSequence: true }) }) },
  { id: "h3-comp-002", prompt: "Put an RNA hairpin beside an RNA–DNA hybrid and compare folding with cross-polymer pairing.", category: "compoundAssociation", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["show", "compare"], ["rna", "dna", "duplex"], ["rnaSecondaryStructure", "rnaDnaHybridization"], ["rnaSecondaryFolding", "rnaDnaHybridFormation"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["show", "compare"], preservePhenomena: ["rnaSecondaryStructure", "rnaDnaHybridization"], preserveMechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation"], noInventedSequence: true }) }) },
  { id: "h3-comp-003", prompt: "Show the transcript's cap and splicing together; do not reduce both operations to one generic break.", category: "compoundAssociation", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["show"], ["mRNA", "cap", "intron", "exon"], ["rnaProcessing"], ["rnaCapping", "rnaSplicing"], false, "ACCEPT", { states: req(["preMRNA", "matureMRNA", "capped"]), multiIntentInvariants: req({ preserveActs: ["show"], preservePhenomena: ["rnaProcessing"], preserveMechanisms: ["rnaCapping", "rnaSplicing"], noInventedSequence: true }) }) },
  { id: "h3-comp-004", prompt: "Show a G–C pair and explain how stacking keeps the surrounding helix ordered.", category: "compoundAssociation", difficulty: "HARD", domain: "DNA", expected: expected(["show", "explain"], ["dna", "guanine", "cytosine", "duplex"], ["canonicalBasePairing", "helixStabilization"], ["hydrogenBonding", "baseStacking"], false, "ACCEPT", { states: req(["paired"]) }) },

  { id: "h3-act-001", prompt: "What is happening at the capped end of this messenger?", category: "acts", difficulty: "HARD", domain: "RNA", expected: expected(["explain"], ["mRNA", "cap"], ["rnaProcessing"], ["rnaCapping"]) },
  { id: "h3-act-002", prompt: "Which atom group should I inspect on the ribose at position two?", category: "acts", difficulty: "MEDIUM", domain: "RNA", expected: expected(["inspect"], ["ribose", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h3-act-003", prompt: "Contrast an RNA sugar with its DNA counterpart, and explain why the difference matters.", category: "acts", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["compare", "explain"], ["rna", "dna", "ribose", "deoxyribose"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h3-act-004", prompt: "Point to the phosphate bridge that joins neighboring nucleotides.", category: "acts", difficulty: "HARD", domain: "DNA", expected: expected(["show", "inspect"], ["phosphate", "nucleotide", "phosphodiesterLinkage"], ["backboneChemistry"], ["phosphodiesterLinkage"]) },

  { id: "h3-claim-001", prompt: "DNA has ribose, doesn't it? Please check my assumption rather than accepting it.", category: "claims", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["dna", "ribose"], [], [], false, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("DNA has ribose", "suspected")) }) },
  { id: "h3-claim-002", prompt: "A published source reports that RNA uses thymine; show what that claim would imply.", category: "claims", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["show", "explain"], ["rna", "thymine"], [], [], false, "CORRECTION_REQUIRED", { claims: req(claim("RNA uses thymine", "validated")) }) },
  { id: "h3-claim-003", prompt: "My teacher says the DNA rails run the same way. Can you show whether that is true?", category: "claims", difficulty: "HARD", domain: "DNA", expected: expected(["show", "explain"], ["dna", "strand", "duplex"], ["polarity"], ["antiparallelOrganization"], false, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("the DNA rails run the same way", "suspected")) }) },
  { id: "h3-claim-004", prompt: "Could the RNA hydroxyl be why this polymer is chemically easier to break than DNA?", category: "claims", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"], false, "ACCEPT", { claims: req(claim("the RNA hydroxyl could explain greater chemical lability than DNA", "neutral")) }) },

  { id: "h3-dir-001", prompt: "The exonuclease starts at the transcript's three-prime end; show the chemical travel direction, not a screen arrow.", category: "biochemicalDirection", difficulty: "HARD", domain: "RNA", expected: expected(["show"], ["rna"], ["exonucleaseDegradation"], ["terminalExonucleaseAction"], false, "ACCEPT", { states: req(["partiallyDegraded"]), biochemicalDirection: req("threeToFive") }) },
  { id: "h3-dir-002", prompt: "The terminus on the left is only a drawing choice; show the RNA cut without inferring a biochemical direction.", category: "biochemicalDirection", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["show"], ["rna"], ["cleavage"], ["rnaCleavage"], true, "ACCEPT", { screenDirection: req("screenLeft"), biochemicalDirection: opt("unknown") }) },
  { id: "h3-dir-003", prompt: "Follow synthesis toward the five-prime end of the daughter strand while ignoring page orientation.", category: "biochemicalDirection", difficulty: "HARD", domain: "DNA", expected: expected(["show", "explain"], ["dna", "strand"], ["replication"], ["dnaReplication"], false, "ACCEPT", { biochemicalDirection: req("threeToFive") }) },
  { id: "h3-dir-004", prompt: "Annotate each DNA strand's biochemical termini; their placement on the display can be arbitrary.", category: "biochemicalDirection", difficulty: "MEDIUM", domain: "DNA", expected: expected(["show"], ["dna", "strand", "duplex"], ["polarity"], ["antiparallelOrganization"], false, "ACCEPT", { biochemicalDirection: req("strandRelative") }) },

  { id: "h3-local-001", prompt: "Focus on the phosphodiester site that is broken during this RNA cleavage.", category: "localChemistry", difficulty: "HARD", domain: "RNA", expected: expected(["show", "inspect"], ["rna", "phosphodiesterLinkage"], ["cleavage", "backboneChemistry"], ["rnaCleavage", "phosphodiesterLinkage"]) },
  { id: "h3-local-002", prompt: "What makes the ribose two-prime substituent render an RNA chain more hydrolysis-prone than a deoxyribose chain?", category: "localChemistry", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h3-local-003", prompt: "Show the phosphate connection made when one nucleotide is added to a growing strand.", category: "localChemistry", difficulty: "HARD", domain: "DNA", expected: expected(["show"], ["nucleotide", "phosphate", "strand"], ["nucleotideAssembly", "backboneChemistry"], ["nucleotideAddition", "phosphodiesterLinkage"], false, "ACCEPT", { states: req(["forming"]) }) },
  { id: "h3-local-004", prompt: "Identify the base's attachment point on the one-prime carbon of the ribose ring.", category: "localChemistry", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["base", "onePrimeCarbon", "ribose"], ["backboneChemistry"], [], false, "ACCEPT", { mechanisms: alt([["phosphodiesterLinkage"], []] as unknown as MechanismId[][]) }) },

  { id: "h3-cross-001", prompt: "Why is comparing a ribose transcript with a deoxyribose polymer useful here?", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain", "compare"], ["rna", "dna", "ribose", "deoxyribose"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h3-cross-002", prompt: "Put an RNA strand against DNA and keep the two sugar identities visible in the hybrid.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show"], ["rna", "dna", "strand"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], false, "ACCEPT", { states: req(["hybridized"]) }) },
  { id: "h3-cross-003", prompt: "A U-containing partner is present; inspect whether it belongs to RNA or DNA before choosing the pairing explanation.", category: "crossDomain", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["inspect", "explain"], ["uracil", "rna", "dna"], ["basePairing"], ["hydrogenBonding"], true) },
  { id: "h3-cross-004", prompt: "The RNA copy is leaving its DNA template; show the contact and identify which chain is nascent.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show", "inspect"], ["rna", "dna", "mRNA"], ["transcription"], ["transcriptionElongation"], false, "ACCEPT", { states: req(["nascent"]) }) },

  { id: "h3-valid-001", prompt: "Does DNA really contain a ribose ring? Explain the correction without changing my question.", category: "misconceptionValidity", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "ribose"], [], [], false, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("DNA contains a ribose ring", "suspected")) }) },
  { id: "h3-valid-002", prompt: "A paper concludes that uracil is the normal DNA base; present that claim for checking.", category: "misconceptionValidity", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show"], ["dna", "uracil"], [], [], false, "CORRECTION_REQUIRED", { claims: req(claim("uracil is the normal DNA base", "validated")) }) },
  { id: "h3-valid-003", prompt: "Can you show a normal RNA-DNA hybrid, or is that scientifically impossible?", category: "misconceptionValidity", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show", "explain"], ["rna", "dna"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], false, "ACCEPT") },
  { id: "h3-valid-004", prompt: "RNA has a two-prime hydroxyl, so it should be less stable than DNA—does that reasoning hold?", category: "misconceptionValidity", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"], false, "ACCEPT", { claims: req(claim("RNA has a two-prime hydroxyl and is therefore less stable than DNA", "suspected")) }) },

  { id: "h3-multi-001", prompt: "Show DNA opening at the replication fork and explain how the daughter strands acquire their direction labels.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show", "explain"], ["dna", "replicationFork", "strand", "helicase"], ["strandSeparation", "replication", "polarity"], ["strandOpening", "dnaReplication", "antiparallelOrganization"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["strandSeparation", "replication", "polarity"], preserveMechanisms: ["strandOpening", "dnaReplication", "antiparallelOrganization"], noInventedSequence: true }) }) },
  { id: "h3-multi-002", prompt: "A compact RNA fold and a cross-polymer duplex need side-by-side explanation—contrast what each pairing context means.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["compare", "explain"], ["rna", "dna", "duplex"], ["rnaSecondaryStructure", "rnaDnaHybridization"], ["rnaSecondaryFolding", "rnaDnaHybridFormation"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["compare", "explain"], preservePhenomena: ["rnaSecondaryStructure", "rnaDnaHybridization"], preserveMechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation"], noInventedSequence: true }) }) },
  { id: "h3-multi-003", prompt: "Show the pre-message's introns and cap, and compare it with the processed message without inventing a splice timeline.", category: "multiIntent", difficulty: "HARD", domain: "RNA", expected: expected(["show", "compare"], ["mRNA", "intron", "exon", "cap"], ["rnaProcessing"], ["rnaSplicing", "rnaCapping"], false, "ACCEPT", { states: req(["preMRNA", "matureMRNA", "capped"]), multiIntentInvariants: req({ preserveActs: ["show", "compare"], preservePhenomena: ["rnaProcessing"], preserveMechanisms: ["rnaSplicing", "rnaCapping"], noInventedSequence: true }) }) },
  { id: "h3-multi-004", prompt: "Show the nascent RNA leaving DNA, explain its 3-prime synthesis end, and keep the local pairing context separate from the full duplex.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["show", "explain"], ["rna", "dna", "mRNA", "duplex"], ["transcription", "rnaDnaHybridization"], ["transcriptionElongation", "rnaDnaHybridFormation"], false, "ACCEPT", { states: req(["nascent", "hybridized"]), biochemicalDirection: req("fiveToThree"), multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["transcription", "rnaDnaHybridization"], preserveMechanisms: ["transcriptionElongation", "rnaDnaHybridFormation"], noInventedSequence: true }) }) },
] as const;

export const p1G7HoldoutV3CaseIds = p1G7HoldoutV3.map(({ id }) => id);
