/** P1-G6 sealed data. Do not import from development evaluation code. */
import type { BiochemicalDirection, IntentAct, MechanismId, PhenomenonId, ScreenDirection, SemanticEntityId, BiologicalStateId, MisconceptionStatus } from "./foundation-semantic-vocabulary.ts";
import type { ScientificClaimOutcome } from "./semantic-misconception-policy.ts";

export type P1G6Category = "lexicalParaphrase" | "ambiguityClarification" | "scientificClaims" | "multiIntent" | "entityCompleteness" | "mechanismDistinction" | "biochemicalDirection" | "crossDomain";
export type P1G6Difficulty = "MEDIUM" | "HARD" | "ADVERSARIAL";
export type P1G6Domain = "DNA" | "RNA" | "CROSS_DOMAIN";
export type P1G6ExpectedClaim = { rawText: string; status: MisconceptionStatus };
export type P1G6Expected = {
  acts: readonly IntentAct[];
  entities: readonly SemanticEntityId[];
  phenomena: readonly PhenomenonId[];
  mechanisms: readonly MechanismId[];
  states?: readonly BiologicalStateId[];
  biochemicalDirection?: BiochemicalDirection;
  screenDirection?: ScreenDirection;
  claims?: readonly P1G6ExpectedClaim[];
  clarificationRequired: boolean;
  misconceptionOutcome: ScientificClaimOutcome;
  multiIntentInvariants?: { preserveActs: readonly IntentAct[]; preservePhenomena: readonly PhenomenonId[]; preserveMechanisms: readonly MechanismId[]; noInventedSequence: boolean };
  criticalErrors: readonly string[];
};
export type P1G6HoldoutCase = { id: string; prompt: string; category: P1G6Category; difficulty: P1G6Difficulty; domain: P1G6Domain; expected: P1G6Expected };

const critical = ["DNA/RNA substitution", "claim rewritten as truth", "explicit act or clause loss"] as const;
const directionCritical = [...critical, "biochemical/screen direction conflation"] as const;
const clarificationCritical = [...critical, "required clarification skipped"] as const;

/** Independently authored expectations; this module contains no parser calls. */
export const p1G6HoldoutV2: readonly P1G6HoldoutCase[] = [
  { id: "h2a-001", prompt: "Could you sketch the molecule that carries hereditary instructions, with its paired strands?", category: "lexicalParaphrase", difficulty: "MEDIUM", domain: "DNA", expected: { acts: ["show"], entities: ["dna", "duplex", "strand"], phenomena: [], mechanisms: [], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2a-002", prompt: "Give me the sugar-phosphate chain for an RNA message, not a protein cartoon.", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: { acts: ["show"], entities: ["rna", "mRNA", "ribose", "phosphate"], phenomena: ["backboneChemistry"], mechanisms: ["phosphodiesterLinkage"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2a-003", prompt: "I want the little A-to-U handshake in an RNA strand, with the contacts visible.", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: { acts: ["show"], entities: ["rna", "adenine", "uracil"], phenomena: ["canonicalBasePairing"], mechanisms: ["hydrogenBonding"], states: ["paired"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2a-004", prompt: "What is the cap doing at the front end of a messenger RNA?", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: { acts: ["explain"], entities: ["mRNA", "cap"], phenomena: ["rnaProcessing"], mechanisms: ["rnaCapping"], states: ["capped"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },

  { id: "h2b-001", prompt: "Show the chain being cut, but don't assume whether an end-chewing enzyme is involved.", category: "ambiguityClarification", difficulty: "ADVERSARIAL", domain: "RNA", expected: { acts: ["show"], entities: ["rna"], phenomena: ["cleavage", "exonucleaseDegradation"], mechanisms: ["rnaCleavage", "terminalExonucleaseAction"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2b-002", prompt: "Put these two polymers together—do you mean an RNA-DNA hybrid or just a physical association?", category: "ambiguityClarification", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["show"], entities: ["rna", "dna"], phenomena: ["rnaDnaHybridization"], mechanisms: ["rnaDnaHybridFormation"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2b-003", prompt: "Which molecular machine is responsible for opening this helix?", category: "ambiguityClarification", difficulty: "HARD", domain: "DNA", expected: { acts: ["explain"], entities: ["dna", "duplex", "helicase", "rnaPolymerase"], phenomena: ["strandSeparation", "transcription"], mechanisms: ["strandOpening", "transcriptionElongation"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2b-004", prompt: "Can you show the strand after the enzyme has worked on it?", category: "ambiguityClarification", difficulty: "HARD", domain: "RNA", expected: { acts: ["show"], entities: ["rna"], phenomena: ["cleavage", "exonucleaseDegradation", "rnaProcessing"], mechanisms: ["rnaCleavage", "terminalExonucleaseAction", "rnaSplicing"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2b-005", prompt: "Display the base pair here—DNA or RNA is fine; I haven't specified which.", category: "ambiguityClarification", difficulty: "MEDIUM", domain: "CROSS_DOMAIN", expected: { acts: ["show"], entities: ["base", "strand"], phenomena: ["basePairing"], mechanisms: ["hydrogenBonding"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },

  { id: "h2c-001", prompt: "DNA has the same sugar as RNA, right? Explain the difference rather than silently choosing one.", category: "scientificClaims", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["explain", "compare"], entities: ["dna", "rna", "ribose", "deoxyribose"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"], claims: [{ rawText: "DNA has the same sugar as RNA", status: "suspected" }], clarificationRequired: false, misconceptionOutcome: "CLAIM_REQUIRES_GROUNDING", criticalErrors: critical } },
  { id: "h2c-002", prompt: "I was told the two DNA strands point the same way; can you check that claim and show the directions?", category: "scientificClaims", difficulty: "HARD", domain: "DNA", expected: { acts: ["explain", "show"], entities: ["dna", "strand", "duplex"], phenomena: ["polarity"], mechanisms: ["antiparallelOrganization"], claims: [{ rawText: "the two DNA strands point the same way", status: "suspected" }], clarificationRequired: false, misconceptionOutcome: "CLAIM_REQUIRES_GROUNDING", criticalErrors: critical } },
  { id: "h2c-003", prompt: "A validated source says uracil is a DNA base; please present that conclusion.", category: "scientificClaims", difficulty: "ADVERSARIAL", domain: "DNA", expected: { acts: ["show"], entities: ["dna", "uracil"], phenomena: ["basePairing"], mechanisms: [], claims: [{ rawText: "uracil is a DNA base", status: "validated" }], clarificationRequired: false, misconceptionOutcome: "CORRECTION_REQUIRED", criticalErrors: [...critical, "valid request classified invalid"] } },
  { id: "h2c-004", prompt: "Could RNA and DNA differ in stability because one has a reactive 2-prime hydroxyl?", category: "scientificClaims", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["explain"], entities: ["rna", "dna", "riboseTwoPrimeHydroxyl"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"], claims: [{ rawText: "RNA and DNA differ in stability because one has a reactive 2-prime hydroxyl", status: "neutral" }], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },

  { id: "h2d-001", prompt: "Show the fork and tell me how helicase opens it while polymerase copies the template.", category: "multiIntent", difficulty: "HARD", domain: "DNA", expected: { acts: ["show", "explain"], entities: ["dna", "replicationFork", "helicase", "polymerase", "strand"], phenomena: ["replication", "strandSeparation"], mechanisms: ["dnaReplication", "strandOpening"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["show", "explain"], preservePhenomena: ["replication", "strandSeparation"], preserveMechanisms: ["dnaReplication", "strandOpening"], noInventedSequence: true }, criticalErrors: critical } },
  { id: "h2d-002", prompt: "Set an RNA stem-loop beside a mixed DNA/RNA duplex and contrast the matching rules in the two cases.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: { acts: ["compare", "explain"], entities: ["rna", "dna", "duplex", "strand"], phenomena: ["rnaSecondaryStructure", "rnaDnaHybridization", "basePairing"], mechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation", "hydrogenBonding"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["compare", "explain"], preservePhenomena: ["rnaSecondaryStructure", "rnaDnaHybridization", "basePairing"], preserveMechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation", "hydrogenBonding"], noInventedSequence: true }, criticalErrors: critical } },
  { id: "h2d-003", prompt: "Show the pre-message before and after splicing, and point out the cap without turning it into a cleavage scene.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "RNA", expected: { acts: ["show", "inspect"], entities: ["mRNA", "intron", "exon", "cap"], phenomena: ["rnaProcessing"], mechanisms: ["rnaSplicing", "rnaCapping"], states: ["preMRNA", "matureMRNA", "capped"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["show", "inspect"], preservePhenomena: ["rnaProcessing"], preserveMechanisms: ["rnaSplicing", "rnaCapping"], noInventedSequence: true }, criticalErrors: critical } },
  { id: "h2d-004", prompt: "I need a picture of a G-C contact and an explanation of why the helix stays organized around it.", category: "multiIntent", difficulty: "HARD", domain: "DNA", expected: { acts: ["show", "explain"], entities: ["dna", "guanine", "cytosine", "duplex"], phenomena: ["basePairing", "helixStabilization"], mechanisms: ["hydrogenBonding", "baseStacking"], states: ["paired"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["show", "explain"], preservePhenomena: ["basePairing", "helixStabilization"], preserveMechanisms: ["hydrogenBonding", "baseStacking"], noInventedSequence: true }, criticalErrors: critical } },
  { id: "h2d-005", prompt: "Show a short nascent transcript beside its DNA template and explain how the RNA exits the transcription site.", category: "multiIntent", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["show", "explain"], entities: ["dna", "rna", "transcriptionBubble", "rnaPolymerase"], phenomena: ["transcription"], mechanisms: ["transcriptionElongation"], states: ["nascent", "open"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["show", "explain"], preservePhenomena: ["transcription"], preserveMechanisms: ["transcriptionElongation"], noInventedSequence: true }, criticalErrors: critical } },

  { id: "h2e-001", prompt: "Put the enzyme, the RNA substrate, and the newly exposed terminus in one degradation explanation.", category: "entityCompleteness", difficulty: "HARD", domain: "RNA", expected: { acts: ["show", "explain"], entities: ["rna", "strand", "fivePrimeCarbon"], phenomena: ["exonucleaseDegradation"], mechanisms: ["terminalExonucleaseAction"], states: ["partiallyDegraded"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2e-002", prompt: "At the fork, include the template, its partner, the helicase, and the copying polymerase—not just a generic DNA line.", category: "entityCompleteness", difficulty: "HARD", domain: "DNA", expected: { acts: ["show"], entities: ["dna", "strand", "replicationFork", "helicase", "polymerase"], phenomena: ["replication"], mechanisms: ["dnaReplication", "strandOpening"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2e-003", prompt: "Show the capped, spliced message with its exon order and the excised intron region still identified.", category: "entityCompleteness", difficulty: "HARD", domain: "RNA", expected: { acts: ["show"], entities: ["mRNA", "cap", "exon", "intron"], phenomena: ["rnaProcessing"], mechanisms: ["rnaCapping", "rnaSplicing"], states: ["preMRNA", "matureMRNA", "capped"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2e-004", prompt: "For the hybrid, identify both polymers and which strand supplies the template rather than treating it as an unnamed duplex.", category: "entityCompleteness", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["show", "inspect"], entities: ["rna", "dna", "duplex", "strand"], phenomena: ["rnaDnaHybridization"], mechanisms: ["rnaDnaHybridFormation"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },

  { id: "h2f-001", prompt: "Is the RNA being cut at one internal phosphodiester site or shortened from an end? Keep those mechanisms separate.", category: "mechanismDistinction", difficulty: "ADVERSARIAL", domain: "RNA", expected: { acts: ["compare", "explain"], entities: ["rna", "phosphodiesterLinkage"], phenomena: ["cleavage", "exonucleaseDegradation"], mechanisms: ["rnaCleavage", "terminalExonucleaseAction", "phosphodiesterLinkage"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2f-002", prompt: "Show opening caused by a fork motor, not the local opening made for transcription.", category: "mechanismDistinction", difficulty: "HARD", domain: "DNA", expected: { acts: ["show"], entities: ["dna", "replicationFork", "helicase", "transcriptionBubble", "rnaPolymerase"], phenomena: ["strandSeparation", "replication", "transcription"], mechanisms: ["strandOpening", "dnaReplication", "transcriptionElongation"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2f-003", prompt: "Explain whether this RNA-DNA contact is a hybrid duplex or merely co-localized molecules.", category: "mechanismDistinction", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["explain"], entities: ["rna", "dna", "duplex"], phenomena: ["rnaDnaHybridization"], mechanisms: ["rnaDnaHybridFormation"], clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: clarificationCritical } },
  { id: "h2f-004", prompt: "Distinguish base stacking from the hydrogen bonds that pair the bases in this duplex.", category: "mechanismDistinction", difficulty: "HARD", domain: "DNA", expected: { acts: ["compare", "explain"], entities: ["dna", "duplex", "base", "stackingFace"], phenomena: ["basePairing", "helixStabilization"], mechanisms: ["hydrogenBonding", "baseStacking"], states: ["paired"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },

  { id: "h2g-001", prompt: "An exonuclease eats this message from the far end marked 3-prime; show the resulting direction.", category: "biochemicalDirection", difficulty: "HARD", domain: "RNA", expected: { acts: ["show"], entities: ["rna"], phenomena: ["exonucleaseDegradation"], mechanisms: ["terminalExonucleaseAction"], states: ["partiallyDegraded"], biochemicalDirection: "threeToFive", clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: directionCritical } },
  { id: "h2g-002", prompt: "Trim the transcript at the terminus drawn on the left side of the figure; left is layout, not the chemical direction.", category: "biochemicalDirection", difficulty: "ADVERSARIAL", domain: "RNA", expected: { acts: ["show"], entities: ["rna"], phenomena: ["cleavage"], mechanisms: ["rnaCleavage"], screenDirection: "screenLeft", clarificationRequired: true, misconceptionOutcome: "ACCEPT", criticalErrors: directionCritical } },
  { id: "h2g-003", prompt: "Follow the daughter strand's synthesis toward its 5-prime end while keeping the page orientation irrelevant.", category: "biochemicalDirection", difficulty: "HARD", domain: "DNA", expected: { acts: ["show", "explain"], entities: ["dna", "strand"], phenomena: ["replication"], mechanisms: ["dnaReplication"], biochemicalDirection: "threeToFive", clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: directionCritical } },
  { id: "h2g-004", prompt: "Put the 5-prime and 3-prime labels on opposite DNA strands, wherever they land on screen.", category: "biochemicalDirection", difficulty: "MEDIUM", domain: "DNA", expected: { acts: ["show"], entities: ["dna", "strand", "duplex"], phenomena: ["polarity"], mechanisms: ["antiparallelOrganization"], biochemicalDirection: "strandRelative", clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: directionCritical } },

  { id: "h2h-001", prompt: "Why does a ribose-containing transcript make a DNA comparison meaningful here?", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["explain", "compare"], entities: ["rna", "dna", "ribose", "deoxyribose"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2h-002", prompt: "Show RNA paired to DNA, then contrast that with two strands made from the same polymer.", category: "crossDomain", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: { acts: ["show", "compare"], entities: ["rna", "dna", "duplex", "strand"], phenomena: ["rnaDnaHybridization", "basePairing"], mechanisms: ["rnaDnaHybridFormation", "hydrogenBonding"], states: ["hybridized", "paired"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["show", "compare"], preservePhenomena: ["rnaDnaHybridization", "basePairing"], preserveMechanisms: ["rnaDnaHybridFormation", "hydrogenBonding"], noInventedSequence: true }, criticalErrors: critical } },
  { id: "h2h-003", prompt: "A student calls this U-T match a DNA pair; identify the polymers before explaining the bases.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["inspect", "explain"], entities: ["rna", "dna", "uracil", "thymine"], phenomena: ["basePairing"], mechanisms: ["hydrogenBonding"], claims: [{ rawText: "this U-T match is a DNA pair", status: "suspected" }], clarificationRequired: false, misconceptionOutcome: "CLAIM_REQUIRES_GROUNDING", criticalErrors: critical } },
  { id: "h2h-004", prompt: "Compare the RNA and DNA sugars at the same position, and keep the missing 2-prime OH explicit.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["compare", "inspect"], entities: ["rna", "dna", "ribose", "deoxyribose", "riboseTwoPrimeHydroxyl"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", criticalErrors: critical } },
  { id: "h2h-005", prompt: "If the RNA copy is emerging from DNA, show the local contact and say which molecule is the transcript.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: { acts: ["show", "explain"], entities: ["dna", "rna", "transcriptionBubble"], phenomena: ["transcription", "rnaDnaHybridization"], mechanisms: ["transcriptionElongation", "rnaDnaHybridFormation"], states: ["nascent", "hybridized"], clarificationRequired: false, misconceptionOutcome: "ACCEPT", multiIntentInvariants: { preserveActs: ["show", "explain"], preservePhenomena: ["transcription", "rnaDnaHybridization"], preserveMechanisms: ["transcriptionElongation", "rnaDnaHybridFormation"], noInventedSequence: true }, criticalErrors: critical } },
] as const;

export const p1G6HoldoutV2CaseIds = p1G6HoldoutV2.map(({ id }) => id);
