/** P1-G8 sealed corpus. This module is never imported by semantic evaluation
 * or tuning runners. Expectations are authored from user meaning, not output. */
import type { BiochemicalDirection, BiologicalStateId, IntentAct, MechanismId, PhenomenonId, ScreenDirection, SemanticEntityId, MisconceptionStatus } from "./foundation-semantic-vocabulary.ts";
import type { ScientificClaimOutcome } from "./semantic-misconception-policy.ts";

export type P1G8Category = "lexicalParaphrase" | "implicitEntity" | "ambiguityClarification" | "mechanismDistinction" | "compoundAssociation" | "acts" | "claims" | "biochemicalDirection" | "localChemistry" | "crossDomain" | "misconceptionValidity" | "multiIntent";
export type P1G8Difficulty = "MEDIUM" | "HARD" | "ADVERSARIAL";
export type P1G8Domain = "DNA" | "RNA" | "CROSS_DOMAIN";
export type P1G8Requirement = "REQUIRED" | "OPTIONAL" | "ALLOWED_ALTERNATIVE" | "UNREPRESENTABLE_IN_F1";
export type P1G8Field<T> = { requirement: P1G8Requirement; value?: T; alternatives?: readonly T[] };
export type P1G8Claim = { rawText: string; status: MisconceptionStatus };
export type P1G8Expected = {
  acts: P1G8Field<IntentAct[]>;
  entities: P1G8Field<SemanticEntityId[]>;
  phenomena: P1G8Field<PhenomenonId[]>;
  mechanisms: P1G8Field<MechanismId[]>;
  states?: P1G8Field<BiologicalStateId[]>;
  biochemicalDirection?: P1G8Field<BiochemicalDirection>;
  screenDirection?: P1G8Field<ScreenDirection>;
  claims?: P1G8Field<P1G8Claim[]>;
  clarification: P1G8Field<boolean>;
  misconceptionOutcome: P1G8Field<ScientificClaimOutcome>;
  multiIntentInvariants?: P1G8Field<{ preserveActs: IntentAct[]; preservePhenomena: PhenomenonId[]; preserveMechanisms: MechanismId[]; noInventedSequence: boolean }>;
  unrepresentable?: readonly { field: string; reason: string }[];
};
export type P1G8HoldoutCase = { id: string; prompt: string; category: P1G8Category; difficulty: P1G8Difficulty; domain: P1G8Domain; expected: P1G8Expected };

const req = <T>(value: T): P1G8Field<T> => ({ requirement: "REQUIRED", value });
const opt = <T>(value: T): P1G8Field<T> => ({ requirement: "OPTIONAL", value });
const alt = <T>(alternatives: readonly T[]): P1G8Field<T> => ({ requirement: "ALLOWED_ALTERNATIVE", alternatives });
const unrep = <T>(): P1G8Field<T> => ({ requirement: "UNREPRESENTABLE_IN_F1" });
const claim = (rawText: string, status: MisconceptionStatus): P1G8Claim[] => [{ rawText, status }];
const expected = (acts: IntentAct[], entities: SemanticEntityId[], phenomena: PhenomenonId[], mechanisms: MechanismId[], clarification = false, outcome: ScientificClaimOutcome = "ACCEPT", extra: Partial<P1G8Expected> = {}): P1G8Expected => ({ acts: req(acts), entities: req(entities), phenomena: req(phenomena), mechanisms: req(mechanisms), clarification: req(clarification), misconceptionOutcome: req(outcome), ...extra });

export const p1G8HoldoutV4: readonly P1G8HoldoutCase[] = [
  { id: "h4-lex-001", prompt: "Make a teaching picture of the hereditary molecule with its paired rails still together.", category: "lexicalParaphrase", difficulty: "MEDIUM", domain: "DNA", expected: expected(["show"], ["dna", "duplex", "strand"], [], []) },
  { id: "h4-lex-002", prompt: "I want the ribose-phosphate thread of the RNA message, with the bases kept quiet.", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: expected(["show"], ["rna", "mRNA", "ribose", "phosphate"], ["backboneChemistry"], ["phosphodiesterLinkage"]) },
  { id: "h4-lex-003", prompt: "Could you put the adenine–uracil handshake from an RNA strand under the microscope?", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["rna", "adenine", "uracil"], ["canonicalBasePairing"], ["hydrogenBonding"], false, "ACCEPT", { states: req(["paired"]) }) },
  { id: "h4-lex-004", prompt: "Walk me through the little modification attached to a messenger's five-prime front.", category: "lexicalParaphrase", difficulty: "HARD", domain: "RNA", expected: expected(["explain"], ["mRNA", "cap"], ["rnaProcessing"], ["rnaCapping"], false, "ACCEPT", { states: req(["capped"]) }) },
  { id: "h4-lex-005", prompt: "Show the DNA pairing rule as a close-up of the two matching bases, not a whole cell.", category: "lexicalParaphrase", difficulty: "MEDIUM", domain: "DNA", expected: expected(["show"], ["dna", "base"], ["basePairing"], ["hydrogenBonding"]) },

  { id: "h4-ent-001", prompt: "Which molecule stores the instructions that a daughter cell receives? Give me its two-strand arrangement.", category: "implicitEntity", difficulty: "HARD", domain: "DNA", expected: expected(["inspect", "show"], ["dna", "duplex", "strand"], [], []) },
  { id: "h4-ent-002", prompt: "Point to the sugar feature that makes the RNA message easier to hydrolyze.", category: "implicitEntity", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["rna", "ribose", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h4-ent-003", prompt: "At the copying junction, identify the unwinding motor and the builder following it.", category: "implicitEntity", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["inspect"], ["dna", "replicationFork", "helicase", "polymerase"], ["replication", "strandSeparation"], ["dnaReplication", "strandOpening"]) },
  { id: "h4-ent-004", prompt: "Show the short message that is coming off the instruction molecule while it is being made.", category: "implicitEntity", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show"], ["dna", "rna", "mRNA"], ["transcription"], ["transcriptionElongation"], false, "ACCEPT", { states: req(["nascent"]) }) },
  { id: "h4-ent-005", prompt: "The chain's front end is being trimmed by a terminal enzyme; identify the polymer involved.", category: "implicitEntity", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["rna"], ["exonucleaseDegradation"], ["terminalExonucleaseAction"], false, "ACCEPT", { states: req(["partiallyDegraded"]) }) },

  { id: "h4-amb-001", prompt: "This polymer got shorter—was a middle connection cut, or was an end chewed back?", category: "ambiguityClarification", difficulty: "MEDIUM", domain: "RNA", expected: expected(["explain"], ["rna"], ["cleavage", "exonucleaseDegradation"], ["rnaCleavage", "terminalExonucleaseAction"], true) },
  { id: "h4-amb-002", prompt: "The RNA and DNA are next to each other here; is that a real hybrid or just a layout choice?", category: "ambiguityClarification", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], true, "ACCEPT", { unrepresentable: [{ field: "genericAssociation", reason: "F1-v1 cannot encode generic co-localization separately from hybridization." }] }) },
  { id: "h4-amb-003", prompt: "What opened this DNA region: the copying motor, the transcription machine, or something else?", category: "ambiguityClarification", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "helicase", "rnaPolymerase"], ["strandSeparation", "transcription"], ["strandOpening", "transcriptionElongation"], true) },
  { id: "h4-amb-004", prompt: "Pair the base in front of me; the molecule type was never specified.", category: "ambiguityClarification", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show"], ["base", "dna", "rna"], ["basePairing"], ["hydrogenBonding"], true) },
  { id: "h4-amb-005", prompt: "Is this unnamed catalyst joining a nucleotide, or merely holding the strand in place?", category: "ambiguityClarification", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["nucleotide", "strand"], ["nucleotideAssembly"], ["nucleotideAddition"], true, "ACCEPT", { unrepresentable: [{ field: "enzymeIdentity", reason: "F1-v1 cannot encode an unspecified enzyme identity." }, { field: "genericAssociation", reason: "F1-v1 cannot represent generic holding/co-localization." }] }) },

  { id: "h4-mech-001", prompt: "Contrast an internal RNA backbone break with removal from one terminal end.", category: "mechanismDistinction", difficulty: "HARD", domain: "RNA", expected: expected(["compare", "explain"], ["rna", "phosphodiesterLinkage"], ["cleavage", "exonucleaseDegradation"], ["rnaCleavage", "terminalExonucleaseAction"], true) },
  { id: "h4-mech-002", prompt: "Show fork opening in DNA, explicitly separate from the small transcription bubble.", category: "mechanismDistinction", difficulty: "HARD", domain: "DNA", expected: expected(["show"], ["dna", "replicationFork", "transcriptionBubble"], ["strandSeparation", "replication", "transcription"], ["strandOpening", "dnaReplication", "transcriptionElongation"], true) },
  { id: "h4-mech-003", prompt: "Are these two polymers hybridized, or merely staged together for comparison?", category: "mechanismDistinction", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], true, "ACCEPT", { unrepresentable: [{ field: "genericAssociation", reason: "Generic staging is outside F1-v1." }] }) },
  { id: "h4-mech-004", prompt: "Explain the hydrogen bonds separately from the stacking faces around this DNA pair.", category: "mechanismDistinction", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "base", "stackingFace"], ["basePairing", "helixStabilization"], ["hydrogenBonding", "baseStacking"], false, "ACCEPT", { states: req(["paired"]) }) },
  { id: "h4-mech-005", prompt: "For the RNA transcript, distinguish making a phosphodiester link from breaking that link.", category: "mechanismDistinction", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["compare", "explain"], ["rna", "phosphodiesterLinkage"], ["nucleotideAssembly", "cleavage", "backboneChemistry"], ["nucleotideAddition", "rnaCleavage", "phosphodiesterLinkage"], true) },

  { id: "h4-comp-001", prompt: "Show the replication fork, explain who opens it, and keep the daughter-chain builder in the same account.", category: "compoundAssociation", difficulty: "HARD", domain: "DNA", expected: expected(["show", "explain"], ["dna", "replicationFork", "helicase", "polymerase"], ["replication", "strandSeparation"], ["dnaReplication", "strandOpening"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["replication", "strandSeparation"], preserveMechanisms: ["dnaReplication", "strandOpening"], noInventedSequence: true }) }) },
  { id: "h4-comp-002", prompt: "Place an RNA hairpin beside an RNA-DNA hybrid and tell me what kind of pairing each uses.", category: "compoundAssociation", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["show", "explain"], ["rna", "dna", "duplex"], ["rnaSecondaryStructure", "rnaDnaHybridization"], ["rnaSecondaryFolding", "rnaDnaHybridFormation"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["rnaSecondaryStructure", "rnaDnaHybridization"], preserveMechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation"], noInventedSequence: true }) }) },
  { id: "h4-comp-003", prompt: "Keep the messenger's cap and intron removal as two processing facts, not one generic edit.", category: "compoundAssociation", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["explain"], ["mRNA", "cap", "intron", "exon"], ["rnaProcessing"], ["rnaCapping", "rnaSplicing"], false, "ACCEPT", { states: req(["preMRNA", "matureMRNA", "capped"]), multiIntentInvariants: req({ preserveActs: ["explain"], preservePhenomena: ["rnaProcessing"], preserveMechanisms: ["rnaCapping", "rnaSplicing"], noInventedSequence: true }) }) },
  { id: "h4-comp-004", prompt: "Show G-C pairing, then explain how neighboring bases help stabilize the helix without inventing a timeline.", category: "compoundAssociation", difficulty: "HARD", domain: "DNA", expected: expected(["show", "explain"], ["dna", "guanine", "cytosine", "duplex"], ["canonicalBasePairing", "helixStabilization"], ["hydrogenBonding", "baseStacking"], false, "ACCEPT", { states: req(["paired"]) }) },
  { id: "h4-comp-005", prompt: "The RNA is being copied from DNA while a short hybrid remains; describe both relationships together.", category: "compoundAssociation", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "duplex"], ["transcription", "rnaDnaHybridization"], ["transcriptionElongation", "rnaDnaHybridFormation"], false, "ACCEPT", { states: req(["nascent", "hybridized"]) }) },

  { id: "h4-act-001", prompt: "Why would a messenger carry a cap at its leading terminus?", category: "acts", difficulty: "MEDIUM", domain: "RNA", expected: expected(["explain"], ["mRNA", "cap"], ["rnaProcessing"], ["rnaCapping"]) },
  { id: "h4-act-002", prompt: "Which group should receive my attention on carbon two of this ribose?", category: "acts", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["ribose", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h4-act-003", prompt: "Set the RNA and DNA sugars side by side and tell me why their difference matters.", category: "acts", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["compare", "explain"], ["rna", "dna", "ribose", "deoxyribose"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h4-act-004", prompt: "Point out the phosphate bridge between neighboring nucleotides.", category: "acts", difficulty: "HARD", domain: "DNA", expected: expected(["show", "inspect"], ["phosphate", "nucleotide", "phosphodiesterLinkage"], ["backboneChemistry"], ["phosphodiesterLinkage"]) },
  { id: "h4-act-005", prompt: "Make a before-and-after picture of a transcript shortened from an end.", category: "acts", difficulty: "HARD", domain: "RNA", expected: expected(["show"], ["rna"], ["exonucleaseDegradation"], ["terminalExonucleaseAction"], false, "ACCEPT", { states: req(["partiallyDegraded"]) }) },

  { id: "h4-claim-001", prompt: "DNA contains ribose, right? Check that assumption instead of silently changing it.", category: "claims", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["dna", "ribose"], [], [], false, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("DNA contains ribose", "suspected")) }) },
  { id: "h4-claim-002", prompt: "A review says RNA normally uses thymine; show the claim so I can examine it.", category: "claims", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["show", "explain"], ["rna", "thymine"], [], [], false, "CORRECTION_REQUIRED", { claims: req(claim("RNA normally uses thymine", "validated")) }) },
  { id: "h4-claim-003", prompt: "My lab partner says the DNA strands point the same way—can you check that statement?", category: "claims", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "strand"], ["polarity"], ["antiparallelOrganization"], false, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("the DNA strands point the same way", "suspected")) }) },
  { id: "h4-claim-004", prompt: "Could the RNA two-prime hydroxyl account for its greater chemical fragility than DNA?", category: "claims", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"], false, "ACCEPT", { claims: req(claim("the RNA two-prime hydroxyl could account for greater fragility than DNA", "neutral")) }) },
  { id: "h4-claim-005", prompt: "The source claims uracil is the standard DNA base; present that claim for correction.", category: "claims", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show", "explain"], ["dna", "uracil"], [], [], false, "CORRECTION_REQUIRED", { claims: req(claim("uracil is the standard DNA base", "validated")) }) },

  { id: "h4-dir-001", prompt: "The nuclease begins at the RNA three-prime terminus; mark the biochemical travel direction, not screen placement.", category: "biochemicalDirection", difficulty: "HARD", domain: "RNA", expected: expected(["show"], ["rna"], ["exonucleaseDegradation"], ["terminalExonucleaseAction"], false, "ACCEPT", { states: req(["partiallyDegraded"]), biochemicalDirection: req("threeToFive") }) },
  { id: "h4-dir-002", prompt: "Put the cut on the viewer's left, but do not turn that layout choice into a molecular direction.", category: "biochemicalDirection", difficulty: "ADVERSARIAL", domain: "RNA", expected: expected(["show"], ["rna"], ["cleavage"], ["rnaCleavage"], true, "ACCEPT", { screenDirection: req("screenLeft"), biochemicalDirection: opt("unknown") }) },
  { id: "h4-dir-003", prompt: "The new DNA segment grows toward its five-prime terminus; explain the biochemical direction while ignoring the page.", category: "biochemicalDirection", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "strand"], ["replication"], ["dnaReplication"], false, "ACCEPT", { biochemicalDirection: req("threeToFive") }) },
  { id: "h4-dir-004", prompt: "Label both molecular ends of the duplex; their screen positions are arbitrary.", category: "biochemicalDirection", difficulty: "HARD", domain: "DNA", expected: expected(["show"], ["dna", "duplex", "strand"], ["polarity"], ["antiparallelOrganization"], false, "ACCEPT", { biochemicalDirection: req("strandRelative") }) },
  { id: "h4-dir-005", prompt: "The polymerase advances from the three-prime end toward the five-prime side of the template—show that orientation.", category: "biochemicalDirection", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show"], ["dna", "polymerase", "strand"], ["replication"], ["dnaReplication"], false, "ACCEPT", { biochemicalDirection: req("threeToFive") }) },

  { id: "h4-local-001", prompt: "Zoom in on the RNA phosphodiester connection that is about to be severed.", category: "localChemistry", difficulty: "MEDIUM", domain: "RNA", expected: expected(["show", "inspect"], ["rna", "phosphodiesterLinkage"], ["cleavage", "backboneChemistry"], ["rnaCleavage", "phosphodiesterLinkage"]) },
  { id: "h4-local-002", prompt: "Why does the two-prime substituent on ribose make RNA more prone to backbone hydrolysis than DNA?", category: "localChemistry", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h4-local-003", prompt: "Show the phosphate connection created when a nucleotide joins a growing DNA strand.", category: "localChemistry", difficulty: "HARD", domain: "DNA", expected: expected(["show"], ["nucleotide", "phosphate", "strand"], ["nucleotideAssembly", "backboneChemistry"], ["nucleotideAddition", "phosphodiesterLinkage"], false, "ACCEPT", { states: req(["forming"]) }) },
  { id: "h4-local-004", prompt: "Identify the atom position where the base attaches to ribose, rather than the phosphate side.", category: "localChemistry", difficulty: "HARD", domain: "RNA", expected: expected(["inspect"], ["base", "onePrimeCarbon", "ribose"], ["backboneChemistry"], [], false, "ACCEPT", { mechanisms: opt([]) }) },
  { id: "h4-local-005", prompt: "Show the donor and acceptor groups that make this A-T contact specific.", category: "localChemistry", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show"], ["adenine", "thymine", "hydrogenBondDonor", "hydrogenBondAcceptor"], ["basePairing"], ["hydrogenBonding"]) },

  { id: "h4-cross-001", prompt: "For this transcript, explain why its pentose should be matched against the template's deoxypentose.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["compare", "explain"], ["rna", "mRNA", "dna", "ribose", "deoxyribose"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"]) },
  { id: "h4-cross-002", prompt: "Set an RNA strand alongside DNA and preserve both sugar identities in the hybrid view.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show"], ["rna", "dna", "strand"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], false, "ACCEPT", { states: req(["hybridized"]) }) },
  { id: "h4-cross-003", prompt: "A uracil partner appears in the duplex; inspect whether the surrounding polymer is RNA before explaining the pair.", category: "crossDomain", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["inspect", "explain"], ["uracil", "rna", "dna"], ["basePairing"], ["hydrogenBonding"], true) },
  { id: "h4-cross-004", prompt: "The RNA copy is emerging from DNA; show the local contact and identify the newly made chain.", category: "crossDomain", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["show", "inspect"], ["rna", "dna", "mRNA"], ["transcription"], ["transcriptionElongation"], false, "ACCEPT", { states: req(["nascent"]) }) },
  { id: "h4-cross-005", prompt: "Contrast an intramolecular RNA stem with a mixed DNA/RNA duplex, explaining why their partners differ.", category: "crossDomain", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["compare", "explain"], ["rna", "dna", "duplex"], ["rnaDnaHybridization", "rnaSecondaryStructure"], ["rnaDnaHybridFormation", "rnaSecondaryFolding"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["compare", "explain"], preservePhenomena: ["rnaDnaHybridization", "rnaSecondaryStructure"], preserveMechanisms: ["rnaDnaHybridFormation", "rnaSecondaryFolding"], noInventedSequence: true }) }) },

  { id: "h4-valid-001", prompt: "Does DNA actually carry a ribose ring? Explain the answer without rewriting my premise.", category: "misconceptionValidity", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "ribose"], [], [], false, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("DNA carries a ribose ring", "suspected")) }) },
  { id: "h4-valid-002", prompt: "A textbook note says uracil is DNA's ordinary base; put that statement under scientific review.", category: "misconceptionValidity", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show", "explain"], ["dna", "uracil"], [], [], false, "CORRECTION_REQUIRED", { claims: req(claim("uracil is DNA's ordinary base", "validated")) }) },
  { id: "h4-valid-003", prompt: "Can an RNA-DNA hybrid exist normally, or would that request be impossible science?", category: "misconceptionValidity", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna"], ["rnaDnaHybridization"], ["rnaDnaHybridFormation"], false, "ACCEPT") },
  { id: "h4-valid-004", prompt: "RNA has a two-prime hydroxyl, so it ought to break more readily than DNA—does that inference hold?", category: "misconceptionValidity", difficulty: "HARD", domain: "CROSS_DOMAIN", expected: expected(["explain"], ["rna", "dna", "riboseTwoPrimeHydroxyl"], ["chemicalStabilityComparison"], ["riboseHydroxylSusceptibility"], false, "ACCEPT", { claims: req(claim("RNA has a two-prime hydroxyl and therefore breaks more readily than DNA", "suspected")) }) },
  { id: "h4-valid-005", prompt: "Someone told me every polymerase opens DNA; check that claim against replication and transcription roles.", category: "misconceptionValidity", difficulty: "HARD", domain: "DNA", expected: expected(["explain"], ["dna", "polymerase"], ["replication", "transcription"], ["dnaReplication", "transcriptionElongation"], true, "CLAIM_REQUIRES_GROUNDING", { claims: req(claim("every polymerase opens DNA", "suspected")) }) },

  { id: "h4-multi-001", prompt: "At the copying fork, depict the unwinding motor, then explain the opposite 5′/3′ labels on the newly made rails.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "DNA", expected: expected(["show", "explain"], ["dna", "replicationFork", "strand", "helicase"], ["strandSeparation", "replication", "polarity"], ["strandOpening", "dnaReplication", "antiparallelOrganization"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["strandSeparation", "replication", "polarity"], preserveMechanisms: ["strandOpening", "dnaReplication", "antiparallelOrganization"], noInventedSequence: true }) }) },
  { id: "h4-multi-002", prompt: "Contrast an RNA fold with an RNA-DNA hybrid, then explain why their partners are not interchangeable.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["compare", "explain"], ["rna", "dna", "duplex"], ["rnaSecondaryStructure", "rnaDnaHybridization"], ["rnaSecondaryFolding", "rnaDnaHybridFormation"], false, "ACCEPT", { multiIntentInvariants: req({ preserveActs: ["compare", "explain"], preservePhenomena: ["rnaSecondaryStructure", "rnaDnaHybridization"], preserveMechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation"], noInventedSequence: true }) }) },
  { id: "h4-multi-003", prompt: "Show the capped pre-message and its processed counterpart, but do not invent an order for the edits.", category: "multiIntent", difficulty: "HARD", domain: "RNA", expected: expected(["show", "compare"], ["mRNA", "cap", "intron", "exon"], ["rnaProcessing"], ["rnaCapping", "rnaSplicing"], false, "ACCEPT", { states: req(["preMRNA", "matureMRNA", "capped"]), multiIntentInvariants: req({ preserveActs: ["show", "compare"], preservePhenomena: ["rnaProcessing"], preserveMechanisms: ["rnaCapping", "rnaSplicing"], noInventedSequence: true }) }) },
  { id: "h4-multi-004", prompt: "Show the nascent RNA leaving its DNA template, explain the synthesis terminus, and keep the local hybrid separate from the flanking duplex.", category: "multiIntent", difficulty: "ADVERSARIAL", domain: "CROSS_DOMAIN", expected: expected(["show", "explain"], ["rna", "dna", "mRNA", "duplex"], ["transcription", "rnaDnaHybridization"], ["transcriptionElongation", "rnaDnaHybridFormation"], false, "ACCEPT", { states: req(["nascent", "hybridized"]), biochemicalDirection: req("fiveToThree"), multiIntentInvariants: req({ preserveActs: ["show", "explain"], preservePhenomena: ["transcription", "rnaDnaHybridization"], preserveMechanisms: ["transcriptionElongation", "rnaDnaHybridFormation"], noInventedSequence: true }) }) },
  { id: "h4-multi-005", prompt: "Compare an intact RNA chain with its end-shortened form and explain which phosphodiester context disappeared.", category: "multiIntent", difficulty: "HARD", domain: "RNA", expected: expected(["compare", "explain"], ["rna", "phosphodiesterLinkage"], ["exonucleaseDegradation", "backboneChemistry"], ["terminalExonucleaseAction", "phosphodiesterLinkage"], false, "ACCEPT", { states: req(["intact", "partiallyDegraded"]), multiIntentInvariants: req({ preserveActs: ["compare", "explain"], preservePhenomena: ["exonucleaseDegradation", "backboneChemistry"], preserveMechanisms: ["terminalExonucleaseAction", "phosphodiesterLinkage"], noInventedSequence: true }) }) },
] as const;

export const p1G8HoldoutV4CaseIds = p1G8HoldoutV4.map(({ id }) => id);
