import type { IntentAct, MechanismId, PhenomenonId, SemanticEntityId } from "./foundation-semantic-vocabulary.ts";
import type { P1Domain, P1Difficulty } from "./p1-adversarial-corpus.ts";

export type K5AExpectation = { entities?: readonly SemanticEntityId[]; phenomenon?: PhenomenonId; mechanism?: MechanismId; acts?: readonly IntentAct[]; clarification?: boolean; biochemicalDirection?: string; screenDirection?: string };
export type K5ACase = { id: string; prompt: string; category: string; domain: P1Domain; difficulty: P1Difficulty; expected: K5AExpectation };
const make = (category: string, domain: P1Domain, expected: K5AExpectation, prompts: readonly string[]): K5ACase[] => prompts.map((prompt, i) => ({ id: `k5a-${category}-${String(i + 1).padStart(2, "0")}`, prompt, category, domain, difficulty: i < 2 ? "MEDIUM" : i < 8 ? "HARD" : "ADVERSARIAL", expected }));

export const p1K5AFreshDevelopmentCorpus: readonly K5ACase[] = [
  ...make("implicit", "DNA", { entities: ["dna", "duplex"], acts: ["show"] }, [
    "Sketch the paired genetic material that stores the instructions.", "Show the hereditary molecule with both of its matching sides.", "Can I see the information-carrying double strand?", "Give me the molecule cells copy before division.", "Put the two complementary DNA sides in view.", "What does the genetic instruction molecule look like when paired?", "Display the long paired archive, not a protein.", "I mean the double-stranded carrier of genes.", "Show the molecule that gets read into messages.", "Let me inspect the paired genetic polymer."]),
  ...make("pronoun", "RNA", { entities: ["rna", "mRNA"], phenomenon: "rnaProcessing", acts: ["show"] }, [
    "Show the message after its extra stretches are removed.", "What happens to it when the noncoding pieces are taken out?", "Put the finished transcript beside the earlier version.", "Can you display the RNA after editing, with its order intact?", "I want the processed message, not the first draft.", "Show that transcript once its intervening regions are gone.", "How does the molecule look after those pieces leave?", "Display the mature version of the cellular message.", "Compare the draft with what survives processing.", "Show it after splicing, keeping the exons visible."]),
  ...make("ambiguity", "RNA", { entities: ["rna"], phenomenon: "cleavage", acts: ["show"], clarification: true }, [
    "Show the RNA after it gets cut somehow.", "What does the chain look like once an enzyme acts on it?", "Can you picture the shortened message?", "Display the result of breaking this transcript, but the route is unclear.", "Show what remains after processing the strand.", "I need the product after the RNA is reduced.", "Make the change to the polymer visible; I have not named the mechanism.", "Show the chain after its end or middle has been removed.", "Can the altered transcript be pictured without guessing the enzyme?", "Display the broken RNA and keep competing mechanisms visible."]),
  ...make("mechanism", "DNA", { entities: ["dna", "replicationFork", "helicase", "polymerase"], phenomenon: "replication", mechanism: "dnaReplication", acts: ["explain", "show"] }, [
    "Show how the copying machine advances at the fork.", "Explain what the unwinding motor and builder do together.", "I want the replication junction and the new daughter chain.", "Picture the template being read while its partner opens.", "How does DNA duplication proceed from this fork?", "Display the copying apparatus, including its two key enzymes.", "Explain the handoff between opening and nucleotide addition.", "Show the growing daughter strand on the template.", "Can you walk through the fork without reducing it to a generic line?", "Make the replication actors and their substrate visible."]),
  ...make("compound", "CROSS_DOMAIN", { entities: ["dna", "rna", "transcriptionBubble"], phenomenon: "transcription", mechanism: "transcriptionElongation", acts: ["show", "explain"] }, [
    "Show the RNA copy leaving DNA and explain the local opening.", "How does a short transcript emerge while the DNA is used?", "Picture the template with the new RNA coming out of the complex.", "Explain the relationship between the opened duplex and its transcript.", "I need DNA and the newly made RNA in one local view.", "Show where synthesis happens and which strand is the product.", "Can the transcription site and exiting message be clear?", "Display the emerging transcript beside its DNA context.", "Explain how the polymerase makes the RNA copy.", "Show the local hybrid and the direction of transcript emergence."]),
  ...make("claims", "CROSS_DOMAIN", { entities: ["dna", "rna", "ribose", "deoxyribose"], phenomenon: "chemicalStabilityComparison", mechanism: "riboseHydroxylSusceptibility", acts: ["explain", "compare"] }, [
    "Is the extra hydroxyl why RNA is less sturdy than DNA?", "Someone said DNA and RNA use the same sugar; can you check that?", "Explain the stability difference through their sugar structures.", "Compare the two polymers and address the claim about ribose.", "Does the 2-prime group make the RNA backbone more vulnerable?", "I am unsure whether deoxyribose really lacks that hydroxyl.", "Why would one nucleic acid hydrolyze more readily than the other?", "Contrast the matched sugars without silently correcting my question.", "Can you inspect the claim that RNA is chemically identical to DNA?", "Explain the molecular reason for their different stability."]),
  ...make("direction", "RNA", { entities: ["rna", "fivePrimeCarbon"], phenomenon: "exonucleaseDegradation", mechanism: "terminalExonucleaseAction", acts: ["show"], biochemicalDirection: "fiveToThree" }, [
    "Show an enzyme chewing the message from its five-prime end.", "Picture shortening that begins at the 5-prime terminus.", "Which way does an exonuclease remove residues from this transcript?", "Display the exposed end after 5-prime-to-3-prime digestion.", "The degradation starts at the marked five-prime tip; show the result.", "Show terminal loss toward the three-prime side.", "Explain the chemical direction of end-directed RNA decay.", "Can the new terminus be visible after removal from the 5-prime end?", "Make clear that the page layout is not the molecular direction.", "Show the transcript getting shorter from its 5-prime end."]),
  ...make("chemistry", "RNA", { entities: ["rna", "ribose", "phosphate", "riboseTwoPrimeHydroxyl"], phenomenon: "backboneChemistry", mechanism: "phosphodiesterLinkage", acts: ["show"] }, [
    "Show the sugar-phosphate repeating chemistry in an RNA strand.", "Which atoms connect neighboring riboses in the backbone?", "Give me a close view of the phosphate bridge between sugars.", "Display one nucleotide with its sugar, base, and phosphate attached.", "Show the hydroxyl unique to the RNA sugar.", "Can I inspect the 1-prime through 5-prime positions on ribose?", "Picture the phosphate bonded to the next sugar rather than floating.", "Show the local covalent chain and keep the bases secondary.", "What does an RNA nucleotide look like at molecular scale?", "Display uracil attached to ribose in an RNA nucleotide."]),
  ...make("cross", "CROSS_DOMAIN", { entities: ["rna", "dna", "duplex"], phenomenon: "rnaDnaHybridization", mechanism: "rnaDnaHybridFormation", acts: ["show"] }, [
    "Show an RNA strand paired with a DNA strand.", "How does a mixed nucleic-acid duplex look?", "Display the hybrid rather than two unrelated polymers.", "Put the RNA-DNA contact in a compact molecular view.", "Can I see the two different backbones in one duplex?", "Show where an RNA transcript remains paired to its DNA template.", "Picture a hybrid helix and label which side is RNA.", "What distinguishes a mixed duplex from a DNA homoduplex?", "Display the local pairing between the two polymers.", "Show the RNA-DNA hybrid without turning it into an RNA hairpin."]),
  ...make("multi", "CROSS_DOMAIN", { entities: ["dna", "rna", "duplex"], phenomenon: "basePairing", mechanism: "hydrogenBonding", acts: ["compare", "explain"] }, [
    "Compare an RNA hairpin with a DNA duplex and explain their contacts.", "Show the two pairing contexts and tell me what differs chemically.", "I need a comparison of mixed and same-polymer base pairing.", "Explain why an RNA stem is not the same object as an RNA-DNA hybrid.", "Put a canonical pair beside a wobble and identify the interaction type.", "Compare the hydrogen bonds in DNA and RNA examples.", "Show both structures, then explain which polymer each base belongs to.", "How do the matching rules change between these two duplexes?", "Display the paired regions and keep their identities separate.", "Explain the contacts while comparing the two nucleic-acid scenes."]),
  ...make("acts", "DNA", { entities: ["dna", "strand"], phenomenon: "polarity", mechanism: "antiparallelOrganization", acts: ["inspect"] }, [
    "Which way do the two DNA strands run?", "Identify the end labels on this duplex.", "I only want to inspect the strand directions.", "What are the 5-prime and 3-prime ends here?", "Point out the orientation of each DNA side.", "Tell me which strand faces which way.", "Can you identify the polarity without explaining the whole molecule?", "I need the direction labels located on the duplex.", "Inspect the two strands and name their relative orientation.", "What does the strand direction look like in this drawing?"]),
  ...make("validity", "DNA", { entities: ["dna", "uracil"], phenomenon: "basePairing", acts: ["explain"] }, [
    "DNA uses uracil instead of thymine, right? Explain the claim.", "Please check whether uracil belongs in ordinary DNA.", "Someone insists that a DNA pair contains U; how should I understand that?", "Is this a normal DNA base or a mix-up with RNA?", "Explain the statement that DNA pairs through uracil.", "I heard U is the standard DNA partner; is that scientifically sound?", "Can you inspect my claim about uracil in DNA without rewriting it?", "Why might a DNA diagram showing U be misleading?", "Tell me whether this supposed U-containing DNA pair is valid.", "Explain the difference between an RNA U pair and a claimed DNA U pair."]),
];

export const p1K5AFreshDevelopmentMetadata = { version: "p1-k5a-dev-v1", count: p1K5AFreshDevelopmentCorpus.length, source: "independently authored semantic-principle fixtures", holdout: false } as const;
