/** P1-K3B: fresh development cases for generalized semantic repair. */
import type { IntentAct, MechanismId, PhenomenonId, SemanticEntityId, BiologicalStateId, BiochemicalDirection, ScreenDirection } from "./foundation-semantic-vocabulary.ts";
import type { ScientificClaimOutcome } from "./semantic-misconception-policy.ts";

export type K3BCase = {
  id: string; prompt: string; category: "entity" | "compound" | "ambiguity" | "acts" | "claims" | "direction" | "crossDomain" | "localChemistry";
  expected: { acts: readonly IntentAct[]; entities?: readonly SemanticEntityId[]; phenomena?: readonly PhenomenonId[]; mechanisms?: readonly MechanismId[]; states?: readonly BiologicalStateId[]; biochemicalDirection?: BiochemicalDirection; screenDirection?: ScreenDirection; clarification?: boolean; outcome?: ScientificClaimOutcome; claims?: readonly { text: string; status: "neutral" | "suspected" | "validated" }[]; preserve?: { acts: readonly IntentAct[]; mechanisms: readonly MechanismId[] } };
};

export const p1K3bGeneralizationCorpus: readonly K3BCase[] = [
  { id: "k3b-entity-001", prompt: "Draw the molecule that stores inherited instructions, with its paired rails.", category: "entity", expected: { acts: ["show"], entities: ["dna", "duplex", "strand"], states: ["paired"] } },
  { id: "k3b-entity-002", prompt: "Show the RNA message product and its sugar-phosphate chain.", category: "entity", expected: { acts: ["show"], entities: ["rna", "mRNA", "phosphate"], phenomena: ["backboneChemistry"], mechanisms: ["phosphodiesterLinkage"] } },
  { id: "k3b-entity-003", prompt: "Point to the sugar ring in an RNA nucleotide and its hydroxyl at position two.", category: "entity", expected: { acts: ["show", "inspect"], entities: ["rna", "ribose", "riboseTwoPrimeHydroxyl"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"] } },
  { id: "k3b-entity-004", prompt: "Which hereditary material is shown as a double helix?", category: "entity", expected: { acts: ["inspect"], entities: ["dna", "duplex"] } },

  { id: "k3b-compound-001", prompt: "At the copying fork, show the unwinding helicase and the polymerase extending the new strand.", category: "compound", expected: { acts: ["show"], entities: ["dna", "replicationFork", "helicase", "polymerase"], phenomena: ["replication", "strandSeparation"], mechanisms: ["dnaReplication", "strandOpening"], preserve: { acts: ["show"], mechanisms: ["dnaReplication", "strandOpening"] } } },
  { id: "k3b-compound-002", prompt: "Show an RNA stem-loop next to an RNA-DNA contact and compare their pairing behavior.", category: "compound", expected: { acts: ["show", "compare"], entities: ["rna", "dna", "duplex"], phenomena: ["rnaSecondaryStructure", "rnaDnaHybridization"], mechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation"], preserve: { acts: ["show", "compare"], mechanisms: ["rnaSecondaryFolding", "rnaDnaHybridFormation"] } } },
  { id: "k3b-compound-003", prompt: "Show the cap and splicing of this messenger message, keeping both processing operations visible.", category: "compound", expected: { acts: ["show"], entities: ["mRNA", "cap", "intron", "exon"], phenomena: ["rnaProcessing"], mechanisms: ["rnaCapping", "rnaSplicing"], preserve: { acts: ["show"], mechanisms: ["rnaCapping", "rnaSplicing"] } } },
  { id: "k3b-compound-004", prompt: "Display the base contacts and explain the stacking that organizes the duplex.", category: "compound", expected: { acts: ["show", "explain"], entities: ["duplex"], phenomena: ["canonicalBasePairing", "helixStabilization"], mechanisms: ["hydrogenBonding", "baseStacking"], preserve: { acts: ["show", "explain"], mechanisms: ["hydrogenBonding", "baseStacking"] } } },

  { id: "k3b-ambiguity-001", prompt: "What happened to this polymer: was it cut internally or nibbled from an end?", category: "ambiguity", expected: { acts: ["explain"], entities: ["strand"], clarification: true, outcome: "ACCEPT" } },
  { id: "k3b-ambiguity-002", prompt: "Do you mean a hybrid duplex or an ordinary RNA-DNA association here?", category: "ambiguity", expected: { acts: ["explain"], entities: ["rna", "dna"], clarification: true, outcome: "ACCEPT" } },
  { id: "k3b-ambiguity-003", prompt: "Which machine opens this double helix, the fork motor or transcription polymerase?", category: "ambiguity", expected: { acts: ["inspect"], entities: ["dna", "duplex", "helicase", "rnaPolymerase"], clarification: true, outcome: "ACCEPT" } },
  { id: "k3b-ambiguity-004", prompt: "Pair this base—DNA or RNA, I have not said.", category: "ambiguity", expected: { acts: ["show"], entities: ["dna", "rna"], clarification: true, outcome: "ACCEPT" } },

  { id: "k3b-acts-001", prompt: "What is the transcript doing at its capped end?", category: "acts", expected: { acts: ["explain"], entities: ["rna", "mRNA", "cap"], phenomena: ["rnaProcessing"], mechanisms: ["rnaCapping"] } },
  { id: "k3b-acts-002", prompt: "Which group should I inspect at the two-prime position?", category: "acts", expected: { acts: ["inspect"], entities: ["riboseTwoPrimeHydroxyl"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"] } },
  { id: "k3b-acts-003", prompt: "Contrast ribose in RNA with deoxyribose in DNA and explain the chemical difference.", category: "acts", expected: { acts: ["compare", "explain"], entities: ["ribose", "deoxyribose", "rna", "dna"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"] } },
  { id: "k3b-acts-004", prompt: "How does the phosphodiester phosphate bridge join neighboring nucleotides?", category: "acts", expected: { acts: ["explain"], entities: ["phosphate", "phosphodiesterLinkage", "nucleotide"], phenomena: ["backboneChemistry"], mechanisms: ["phosphodiesterLinkage"] } },

  { id: "k3b-claims-001", prompt: "DNA contains ribose, doesn't it? Check that claim.", category: "claims", expected: { acts: ["explain"], entities: ["dna", "ribose"], claims: [{ text: "DNA contains ribose, doesn't it? Check that claim", status: "suspected" }], outcome: "CLAIM_REQUIRES_GROUNDING" } },
  { id: "k3b-claims-002", prompt: "A published report says RNA uses thymine.", category: "claims", expected: { acts: ["show"], entities: ["rna", "thymine"], claims: [{ text: "RNA uses thymine", status: "validated" }], outcome: "CORRECTION_REQUIRED" } },
  { id: "k3b-claims-003", prompt: "A student claims the two strands run in the same direction.", category: "claims", expected: { acts: ["show"], entities: ["strand"], claims: [{ text: "the two strands run in the same direction", status: "suspected" }], outcome: "CLAIM_REQUIRES_GROUNDING" } },
  { id: "k3b-claims-004", prompt: "Could RNA be less stable because it carries a two-prime hydroxyl?", category: "claims", expected: { acts: ["explain"], entities: ["rna", "riboseTwoPrimeHydroxyl"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"], outcome: "ACCEPT" } },

  { id: "k3b-direction-001", prompt: "The exonuclease removes material from the RNA message beginning at the three-prime terminus.", category: "direction", expected: { acts: ["show"], entities: ["rna"], phenomena: ["exonucleaseDegradation"], mechanisms: ["terminalExonucleaseAction"], biochemicalDirection: "threeToFive" } },
  { id: "k3b-direction-002", prompt: "Shorten the transcript at the five-prime end; the drawing happens to run leftward.", category: "direction", expected: { acts: ["show"], entities: ["rna"], phenomena: ["exonucleaseDegradation"], mechanisms: ["terminalExonucleaseAction"], biochemicalDirection: "fiveToThree", screenDirection: "screenLeft" } },
  { id: "k3b-direction-003", prompt: "Mark opposite five-prime and three-prime ends on the paired DNA rails.", category: "direction", expected: { acts: ["show"], entities: ["dna", "duplex", "strand"], phenomena: ["polarity"], mechanisms: ["antiparallelOrganization"], biochemicalDirection: "strandRelative" } },
  { id: "k3b-direction-004", prompt: "Show the RNA being chewed from its three-prime end, not from the page edge.", category: "direction", expected: { acts: ["show"], entities: ["rna"], phenomena: ["exonucleaseDegradation"], mechanisms: ["terminalExonucleaseAction"], biochemicalDirection: "threeToFive" } },

  { id: "k3b-cross-001", prompt: "Compare the ribose in RNA with the deoxyribose in DNA at the same local position.", category: "crossDomain", expected: { acts: ["compare"], entities: ["rna", "dna", "ribose", "deoxyribose"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"] } },
  { id: "k3b-cross-002", prompt: "Show an RNA strand paired directly with a DNA strand.", category: "crossDomain", expected: { acts: ["show"], entities: ["rna", "dna", "strand"], phenomena: ["rnaDnaHybridization"], mechanisms: ["rnaDnaHybridFormation"], states: ["hybridized"] } },
  { id: "k3b-cross-003", prompt: "Identify whether this U-containing partner belongs to RNA or DNA.", category: "crossDomain", expected: { acts: ["inspect"], entities: ["uracil", "rna", "dna"], clarification: true, outcome: "ACCEPT" } },
  { id: "k3b-cross-004", prompt: "An RNA copy leaves the DNA template; show the local transcription contact.", category: "crossDomain", expected: { acts: ["show"], entities: ["rna", "dna"], phenomena: ["transcription"], mechanisms: ["transcriptionElongation"], states: ["nascent"] } },

  { id: "k3b-local-001", prompt: "Show the phosphodiester break made during RNA cleavage.", category: "localChemistry", expected: { acts: ["show"], entities: ["rna", "phosphodiesterLinkage"], phenomena: ["cleavage", "backboneChemistry"], mechanisms: ["rnaCleavage", "phosphodiesterLinkage"] } },
  { id: "k3b-local-002", prompt: "Explain why the two-prime hydroxyl makes the RNA backbone more vulnerable than DNA.", category: "localChemistry", expected: { acts: ["explain"], entities: ["rna", "dna", "riboseTwoPrimeHydroxyl"], phenomena: ["chemicalStabilityComparison"], mechanisms: ["riboseHydroxylSusceptibility"] } },
  { id: "k3b-local-003", prompt: "Show one nucleotide joining the next through its phosphodiester phosphate bridge.", category: "localChemistry", expected: { acts: ["show"], entities: ["nucleotide", "phosphate", "phosphodiesterLinkage"], phenomena: ["nucleotideAssembly", "backboneChemistry"], mechanisms: ["nucleotideAddition", "phosphodiesterLinkage"] } },
  { id: "k3b-local-004", prompt: "Point out the base attached to the one-prime carbon of ribose in the nucleotide backbone.", category: "localChemistry", expected: { acts: ["inspect"], entities: ["base", "onePrimeCarbon", "ribose"], phenomena: ["backboneChemistry"] } },
] as const;
