/** P2-E: relation/topology authority. P2-G remains the sole chemistry authority. */
import type { ScientificActorId, ScientificActorScene } from "./scientific-actor.ts";
import { validateScientificTopologyModel, type ScientificInteraction, type ScientificTopologyModel, type TopologyChange, type ScientificContinuity, type ScientificConstraint } from "./scientific-topology.ts";
import type { GroundingSubstrateResult } from "./p2-bcdf-grounding-seam.ts";
import { isAuthenticatedLocalChemistryResult, type GroundedLocalChemistryResult, type LocalChemicalAssertion } from "./p2-local-chemistry-grounding.ts";

export const interactionEvidenceKinds = ["DEPOSITED_SOURCE", "CHEMICAL_RULE", "COMPUTED", "CONSTRAINED_SCHEMATIC", "SCHEMATIC"] as const;
export type InteractionEvidenceKind = (typeof interactionEvidenceKinds)[number];
export type InteractionGroundingFailure = "INTERACTION_UNRESOLVED" | "CHEMICAL_FACT_MISSING" | "CHEMISTRY_INCOMPATIBLE" | "TOPOLOGY_INCONSISTENT" | "SELECTOR_UNRESOLVED" | "EVIDENCE_INSUFFICIENT" | "TERMINUS_UNGROUNDED" | "LINK_MISMATCH" | "FIDELITY_EVIDENCE_MISMATCH";
type ChemicalParticipant = { actorId: ScientificActorId; chemicalFactId: string; anchorId?: string };
type ChemicalLinkParticipant = { actorId: ScientificActorId; selectorBindingId: string; residueKey: string; atomKeys: readonly string[]; anchorId?: string };
export type GroundedInteractionRequest =
  | { interactionId: string; kind: "basePairing" | "hydrogenBond" | "baseStacking" | "hybridization"; participants: [ChemicalParticipant, ChemicalParticipant]; evidence: InteractionEvidenceKind; state?: "present" | "forming" | "breaking" | "absent" }
  | { interactionId: string; kind: "phosphodiesterLinkage" | "covalentBond" | "polymerContinuity"; participants: [ChemicalLinkParticipant, ChemicalLinkParticipant]; chemicalFactId: string; evidence: InteractionEvidenceKind; state?: "present" | "forming" | "breaking" | "absent" };
export type GroundedContinuityRequest = { continuityId: string; strandActorId: ScientificActorId; orderedActorIds: ScientificActorId[]; state: "intact" | "cleaved" | "partial"; chemicalFactId?: string };
export type GroundedTopologyChangeRequest = { changeId: string; kind: TopologyChange["kind"]; actorIds: ScientificActorId[]; interactionIds?: string[]; biochemicalDirection?: TopologyChange["biochemicalDirection"]; terminusFactIds?: readonly [string, string]; chemicalFactId?: string };
export type InteractionTopologyGroundingInput = { grounding: GroundingSubstrateResult; actorScene: ScientificActorScene; chemistry: GroundedLocalChemistryResult; interactions: GroundedInteractionRequest[]; continuities?: GroundedContinuityRequest[]; changes?: GroundedTopologyChangeRequest[]; constraints?: ScientificConstraint[] };
export type InteractionEvidenceTrace = { outputKind: "interaction" | "continuity" | "change" | "constraint"; evidence: InteractionEvidenceKind; provenanceSourceId: string; structureId: string; selectorBindingIds: readonly string[]; chemicalFactIds: readonly string[]; linkAssertionIds: readonly string[]; fidelity: string };
export type InteractionTopologyGroundingResult = { ok: true; model: ScientificTopologyModel; evidence: Readonly<Record<string, InteractionEvidenceTrace>>; participantIdentity: Readonly<Record<string, readonly string[]>> } | { ok: false; code: InteractionGroundingFailure; reasons: readonly string[] };

/** Validates the sidecar without changing frozen F2 topology records. */
export function validateInteractionTopologyEvidence(result: Extract<InteractionTopologyGroundingResult, { ok: true }>, grounding: Extract<GroundingSubstrateResult, { outcome: "RESOLVED" }>, chemistry: GroundedLocalChemistryResult): { valid: true; issues: [] } | { valid: false; issues: readonly string[] } {
  const issues: string[] = []; const records = new Map<string, InteractionEvidenceTrace["outputKind"]>();
  for (const item of result.model.topology.interactions) records.set(item.interactionId, "interaction");
  for (const item of result.model.topology.continuities ?? []) records.set(item.continuityId, "continuity");
  for (const item of result.model.topology.changes ?? []) records.set(item.changeId, "change");
  for (const item of result.model.constraints ?? []) records.set(item.constraintId, "constraint");
  for (const [id, kind] of records) { const trace = result.evidence[id]; if (!trace) issues.push(`${id}: missing trace`); else if (trace.outputKind !== kind) issues.push(`${id}: wrong output kind`); }
  for (const [id, trace] of Object.entries(result.evidence)) { if (records.get(id) !== trace.outputKind) issues.push(`${id}: dangling or wrong-kind trace`); if (trace.provenanceSourceId !== String(grounding.provenance.sourceId) || trace.structureId !== grounding.structureContext?.structureId) issues.push(`${id}: wrong source or structure`); if (trace.selectorBindingIds.some((binding) => !chemistry.selectorBindingIds.includes(binding))) issues.push(`${id}: dangling selector binding`); if (trace.chemicalFactIds.some((fact) => !chemistry.assertions.some((assertion) => assertion.assertionId === fact))) issues.push(`${id}: dangling chemical fact`); if (trace.linkAssertionIds.some((link) => !chemistry.linkAssertions.some((assertion) => assertion.linkAssertionId === link))) issues.push(`${id}: dangling link assertion`); if (!evidenceMatchesFidelity(trace.evidence, trace.fidelity)) issues.push(`${id}: invalid evidence/fidelity pair`); }
  return issues.length ? { valid: false, issues } : { valid: true, issues: [] };
}

const fail = (code: InteractionGroundingFailure, reasons: string[]): InteractionTopologyGroundingResult => ({ ok: false, code, reasons });
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const exact = (value: unknown, keys: readonly string[]) => isRecord(value) && Object.keys(value).every((key) => keys.includes(key));
const evidenceMatchesFidelity = (evidence: InteractionEvidenceKind, fidelity: string) => (evidence !== "DEPOSITED_SOURCE" || fidelity === "E0_DEPOSITED") && (evidence !== "COMPUTED" || fidelity === "C0_COMPUTED") && (evidence !== "CONSTRAINED_SCHEMATIC" || fidelity === "S1_CONSTRAINED") && (evidence !== "SCHEMATIC" || fidelity === "S2_SCHEMATIC");
const canonical = (a: LocalChemicalAssertion, b: LocalChemicalAssertion) => (a.nucleicChemistry === "DNA" && b.nucleicChemistry === "DNA" && ((a.base === "A" && b.base === "T") || (a.base === "T" && b.base === "A") || (a.base === "G" && b.base === "C") || (a.base === "C" && b.base === "G"))) || (a.nucleicChemistry === "RNA" && b.nucleicChemistry === "RNA" && ((a.base === "A" && b.base === "U") || (a.base === "U" && b.base === "A") || (a.base === "G" && b.base === "C") || (a.base === "C" && b.base === "G")));

/** Converts P2-G-backed relation requests into frozen F2 topology, with an auditable sidecar. */
export function groundScientificInteractions(input: InteractionTopologyGroundingInput): InteractionTopologyGroundingResult {
  if (!exact(input, ["grounding", "actorScene", "chemistry", "interactions", "continuities", "changes", "constraints"]) || !Array.isArray(input.interactions)) return fail("TOPOLOGY_INCONSISTENT", ["malformed P2-E input or unsupported field"]);
  if (input.grounding.outcome !== "RESOLVED" || !input.grounding.selectors?.valid || !input.grounding.structureContext || !input.grounding.fidelity.accepted) return fail("EVIDENCE_INSUFFICIENT", ["validated BCDF provenance, structure context, selectors, and fidelity are required"]);
  const provenanceSourceId = String(input.grounding.provenance.sourceId);
  const resolvedStructureId = input.grounding.structureContext.structureId; const resolvedFidelity = input.grounding.fidelity.decision.fidelity;
  if (!isAuthenticatedLocalChemistryResult(input.chemistry) || input.chemistry.schemaVersion !== "2" || input.chemistry.substrateSourceId !== provenanceSourceId || input.chemistry.structureId !== input.grounding.structureContext.structureId) return fail("CHEMICAL_FACT_MISSING", ["P2-E requires the authenticated P2-G result for this exact BCDF substrate"]);
  const actors = new Set(input.actorScene.actors.map((actor) => actor.actorId)); const actorRecords = new Map(input.actorScene.actors.map((actor) => [actor.actorId, actor])); const facts = new Map(input.chemistry.assertions.map((fact) => [fact.assertionId, fact]));
  if (facts.size !== input.chemistry.assertions.length || input.chemistry.assertions.some((fact) => !exact(fact, ["assertionId", "bindingId", "actorId", "target", "componentId", "nucleicChemistry", "base", "sugar", "residueKeys", "atomKeys", "evidence"]) || !exact(fact.evidence, ["sourceId", "componentEvidence", "confidence", "limitations"]) || fact.evidence.sourceId !== provenanceSourceId || !input.chemistry.selectorBindingIds.includes(fact.bindingId))) return fail("CHEMICAL_FACT_MISSING", ["authenticated P2-G result contains an invalid chemical fact"]);
  const interactions: ScientificInteraction[] = []; const evidence: Record<string, InteractionEvidenceTrace> = {}; const participantIdentity: Record<string, readonly string[]> = {}; const ids = new Set<string>();
  for (const request of input.interactions) {
    if (!isRecord(request) || !request.interactionId || ids.has(request.interactionId) || !interactionEvidenceKinds.includes(request.evidence)) return fail("TOPOLOGY_INCONSISTENT", ["interaction ID/evidence is malformed or duplicated"]);
    const linkRequest = "chemicalFactId" in request;
    if (!exact(request, linkRequest ? ["interactionId", "kind", "participants", "chemicalFactId", "evidence", "state"] : ["interactionId", "kind", "participants", "evidence", "state"]) || !Array.isArray(request.participants) || request.participants.length !== 2 || request.participants.some((participant) => !exact(participant, linkRequest ? ["actorId", "selectorBindingId", "residueKey", "atomKeys", "anchorId"] : ["actorId", "chemicalFactId", "anchorId"]))) return fail("TOPOLOGY_INCONSISTENT", ["interaction request contains malformed or unsupported fields"]);
    if (request.evidence === "DEPOSITED_SOURCE" && !(input.grounding.provenance.__p2BValidated === true && input.grounding.provenance.sourceType === "depositedStructure" && input.grounding.fidelity.decision.fidelity === "E0_DEPOSITED")) return fail("FIDELITY_EVIDENCE_MISMATCH", [`${request.interactionId} lacks deposited provenance/fidelity`]);
    if (request.evidence === "COMPUTED" && !(input.grounding.provenance.sourceType === "computedModel" && input.grounding.fidelity.decision.fidelity === "C0_COMPUTED")) return fail("FIDELITY_EVIDENCE_MISMATCH", [`${request.interactionId} computed evidence contradicts provenance/fidelity`]);
    if (request.evidence === "SCHEMATIC" && input.grounding.fidelity.decision.fidelity !== "S2_SCHEMATIC") return fail("FIDELITY_EVIDENCE_MISMATCH", [`${request.interactionId} schematic evidence contradicts fidelity`]);
    if (request.evidence === "CONSTRAINED_SCHEMATIC" && input.grounding.fidelity.decision.fidelity !== "S1_CONSTRAINED") return fail("FIDELITY_EVIDENCE_MISMATCH", [`${request.interactionId} constrained-schematic evidence contradicts fidelity`]);
    ids.add(request.interactionId); let factIds: string[] = [];
    if (linkRequest) {
      const link = input.chemistry.linkAssertions.find((item) => item.linkAssertionId === request.chemicalFactId && (item.linkKind === "PHOSPHODIESTER" || item.linkKind === "CLEAVAGE_SITE"));
      if (!link || link.endpoints.length !== 2) return fail("LINK_MISMATCH", [`${request.interactionId} requires an authenticated binary P2-G link`]);
      const [first, second] = request.participants as [ChemicalLinkParticipant, ChemicalLinkParticipant]; const [left, right] = link.endpoints;
      const matches = (participant: ChemicalLinkParticipant, endpoint: typeof left) => participant.actorId === endpoint.actorId && participant.selectorBindingId === endpoint.selectorBindingId && participant.residueKey === endpoint.residueKey && participant.atomKeys.length === endpoint.atomKeys.length && participant.atomKeys.every((atom) => endpoint.atomKeys.includes(atom));
      const forward = matches(first!, left!) && matches(second!, right!); const reversed = matches(first!, right!) && matches(second!, left!);
      if (first!.actorId === second!.actorId || left!.actorId === right!.actorId || (!forward && !reversed) || !link.endpoints.every((endpoint) => endpoint.atomKeys.length > 0)) return fail("LINK_MISMATCH", [`${request.interactionId} does not bijectively match both authenticated link endpoints`]); factIds = [link.linkAssertionId];
    } else {
      const pairFacts = request.participants.map((participant) => facts.get(participant.chemicalFactId));
      if (pairFacts.some((fact) => !fact)) return fail("CHEMICAL_FACT_MISSING", [`${request.interactionId} references missing P2-G chemistry`]);
      if (request.participants.some((participant, index) => !actors.has(participant.actorId) || pairFacts[index]!.actorId !== participant.actorId)) return fail("CHEMICAL_FACT_MISSING", [`${request.interactionId} fact/actor mismatch`]);
      if (request.kind === "basePairing" && (!pairFacts.every((fact) => fact!.target === "base") || !canonical(pairFacts[0]!, pairFacts[1]!))) return fail("CHEMISTRY_INCOMPATIBLE", [`${request.interactionId} is not canonical under P2-G facts`]);
      if (request.kind === "hydrogenBond" && !((pairFacts[0]!.target === "donor" && pairFacts[1]!.target === "acceptor") || (pairFacts[0]!.target === "acceptor" && pairFacts[1]!.target === "donor"))) return fail("CHEMISTRY_INCOMPATIBLE", [`${request.interactionId} requires P2-G donor/acceptor facts`]);
      for (const participant of request.participants) if (participant.anchorId && !(actorRecords.get(participant.actorId)?.anchors ?? []).some((anchor) => anchor.id === participant.anchorId)) return fail("SELECTOR_UNRESOLVED", [`${request.interactionId} has dangling actor anchor`]);
      factIds = request.participants.map((participant) => participant.chemicalFactId); participantIdentity[request.interactionId] = pairFacts.map((fact) => `${fact!.nucleicChemistry}:${fact!.base}`);
    }
    interactions.push({ interactionId: request.interactionId, kind: request.kind === "phosphodiesterLinkage" || request.kind === "covalentBond" ? "covalent" : request.kind === "polymerContinuity" ? "semanticRelation" : "noncovalent", type: request.kind, participants: request.participants.map((participant) => ({ actorId: participant.actorId, ...("anchorId" in participant && participant.anchorId ? { anchorId: participant.anchorId } : {}) })), state: request.state ?? "present" });
    evidence[request.interactionId] = { outputKind: "interaction", evidence: request.evidence, provenanceSourceId: String(input.grounding.provenance.sourceId), structureId: input.grounding.structureContext.structureId, selectorBindingIds: factIds.flatMap((id) => facts.get(id) ? [facts.get(id)!.bindingId] : input.chemistry.linkAssertions.find((link) => link.linkAssertionId === id)?.endpoints.map((endpoint) => endpoint.selectorBindingId) ?? []), chemicalFactIds: factIds.filter((id) => facts.has(id)), linkAssertionIds: factIds.filter((id) => input.chemistry.linkAssertions.some((link) => link.linkAssertionId === id)), fidelity: input.grounding.fidelity.decision.fidelity };
  }
  const continuities: ScientificContinuity[] = (input.continuities ?? []).map(({ chemicalFactId, ...item }) => item);
  for (const item of input.continuities ?? []) if (!actors.has(item.strandActorId) || item.orderedActorIds.some((id) => !actors.has(id)) || (item.chemicalFactId && !facts.has(item.chemicalFactId))) return fail("TOPOLOGY_INCONSISTENT", [`continuity ${item.continuityId} is ungrounded or dangling`]);
  const changes = (input.changes ?? []).map(({ terminusFactIds, chemicalFactId, ...item }) => item);
  for (const item of input.changes ?? []) { if (item.actorIds.some((id) => !actors.has(id)) || item.interactionIds?.some((id) => !ids.has(id))) return fail("TOPOLOGY_INCONSISTENT", [`change ${item.changeId} has dangling F2 references`]); if (item.biochemicalDirection) { const terminal = item.terminusFactIds?.map((id) => facts.get(id)); const [five, three] = terminal ?? []; if (!five || !three || five.target !== "fivePrimeTerminus" || three.target !== "threePrimeTerminus" || item.actorIds.length < 2 || five.actorId !== item.actorIds[0] || three.actorId !== item.actorIds[1]) return fail("TERMINUS_UNGROUNDED", [`change ${item.changeId} requires exact ordered participating 5′/3′ facts`]); } if ((item.kind === "cleavage" || item.kind === "fragmentation") && (!item.chemicalFactId || !input.chemistry.linkAssertions.some((link) => link.linkAssertionId === item.chemicalFactId && link.linkKind === "CLEAVAGE_SITE"))) return fail("LINK_MISMATCH", [`change ${item.changeId} requires a cleavage-site link fact`]); }
  const trace = (outputKind: InteractionEvidenceTrace["outputKind"], recordId: string, chemicalFactIds: readonly string[] = [], linkAssertionIds: readonly string[] = [], evidenceKind: InteractionEvidenceKind = "CHEMICAL_RULE") => { evidence[recordId] = { outputKind, evidence: evidenceKind, provenanceSourceId, structureId: resolvedStructureId, selectorBindingIds: [...chemicalFactIds.flatMap((id) => facts.get(id) ? [facts.get(id)!.bindingId] : []), ...linkAssertionIds.flatMap((id) => input.chemistry.linkAssertions.find((link) => link.linkAssertionId === id)?.endpoints.map((endpoint) => endpoint.selectorBindingId) ?? [])], chemicalFactIds, linkAssertionIds, fidelity: resolvedFidelity }; };
  for (const item of input.continuities ?? []) trace("continuity", item.continuityId, item.chemicalFactId && facts.has(item.chemicalFactId) ? [item.chemicalFactId] : [], item.chemicalFactId && input.chemistry.linkAssertions.some((link) => link.linkAssertionId === item.chemicalFactId) ? [item.chemicalFactId] : []);
  for (const item of input.changes ?? []) trace("change", item.changeId, [...(item.terminusFactIds ?? []), ...(item.chemicalFactId && facts.has(item.chemicalFactId) ? [item.chemicalFactId] : [])], item.chemicalFactId && input.chemistry.linkAssertions.some((link) => link.linkAssertionId === item.chemicalFactId) ? [item.chemicalFactId] : []);
  for (const item of input.constraints ?? []) trace("constraint", item.constraintId);
  const model: ScientificTopologyModel = { topology: { graphId: "grounded-topology", actorIds: [...actors], interactions, ...(continuities.length ? { continuities } : {}), ...(changes.length ? { changes } : {}) }, states: [], constraints: input.constraints ?? [] };
  const validation = validateScientificTopologyModel(model, input.actorScene);
  return validation.valid ? { ok: true, model, evidence, participantIdentity } : fail("TOPOLOGY_INCONSISTENT", validation.issues.map((issue) => `${issue.path}: ${issue.message}`));
}
