import assert from "node:assert/strict";
import test from "node:test";
import { materializeActorDeclarations, materializeChemistryRequests, materializeSelectorRequests, materializeSourceRequest, materializeStructureRequest, materializeTopologyRequests, planScientificScene } from "./p2-h-scientific-plan-compiler.ts";
import { createScientificFixtureWorld } from "./p2-tf-scientific-grounding-fixtures.ts";
import { createScientificExecutionInventoryFromFixtureWorld } from "./scientific-execution-inventory.ts";
import { semanticIntentFixtures } from "./semantic-intent-fixtures.ts";
import { resolveScientificSourceProvenance } from "./scientific-source-provenance-resolver.ts";
import { resolveStructureContext } from "./p2-d-structure-context.ts";
import { resolveMolecularIdentitySelectors } from "./p2-molecular-selector-grounding.ts";
import { resolveFidelityUncertainty } from "./fidelity-uncertainty-authority.ts";
import { groundAuthenticatedLocalChemistry, type GroundedLocalChemistryResult } from "./p2-local-chemistry-grounding.ts";

test("P2-H materializes actor, source, structure, and selector requests from plan plus raw inventory", () => {
  const planned = planScientificScene(semanticIntentFixtures.slang!, { capabilityId: "dna-base-pairing" }); assert.equal(planned.ok, true); if (!planned.ok) return;
  const inventory = createScientificExecutionInventoryFromFixtureWorld(createScientificFixtureWorld("dnaAT")); const actors = materializeActorDeclarations(planned.plan); const source = materializeSourceRequest(planned.plan, inventory); assert.ok(source); if (!source) return; const validated = resolveScientificSourceProvenance(source, { actorIds: actors.actors.map((item) => item.actorId), groupIds: [] }); assert.equal(validated.ok, true); if (!validated.ok) return; const structureRequest = materializeStructureRequest(planned.plan, inventory, validated.source); const context = resolveStructureContext(validated.source, inventory.entries[0]!.structureInventory!, structureRequest); assert.equal(context.outcome, "RESOLVED"); if (context.outcome !== "RESOLVED") return; const bindings = materializeSelectorRequests(planned.plan, inventory.entries[0]!.structure!.structureId, actors); const selectors = resolveMolecularIdentitySelectors({ schemaVersion: "1", actorScene: actors, structure: inventory.entries[0]!.structure, resolvedContext: context.context, bindings }); assert.equal(selectors.valid, true); assert.equal(bindings[0]!.selector.kind, "localGroup"); assert.equal(bindings[0]!.selector.chain.id, "A");
});

test("P2-H materializes chemistry and exact P2-E endpoints only after authority outputs", () => {
  const planned = planScientificScene(semanticIntentFixtures.rnaHairpin!, { capabilityId: "rna-cleavage" }); assert.equal(planned.ok, true); if (!planned.ok) return; const world = createScientificFixtureWorld("rnaCleavage"); const inventory = createScientificExecutionInventoryFromFixtureWorld(world); const actors = materializeActorDeclarations(planned.plan); const source = materializeSourceRequest(planned.plan, inventory)!; const validated = resolveScientificSourceProvenance(source, { actorIds: actors.actors.map((item) => item.actorId), groupIds: [] }); assert.equal(validated.ok, true); if (!validated.ok) return; const structureRequest = materializeStructureRequest(planned.plan, inventory, validated.source); const context = resolveStructureContext(validated.source, inventory.entries[0]!.structureInventory!, structureRequest); assert.equal(context.outcome, "RESOLVED"); if (context.outcome !== "RESOLVED") return; const bindings = materializeSelectorRequests(planned.plan, world.structure.structureId, actors); const selectors = resolveMolecularIdentitySelectors({ schemaVersion: "1", actorScene: actors, structure: world.structure, resolvedContext: context.context, bindings }); assert.equal(selectors.valid, true); const fidelity = resolveFidelityUncertainty({ ...({ grounding: { kind: "sourceSelected", confidence: .95 }, mechanismEvidence: "direct", representation: { requirement: "depositedCoordinates", declaredBy: "evidence" } }), sources: [validated.source] }); assert.equal(fidelity.accepted, true); if (!fidelity.accepted || !selectors.valid) return; const substrate = { outcome: "RESOLVED" as const, provenance: validated.source, structureContext: context.context, selectors: { valid: true as const, resolutions: selectors.resolutions, issues: [] as [] }, fidelity }; const chemistryRequests = materializeChemistryRequests(planned.plan, selectors); assert.ok(chemistryRequests.some((item) => item.target === "cleavageSite")); const chemistry = groundAuthenticatedLocalChemistry({ schemaVersion: "1", substrate, structure: world.structure, components: world.components, connectivity: world.connectivity, requests: chemistryRequests }); assert.equal((chemistry as { schemaVersion?: string }).schemaVersion, "2"); if (!((chemistry as { schemaVersion?: string }).schemaVersion === "2")) return; const topology = materializeTopologyRequests(planned.plan, actors, chemistry as GroundedLocalChemistryResult); assert.equal(topology.interactions[0]!.participants.length, 2); assert.equal(topology.changes[0]!.chemicalFactId, "link");
});
