/** P2-J1: owner-compatible projections of already-grounded scientific facts. */
import { actorId, groupId, type ScientificActor, type ScientificActorId } from "./scientific-actor.ts";
import type { GroundedScientificPlanResult } from "./p2-h-scientific-plan-compiler.ts";
import type { SceneSpecV1 } from "./scene-spec-v1.ts";
import type { ScientificSceneSpec } from "./scientific-scene-spec.ts";
import { validateSceneSpecV1 } from "./scene-spec-v1.ts";

export type OwnerViewTrace = Readonly<{ sourceSelectorIds: readonly string[]; sourceChemistryAssertionIds: readonly string[]; sourceInteractionIds: readonly string[]; sourceTopologyChangeIds: readonly string[]; sourceContinuityIds: readonly string[] }>;
export type OwnerViewFailure = Readonly<{ ok: false; code: "OWNER_VIEW_UNAVAILABLE"; reasons: readonly string[] }>;
export type OwnerViewResult<T> = (Readonly<{ ok: true; sceneSpec: SceneSpecV1; trace: OwnerViewTrace; view: T }> | OwnerViewFailure);
type Grounded = Extract<GroundedScientificPlanResult, { ok: true }>;
export type DnaBasePairingOwnerView = Readonly<{ actorIds: readonly [ScientificActorId, ScientificActorId]; pair: "A-T" | "G-C" }>;
export type DnaStrandSeparationOwnerView = Readonly<{ strandActorIds: readonly [ScientificActorId, ScientificActorId]; closedStateId: string; openStateId: string; separationChangeId: string }>;
export type RnaHairpinOwnerView = Readonly<{ rnaActorId: ScientificActorId; pairedRegionGroupId: string; pairedStateId: string; basePairingInteractionIds: readonly string[] }>;
export type RnaExonucleaseOwnerView = Readonly<{ rnaActorId: ScientificActorId; retainedActorId: ScientificActorId; terminalShorteningInteractionId: string; partiallyDegradedStateId: string; continuityId: string; topologyChangeId: string }>;

const unavailable = (reasons: readonly string[]): OwnerViewFailure => ({ ok: false, code: "OWNER_VIEW_UNAVAILABLE", reasons });
const trace = (selectors: readonly string[], chemistry: readonly string[], interactions: readonly string[] = [], changes: readonly string[] = [], continuities: readonly string[] = []): OwnerViewTrace => ({ sourceSelectorIds: selectors, sourceChemistryAssertionIds: chemistry, sourceInteractionIds: interactions, sourceTopologyChangeIds: changes, sourceContinuityIds: continuities });
const validScene = (sceneSpec: SceneSpecV1): OwnerViewFailure | undefined => { const result = validateSceneSpecV1(sceneSpec); return result.valid ? undefined : unavailable(result.issues.map((issue) => `${issue.path}: ${issue.message}`)); };
const actor = (source: ScientificActor, id: ScientificActorId, semanticTypeId: string, scope: ScientificActor["scope"]): ScientificActor => ({ ...source, actorId: id, semanticTypeId: semanticTypeId as never, instanceId: id, scope });
const remapParticipants = (scene: ScientificSceneSpec, mapping: ReadonlyMap<string, ScientificActorId>): ScientificSceneSpec["topology"]["interactions"] => scene.topology.interactions.map((interaction) => ({ ...interaction, participants: interaction.participants.map((participant) => ({ ...participant, actorId: mapping.get(String(participant.actorId)) ?? participant.actorId })) }));

export function adaptDnaBasePairingOwnerView(sceneSpec: SceneSpecV1, scientific: Grounded): OwnerViewResult<DnaBasePairingOwnerView> {
  const plan = scientific.plan; const first = plan.selectorRequirements.find((item) => item.selectorId === "base-a"); const second = plan.selectorRequirements.find((item) => item.selectorId === "base-b");
  const facts = scientific.chemistry.assertions.filter((item) => item.target === "base" && (item.bindingId === "base-a" || item.bindingId === "base-b")); const pairInteraction = scientific.scientificScene.topology.interactions.find((item) => item.type === "basePairing" && item.state === "present");
  if (!first?.base || !second?.base || facts.length !== 2 || !pairInteraction) return unavailable(["grounded base selectors, two P2-G base facts, and a present P2-E canonical pair are required"]);
  const pair = first.base === "A" && second.base === "T" ? "A-T" : first.base === "G" && second.base === "C" ? "G-C" : undefined; if (!pair) return unavailable(["grounded base facts do not form a supported canonical DNA pair"]);
  const sourceActors = sceneSpec.scientificScene.actors.filter((item) => pairInteraction.participants.some((participant) => participant.actorId === item.actorId)); if (sourceActors.length !== 2) return unavailable(["canonical pair does not reference exactly two grounded actors"]);
  const ids = [actorId(`${String(sourceActors[0]!.actorId)}-base`), actorId(`${String(sourceActors[1]!.actorId)}-base`)] as const; const mapping = new Map(sourceActors.map((item, index) => [String(item.actorId), ids[index]! as ScientificActorId]));
  const actors = sourceActors.map((item, index) => actor(item, ids[index]!, index === 0 ? (pair === "A-T" ? "adenine" : "guanine") : (pair === "A-T" ? "thymine" : "cytosine"), "residue"));
  const remapId = (value: string) => mapping.get(value) ?? value;
  const projected: SceneSpecV1 = { ...sceneSpec, scientificScene: { ...sceneSpec.scientificScene, actors, topology: { ...sceneSpec.scientificScene.topology, actorIds: [...ids], interactions: remapParticipants(sceneSpec.scientificScene, mapping) }, fidelityProvenance: { ...sceneSpec.scientificScene.fidelityProvenance, attachments: sceneSpec.scientificScene.fidelityProvenance.attachments.map((item) => ({ ...item, target: item.target.kind === "actor" ? { ...item.target, actorId: remapId(String(item.target.actorId)) as ScientificActorId } : item.target })) }, presentationIntent: { ...sceneSpec.scientificScene.presentationIntent, focusActorIds: sceneSpec.scientificScene.presentationIntent.focusActorIds.map((id) => remapId(String(id)) as ScientificActorId), contextActorIds: sceneSpec.scientificScene.presentationIntent.contextActorIds.map((id) => remapId(String(id)) as ScientificActorId), ...(sceneSpec.scientificScene.presentationIntent.regionOfInterest ? { regionOfInterest: sceneSpec.scientificScene.presentationIntent.regionOfInterest.map((item) => item.kind === "actor" ? { ...item, actorId: remapId(String(item.actorId)) as ScientificActorId } : item) } : {}), annotationPriority: sceneSpec.scientificScene.presentationIntent.annotationPriority.map((item) => item.kind === "actor" ? { ...item, actorId: remapId(String(item.actorId)) as ScientificActorId } : item) } } };
  const invalid = validScene(projected); if (invalid) return invalid;
  return { ok: true, sceneSpec: projected, trace: trace([first.selectorId, second.selectorId], facts.map((item) => item.assertionId), [pairInteraction.interactionId]), view: { actorIds: ids, pair } };
}

export function adaptDnaStrandSeparationOwnerView(sceneSpec: SceneSpecV1, scientific: Grounded): OwnerViewResult<DnaStrandSeparationOwnerView> {
  const pair = sceneSpec.scientificScene.topology.interactions.find((item) => item.type === "basePairing"); const change = sceneSpec.scientificScene.topology.changes?.find((item) => item.kind === "separation"); const strands = sceneSpec.scientificScene.actors.filter((item) => item.semanticTypeId === "dna");
  if (!pair || !change || strands.length !== 2 || !change.actorIds.every((id) => strands.some((actor) => actor.actorId === id))) return unavailable(["grounded DNA strand actors, pairing topology, and separation TopologyChange are required"]);
  const closedStateId = "grounded-closed"; const openStateId = "grounded-open"; const projected: SceneSpecV1 = { ...sceneSpec, scientificScene: { ...sceneSpec.scientificScene, actors: strands.map((item) => actor(item, item.actorId, "strand", "strand")), states: [{ stateId: closedStateId, kind: "closed", actorIds: strands.map((item) => item.actorId), interactionIds: [pair.interactionId] }, { stateId: openStateId, kind: "open", actorIds: strands.map((item) => item.actorId), interactionIds: [pair.interactionId], topologyChangeIds: [change.changeId] }], topology: { ...sceneSpec.scientificScene.topology, actorIds: strands.map((item) => item.actorId), interactions: sceneSpec.scientificScene.topology.interactions.map((item) => item.interactionId === pair.interactionId ? { ...item, state: "absent" as const } : item) } } };
  const invalid = validScene(projected); if (invalid) return invalid;
  return { ok: true, sceneSpec: projected, trace: trace(scientific.plan.selectorRequirements.map((item) => item.selectorId), scientific.chemistry.assertions.map((item) => item.assertionId), [pair.interactionId], [change.changeId]), view: { strandActorIds: [strands[0]!.actorId, strands[1]!.actorId], closedStateId, openStateId, separationChangeId: change.changeId } };
}

export function adaptRnaHairpinOwnerView(sceneSpec: SceneSpecV1, scientific: Grounded): OwnerViewResult<RnaHairpinOwnerView> {
  const rna = sceneSpec.scientificScene.actors.find((item) => item.semanticTypeId === "rna"); const pairs = sceneSpec.scientificScene.topology.interactions.filter((item) => item.type === "basePairing" && item.state === "present"); const facts = scientific.chemistry.assertions.filter((item) => item.target === "base");
  if (!rna || pairs.length === 0 || facts.length < 2) return unavailable(["grounded RNA actor, paired base interactions, and base chemistry facts are required"]);
  const pairedRegionGroupId = groupId(`group-${sceneSpec.sceneId}-stem`); const pairedStateId = "grounded-paired"; const actors = sceneSpec.scientificScene.actors.map((item) => actor(item, item.actorId, item.semanticTypeId, item.scope)); const projected: SceneSpecV1 = { ...sceneSpec, scientificScene: { ...sceneSpec.scientificScene, actors, groups: [{ groupId: pairedRegionGroupId, kind: "pairedStem", memberActorIds: pairs.flatMap((item) => item.participants.map((participant) => participant.actorId)).filter((id, index, all) => all.indexOf(id) === index) }], states: [{ stateId: pairedStateId, kind: "paired", actorIds: [rna.actorId], interactionIds: pairs.map((item) => item.interactionId) }] } };
  const invalid = validScene(projected); if (invalid) return invalid;
  return { ok: true, sceneSpec: projected, trace: trace(scientific.plan.selectorRequirements.map((item) => item.selectorId), facts.map((item) => item.assertionId), pairs.map((item) => item.interactionId)), view: { rnaActorId: rna.actorId, pairedRegionGroupId, pairedStateId, basePairingInteractionIds: pairs.map((item) => item.interactionId) } };
}

export function adaptRnaExonucleaseOwnerView(sceneSpec: SceneSpecV1, scientific: Grounded): OwnerViewResult<RnaExonucleaseOwnerView> {
  const change = sceneSpec.scientificScene.topology.changes?.find((item) => item.kind === "processing" && item.biochemicalDirection); const continuity = sceneSpec.scientificScene.topology.continuities?.find((item) => item.strandActorId === change?.actorIds[0]); const link = scientific.chemistry.linkAssertions.find((item) => item.linkKind === "PHOSPHODIESTER"); const termini = scientific.chemistry.assertions.filter((item) => item.target === "fivePrimeTerminus" || item.target === "threePrimeTerminus");
  if (!change || !continuity || !link || termini.length < 2) return unavailable(["grounded processing change, continuity record, binary phosphodiester link, and both authenticated termini are required"]);
  const sourceActors = sceneSpec.scientificScene.actors.filter((item) => change.actorIds.includes(item.actorId)); if (sourceActors.length < 2) return unavailable(["processing change must reference terminal and retained grounded actors"]);
  const rnaActorId = actorId("rna-1"); const retainedActorId = actorId("retained-rna-1"); const mapping = new Map([[String(sourceActors[0]!.actorId), rnaActorId], [String(sourceActors[1]!.actorId), retainedActorId]]); const terminalShorteningInteractionId = "terminal-shortening"; const projectedInteractions = [...remapParticipants(sceneSpec.scientificScene, mapping), { interactionId: terminalShorteningInteractionId, kind: "semanticRelation" as const, type: "terminalDegradation" as const, participants: [{ actorId: rnaActorId, anchorId: "five-prime" }, { actorId: retainedActorId, anchorId: "five-prime" }], state: "present" as const, explanatory: true }]; const remapId = (value: string) => mapping.get(value) ?? value; const projectedChanges = (sceneSpec.scientificScene.topology.changes ?? []).map((item) => ({ ...item, actorIds: item.actorIds.map((id) => remapId(String(id)) as ScientificActorId) }));
  const projected: SceneSpecV1 = { ...sceneSpec, scientificScene: { ...sceneSpec.scientificScene, actors: [{ ...actor(sourceActors[0]!, rnaActorId, "rna", "polymer"), anchors: [{ id: "five-prime", kind: "terminus" as const }, { id: "three-prime", kind: "terminus" as const }] }, { ...actor(sourceActors[1]!, retainedActorId, "cleavageFragment", "polymer"), anchors: [{ id: "five-prime", kind: "terminus" as const }, { id: "three-prime", kind: "terminus" as const }] }], states: [{ stateId: "grounded-intact", kind: "intact", actorIds: [rnaActorId] }, { stateId: "grounded-partially-degraded", kind: "partiallyDegraded", actorIds: [rnaActorId, retainedActorId], interactionIds: [terminalShorteningInteractionId], topologyChangeIds: [change.changeId] }], topology: { ...sceneSpec.scientificScene.topology, actorIds: [rnaActorId, retainedActorId], interactions: projectedInteractions, changes: projectedChanges, continuities: [{ ...continuity, strandActorId: rnaActorId, orderedActorIds: [rnaActorId, retainedActorId], state: "partial" }] }, fidelityProvenance: { ...sceneSpec.scientificScene.fidelityProvenance, attachments: sceneSpec.scientificScene.fidelityProvenance.attachments.map((item) => ({ ...item, target: item.target.kind === "actor" ? { ...item.target, actorId: remapId(String(item.target.actorId)) as ScientificActorId } : item.target })) }, presentationIntent: { ...sceneSpec.scientificScene.presentationIntent, focusActorIds: sceneSpec.scientificScene.presentationIntent.focusActorIds.map((id) => remapId(String(id)) as ScientificActorId), contextActorIds: sceneSpec.scientificScene.presentationIntent.contextActorIds.map((id) => remapId(String(id)) as ScientificActorId), ...(sceneSpec.scientificScene.presentationIntent.regionOfInterest ? { regionOfInterest: sceneSpec.scientificScene.presentationIntent.regionOfInterest.map((item) => item.kind === "actor" ? { ...item, actorId: remapId(String(item.actorId)) as ScientificActorId } : item) } : {}), annotationPriority: sceneSpec.scientificScene.presentationIntent.annotationPriority.map((item) => item.kind === "actor" ? { ...item, actorId: remapId(String(item.actorId)) as ScientificActorId } : item) } } };
  const invalid = validScene(projected); if (invalid) return invalid;
  return { ok: true, sceneSpec: projected, trace: trace(scientific.plan.selectorRequirements.map((item) => item.selectorId), [...scientific.chemistry.assertions.map((item) => item.assertionId), link.linkAssertionId], [link.linkAssertionId], [change.changeId], [continuity.continuityId]), view: { rnaActorId, retainedActorId, terminalShorteningInteractionId, partiallyDegradedStateId: "grounded-partially-degraded", continuityId: continuity.continuityId, topologyChangeId: change.changeId } };
}
