/** P2-K: final authority review and fresh, independently frozen holdout. */
import { createHash } from "node:crypto";
import { capabilityRegistry } from "./capability-registry.ts";
import { planScientificScene, executeScientificPlan, composeSceneSpecV1, type GroundedScientificPlanResult } from "./p2-h-scientific-plan-compiler.ts";
import { createScientificFixtureWorld } from "./p2-tf-scientific-grounding-fixtures.ts";
import { createScientificExecutionInventoryFromFixtureWorld, type ScientificExecutionInventoryV1 } from "./scientific-execution-inventory.ts";
import { semanticIntentFixtures } from "./semantic-intent-fixtures.ts";
import type { SemanticIntentV1 } from "./semantic-intent.ts";
import type { ScientificFixtureWorldScenario } from "./p2-tf-scientific-grounding-fixtures.ts";
import { validateScientificSceneSpec } from "./scientific-scene-spec.ts";
import { validateInteractionTopologyEvidence } from "./p2-e-interaction-topology-grounding.ts";
import { migrateProductionScientificScene } from "./p2-j-production-grounding-migration.ts";

export const p2KReviewVersion = "p2-k-v1" as const;
export type P2KExpected = "EXECUTE" | "LIMITED_PLAN" | "COMPUTED_GAP" | "EXPLICIT_FAILURE";
export type P2KCase = Readonly<{ id: string; domain: "DNA" | "RNA" | "cross"; capabilityId: string; scenario: ScientificFixtureWorldScenario; intent: SemanticIntentV1; expected: P2KExpected; expectedCode?: string; ownerExpected?: boolean; sourceStrategy?: "deposited" | "computed" | "constrainedSchematic" | "schematic" }>;
export type P2KCaseResult = Readonly<{ id: string; passed: boolean; critical: boolean; dimensions: Readonly<Record<"capability" | "plan" | "source" | "structure" | "selectors" | "chemistry" | "topology" | "fidelity" | "evidence" | "scene" | "failure" | "owner", boolean>>; code?: string; reasons?: readonly string[] }>;
const validIntent = (base: SemanticIntentV1): SemanticIntentV1 => structuredClone(base);
const strandIntent = validIntent(semanticIntentFixtures.slang!); strandIntent.requests[0] = { ...strandIntent.requests[0]!, subjects: [{ rawText: "DNA", resolvedId: "dna" }, { rawText: "strands", resolvedId: "strand" }], phenomenon: "strandSeparation", mechanism: "strandOpening" };
const exonucleaseIntent: SemanticIntentV1 = { schemaVersion: "1", rawUtterance: "validated structured intent", canonicalGloss: "Validated RNA terminal exonuclease request", acts: ["show"], requests: [{ subjects: [{ rawText: "RNA", resolvedId: "rna", role: "substrate" }, { rawText: "RNA strand", resolvedId: "strand", role: "substrate" }], phenomenon: "exonucleaseDegradation", mechanism: "terminalExonucleaseAction", states: ["intact", "partiallyDegraded"], focus: "terminus", direction: { biochemical: "fiveToThree", meaning: "scientific" }, outputPreferences: ["static"], requestedOutput: "scientificFigure" }], assertedClaims: [], alternatives: [], clarification: { required: false }, confidence: 1 };
const all = (cases: readonly P2KCase[]) => Object.freeze(cases.map((item) => Object.freeze(item)));

/** Frozen before execution; these IDs/scenarios do not occur in the P2-I corpus. */
export const p2KFreshHoldout: readonly P2KCase[] = all([
  { id: "k-dna-01", domain: "DNA", capabilityId: "dna-base-pairing", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXECUTE", ownerExpected: true },
  { id: "k-dna-02", domain: "DNA", capabilityId: "dna-strand-separation", scenario: "dnaAT", intent: strandIntent, expected: "EXECUTE", ownerExpected: true },
  { id: "k-dna-03", domain: "DNA", capabilityId: "dna-phosphodiester-backbone", scenario: "dnaPhosphodiester", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXECUTE" },
  { id: "k-dna-04", domain: "DNA", capabilityId: "dna-canonical-structure", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-dna-05", domain: "DNA", capabilityId: "dna-antiparallel-polarity", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-dna-06", domain: "DNA", capabilityId: "dna-replication", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-dna-07", domain: "DNA", capabilityId: "dna-transcription", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-dna-08", domain: "DNA", capabilityId: "dna-packaging", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-dna-09", domain: "DNA", capabilityId: "dna-damage-repair", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-dna-10", domain: "DNA", capabilityId: "dna-helix-stabilization", scenario: "dnaAT", intent: validIntent(semanticIntentFixtures.slang!), expected: "LIMITED_PLAN" },
  { id: "k-rna-01", domain: "RNA", capabilityId: "rna-secondary-structure", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "EXECUTE", ownerExpected: true },
  { id: "k-rna-02", domain: "RNA", capabilityId: "rna-base-pairing", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "EXECUTE" },
  { id: "k-rna-03", domain: "RNA", capabilityId: "rna-dna-hybridization", scenario: "rnaDnaHybrid", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "EXECUTE" },
  { id: "k-rna-04", domain: "RNA", capabilityId: "rna-cleavage", scenario: "rnaCleavage", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "EXECUTE" },
  { id: "k-rna-05", domain: "RNA", capabilityId: "rna-exonuclease-degradation", scenario: "rnaExonuclease", intent: exonucleaseIntent, expected: "EXECUTE", ownerExpected: true },
  { id: "k-rna-06", domain: "RNA", capabilityId: "rna-generic-structure", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "LIMITED_PLAN" },
  { id: "k-rna-07", domain: "RNA", capabilityId: "rna-processing", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "LIMITED_PLAN" },
  { id: "k-rna-08", domain: "RNA", capabilityId: "rna-nascent-transcript", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "LIMITED_PLAN" },
  { id: "k-rna-09", domain: "RNA", capabilityId: "rna-chemical-stability", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "LIMITED_PLAN" },
  { id: "k-rna-10", domain: "RNA", capabilityId: "rna-local-chemistry", scenario: "rnaAU", intent: validIntent(semanticIntentFixtures.rnaHairpin!), expected: "LIMITED_PLAN" },
  { id: "k-cross-01", domain: "cross", capabilityId: "dna-base-pairing", scenario: "computedModel", intent: validIntent(semanticIntentFixtures.slang!), expected: "COMPUTED_GAP", expectedCode: "COMPUTED_STRUCTURE_CONTEXT_GAP", sourceStrategy: "computed" },
  { id: "k-cross-02", domain: "cross", capabilityId: "dna-base-pairing", scenario: "ambiguousAssembly", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE", expectedCode: "AMBIGUOUS_STRUCTURE" },
  { id: "k-cross-03", domain: "cross", capabilityId: "dna-base-pairing", scenario: "ambiguousModel", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE", expectedCode: "AMBIGUOUS_STRUCTURE" },
  { id: "k-cross-04", domain: "cross", capabilityId: "dna-phosphodiester-backbone", scenario: "missingTerminus", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE" },
  { id: "k-cross-05", domain: "cross", capabilityId: "dna-phosphodiester-backbone", scenario: "malformedConnectivity", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE" },
  { id: "k-cross-06", domain: "cross", capabilityId: "dna-base-pairing", scenario: "excludedChain", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE" },
  { id: "k-cross-07", domain: "cross", capabilityId: "dna-base-pairing", scenario: "missingAtom", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE" },
  { id: "k-cross-08", domain: "cross", capabilityId: "dna-base-pairing", scenario: "fidelityMismatch", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE" },
  { id: "k-cross-09", domain: "cross", capabilityId: "dna-base-pairing", scenario: "repeatedChainAmbiguity", intent: validIntent(semanticIntentFixtures.slang!), expected: "EXPLICIT_FAILURE" },
  { id: "k-cross-10", domain: "cross", capabilityId: "rna-exonuclease-degradation", scenario: "missingComponent", intent: exonucleaseIntent, expected: "EXPLICIT_FAILURE" },
]);
export const p2KFreshHoldoutHash = createHash("sha256").update(JSON.stringify(p2KFreshHoldout)).digest("hex");

const run = (item: P2KCase, inventory?: ScientificExecutionInventoryV1) => { const planned = planScientificScene(item.intent, { capabilityId: item.capabilityId, ...(item.sourceStrategy ? { sourceStrategy: item.sourceStrategy } : {}) }); if (!planned.ok) return { planned, execution: undefined }; const execution = executeScientificPlan(planned.plan, inventory ?? createScientificExecutionInventoryFromFixtureWorld(createScientificFixtureWorld({ scenario: item.scenario }))); return { planned, execution }; };
const codeOf = (execution: ReturnType<typeof executeScientificPlan> | undefined) => execution && !execution.ok ? execution.code : undefined;
export function scoreP2KCase(item: P2KCase): P2KCaseResult { const result = run(item); const plan = result.planned.ok ? result.planned.plan : undefined; const execution = result.execution; const dimensions = { capability: Boolean(plan?.capabilityId === item.capabilityId), plan: Boolean(plan), source: Boolean(plan?.sourceRequirement), structure: Boolean(plan?.structureRequirement), selectors: Boolean(plan?.selectorRequirements.length), chemistry: Boolean(plan?.chemistryRequirements.length), topology: Boolean(plan?.topologyRequirements.length), fidelity: Boolean(plan?.fidelityRequirement), evidence: false, scene: false, failure: false, owner: !item.ownerExpected }; const code = codeOf(execution); if (item.expected === "EXECUTE" && execution?.ok) { dimensions.evidence = validateInteractionTopologyEvidence(execution.topology, execution.substrate, execution.chemistry).valid; dimensions.scene = validateScientificSceneSpec(execution.scientificScene).valid; dimensions.failure = true; if (item.ownerExpected && result.planned.ok) dimensions.owner = migrateProductionScientificScene(item.intent, item.capabilityId, createScientificExecutionInventoryFromFixtureWorld(createScientificFixtureWorld({ scenario: item.scenario }))).ok; const passed = Object.values(dimensions).every(Boolean); return { id: item.id, passed, critical: !passed, dimensions, code }; } if (item.expected === "LIMITED_PLAN") { const passed = Boolean(plan && dimensions.capability && dimensions.plan && dimensions.source && dimensions.structure); return { id: item.id, passed, critical: false, dimensions, code }; } if (item.expected === "COMPUTED_GAP") { const passed = Boolean(code === "UNSUPPORTED_CURRENT_GROUNDING_PATH" && execution && !execution.ok && execution.reasons.includes(item.expectedCode!)); dimensions.failure = passed; return { id: item.id, passed, critical: !passed, dimensions, code, reasons: execution && !execution.ok ? execution.reasons : undefined }; } const passed = Boolean(execution && !execution.ok && (item.expectedCode === undefined || code === item.expectedCode)); dimensions.failure = passed; return { id: item.id, passed, critical: !passed, dimensions, code, reasons: execution && !execution.ok ? execution.reasons : undefined }; }
export function runP2KFreshHoldout() { const results = p2KFreshHoldout.map(scoreP2KCase); return { version: p2KReviewVersion, hash: p2KFreshHoldoutHash, total: results.length, passed: results.filter((item) => item.passed).length, criticalFailures: results.filter((item) => item.critical).length, results }; }
export function runP2KDeterminism(cases: readonly P2KCase[] = p2KFreshHoldout) { const first = cases.map(scoreP2KCase); const second = cases.map(scoreP2KCase); return { deterministic: JSON.stringify(first) === JSON.stringify(second), first, second }; }
export function runP2KMetamorphic() { const base = p2KFreshHoldout[0]!; const first = scoreP2KCase(base); const reorderedIntent = structuredClone(base.intent); reorderedIntent.requests[0] = { ...reorderedIntent.requests[0]!, subjects: [...reorderedIntent.requests[0]!.subjects].reverse() }; const second = scoreP2KCase({ ...base, id: "k-meta-reordered", intent: reorderedIntent }); return { preserved: first.passed === second.passed && first.code === second.code, cases: 1 }; }

export const p2KCapabilityClassification = Object.freeze(capabilityRegistry.map((item) => ({ capabilityId: item.capabilityId, classification: ["dna-base-pairing", "dna-strand-separation", "rna-secondary-structure", "rna-exonuclease-degradation"].includes(item.capabilityId) ? "PRODUCTION_OWNER_MIGRATED" : ["dna-phosphodiester-backbone", "rna-base-pairing", "rna-dna-hybridization", "rna-cleavage"].includes(item.capabilityId) ? "FULLY_EXECUTABLE" : item.fidelityRequirements.minimum === "C0_COMPUTED" ? "UNSUPPORTED_CURRENT_GROUNDING_PATH" : "CONTRACT_SUPPORTED_BUT_GROUNDING_LIMITED" })));
export const p2KAuthorityReview = Object.freeze({ P2B: "source/provenance", P2D: "model/assembly/structure context", P2C: "molecular identity/selectors", P2F: "fidelity/uncertainty", P2G: "local chemistry", P2E: "scientific interactions/topology", P2H: "planning/orchestration", P2J1: "non-authoritative owner projection", rawPromptInspectionAfterIngress: false, visualStatus: "UNVERIFIED — ENVIRONMENT BLOCKED", deferredGate: "P2_J_VISUAL_ACCEPTANCE_PENDING", computedTopology: "COMPUTED_STRUCTURE_CONTEXT_GAP" as const });
