/** Test-only raw-data factory. Authority results are produced by B/C/D/F/G. */
import { actorId, type ScientificActorScene } from "./scientific-actor.ts";
import type { NormalizedMolecularStructure } from "./biology-structure-grounding.ts";
import { resolveGroundingSubstrate, type GroundingSubstrateResult } from "./p2-bcdf-grounding-seam.ts";
import { groundAuthenticatedLocalChemistry, groundLocalChemistry, isAuthenticatedLocalChemistryResult, type GroundedLocalChemistryResult, type LocalChemicalComponent, type LocalChemistryRequest } from "./p2-local-chemistry-grounding.ts";
import type { ScientificFixtureWorld } from "./scientific-execution-inventory.ts";

const point = [0, 0, 0] as [number, number, number]; const bounds = { min: point, max: point };
const baseAtoms: Record<string, readonly string[]> = { A: ["N6", "N1"], T: ["N3", "O4"], G: ["N1", "N2", "O6"], C: ["N4", "N3", "O2"], U: ["N3", "O4"] };
const atom = (atomName: string, residueName: string, residueSequence: number, chainId: string, entityType: "dna" | "rna") => ({ serial: residueSequence, atomName, residueName, residueSequence, residueInsertionCode: "", chainId, entityType, element: atomName === "P" ? "P" : "N", x: 0, y: 0, z: 0 });
const residue = (residueName: string, chainId: string, entityType: "dna" | "rna", residueSequence = 1) => ({ key: `${chainId}:${residueSequence}`, residueName, residueSequence, authSeqId: residueSequence, residueInsertionCode: "", chainId, entityType, atoms: ["P", "O3'", "O5'", "C1'", ...(entityType === "rna" ? ["O2'"] : []), ...baseAtoms[residueName]!].map((name) => atom(name, residueName, residueSequence, chainId, entityType)), centroid: point });
const chain = (id: string, residueName: string, entityType: "dna" | "rna", residues = [residue(residueName, id, entityType)]) => ({ id, authAsymId: id, labelAsymId: id, entityType, residues, atoms: [], centroid: point, bounds });
const polymerChain = (id: string, names: readonly ("A" | "C" | "G" | "T" | "U")[], entityType: "dna" | "rna") => chain(id, names[0]!, entityType, names.map((name, index) => residue(name, id, entityType, index + 1)));
const componentFor = (base: "A" | "C" | "G" | "T" | "U", entityType: "dna" | "rna"): LocalChemicalComponent => ({ componentId: base, nucleicChemistry: entityType === "dna" ? "DNA" : "RNA", base, sugar: entityType === "dna" ? "deoxyribose" : "ribose", atomNames: ["P", "O3'", "O5'", "C1'", ...(entityType === "rna" ? ["O2'"] : []), ...baseAtoms[base]!], donorAtomNames: base === "A" ? ["N6"] : base === "G" ? ["N1", "N2"] : base === "C" ? ["N4"] : ["N3"], acceptorAtomNames: base === "A" ? ["N1"] : base === "G" ? ["O6"] : base === "C" ? ["N3", "O2"] : ["O4"], evidenceType: "ccdComponent", confidence: .95, limitations: ["bounded P2-TF component catalog"] });

export type ScientificGroundingFixtureKind = "dnaAT" | "dnaGC" | "rnaAU" | "rnaGC" | "rnaDnaHybrid" | "invalidAG";
export type ScientificFixtureWorldScenario = "dnaAT" | "dnaGC" | "rnaAU" | "rnaGC" | "rnaDnaHybrid" | "invalidAG" | "dnaPhosphodiester" | "rnaPhosphodiester" | "rnaCleavage" | "rnaExonuclease" | "strandSeparation" | "computedModel" | "constrainedSchematic" | "schematic" | "invalidProvenance" | "ambiguousAssembly" | "ambiguousModel" | "excludedChain" | "missingResidue" | "missingAtom" | "missingComponent" | "malformedConnectivity" | "missingTerminus" | "oneSidedPhosphodiester" | "fidelityMismatch" | "repeatedChainAmbiguity";
export type ScientificFixtureWorldSpec = { scenario: ScientificFixtureWorldScenario; source?: "deposited" | "computed" | "constrainedSchematic" | "schematic" | "invalidProvenance"; assembly?: "normal" | "ambiguous"; model?: "normal" | "ambiguous"; chain?: "normal" | "excluded" | "repeatedAmbiguous"; residue?: "normal" | "missing"; atom?: "normal" | "missing"; component?: "normal" | "missing"; connectivity?: "normal" | "cleavage" | "exonuclease" | "strandSeparation" | "malformed" | "missingTerminus" | "oneSidedPhosphodiester"; fidelity?: "E0" | "C0" | "S1" | "S2" | "mismatch" };
type Base = "A" | "C" | "G" | "T" | "U"; const pairs: Record<string, readonly [Base, Base, "dna" | "rna", "dna" | "rna"]> = { dnaAT: ["A", "T", "dna", "dna"], dnaGC: ["G", "C", "dna", "dna"], rnaAU: ["A", "U", "rna", "rna"], rnaGC: ["G", "C", "rna", "rna"], rnaDnaHybrid: ["G", "C", "rna", "dna"] };

/** Builds raw data first, then applies the requested scenario mutation. */
export function createScientificFixtureWorld(input: ScientificFixtureWorldSpec | ScientificGroundingFixtureKind | ConnectivityFixtureKind = "dnaAT"): ScientificFixtureWorld {
  const spec: ScientificFixtureWorldSpec = typeof input === "string" ? { scenario: input } : input; const scenario = spec.scenario; const pair = scenario === "invalidAG" ? ["A", "G", "dna", "dna"] as const : pairs[scenario] ?? ["A", "C", scenario === "dnaPhosphodiester" ? "dna" : "rna", scenario === "dnaPhosphodiester" ? "dna" : "rna"] as const; const structureId = `fixture-${scenario.replace(/[A-Z]/g, (x) => `-${x.toLowerCase()}`)}`; const strandA = actorId("fixture-dna-a"); const strandB = actorId("fixture-dna-b");
  const actorScene = { actors: [{ actorId: strandA, semanticTypeId: "strand" as const, scope: "strand" as const, instanceId: "fixture-a" }, { actorId: strandB, semanticTypeId: "strand" as const, scope: "strand" as const, instanceId: "fixture-b" }], groups: [] } satisfies ScientificActorScene; const isPolymer = ["dnaPhosphodiester", "rnaPhosphodiester", "rnaCleavage", "rnaExonuclease"].includes(scenario); const entityA = pair[2]; const entityB = pair[3];
  let structure = { structureId, chains: isPolymer ? [polymerChain("A", ["A", "C"], entityA), polymerChain("B", [entityA === "rna" ? "U" : "T"], entityA)] : [chain("A", pair[0], entityA), chain("B", pair[1], entityB)] } satisfies Pick<NormalizedMolecularStructure, "structureId" | "chains">;
  const sourceKind = spec.source ?? (scenario === "computedModel" ? "computed" : scenario === "constrainedSchematic" ? "constrainedSchematic" : scenario === "schematic" ? "schematic" : scenario === "invalidProvenance" ? "invalidProvenance" : "deposited"); const sourceType = sourceKind === "computed" ? "computedModel" : sourceKind === "constrainedSchematic" || sourceKind === "schematic" ? "educationalSchematic" : "depositedStructure"; const sourceFidelity = sourceKind === "computed" ? "C0_COMPUTED" : sourceKind === "constrainedSchematic" ? "S1_CONSTRAINED" : sourceKind === "schematic" ? "S2_SCHEMATIC" : "E0_DEPOSITED";
  const provenance: ScientificFixtureWorld["provenance"] = { sourceId: `${structureId}-source`, sourceType: sourceType as any, fidelity: sourceFidelity as any, provider: sourceType === "depositedStructure" ? { id: "RCSB-PDB" } : { id: "local-curated" }, ...(sourceType === "depositedStructure" ? { accessionOrEntryId: `TEST-${scenario}`, citationReference: "fixture-citation", licenseReference: "fixture-license" } : {}), structure: { structureId, ...(sourceType === "depositedStructure" && scenario !== "ambiguousAssembly" ? { assemblyId: "1" } : {}) }, contentHash: `pending:${structureId}`, sourceConfidence: .95, groundingConfidence: .95, mechanismEvidence: sourceKind === "schematic" ? "educational" as const : "direct" as const, visualApproximation: sourceKind === "constrainedSchematic" ? "constrained" as const : sourceKind === "schematic" ? "schematic" as const : "minor" as const, attachmentId: `${structureId}-attachment`, target: { kind: "actor" as const, id: "fixture-dna-a" }, ...(scenario === "invalidProvenance" ? { accessionOrEntryId: undefined } : {}) };
  const binding = (id: string, actor: ReturnType<typeof actorId>, chainId: string, sequence: number, base: Base) => ({ bindingId: id, actorId: actor, instanceId: actor === strandA ? "fixture-a" : "fixture-b", selector: { kind: "localGroup" as const, structureId, chain: { namespace: "normalized" as const, id: chainId }, residue: { start: sequence, end: sequence, namespace: "auth" as const }, group: "base" as const, base } }); let bindings: any[] = isPolymer ? [binding("fixture-upstream", strandA, "A", 1, "A"), binding("fixture-downstream", strandB, "A", 2, "C"), binding("fixture-base-t", strandB, "B", 1, entityA === "rna" ? "U" : "T")] : [binding("fixture-base-a", strandA, "A", 1, pair[0]), binding("fixture-base-t", strandB, "B", 1, pair[1])];
  let inventory = { asymmetricUnit: { chainIds: structure.chains.map((x) => x.id), modelNumbers: [1] }, biologicalAssemblies: [{ assemblyId: "1", chainIds: structure.chains.map((x) => x.id), modelNumbers: [1] }] }; let structureRequest: ScientificFixtureWorld["structureRequest"] = { assembly: { kind: "biologicalAssembly", assemblyId: "1" }, modelNumber: 1, chainIds: structure.chains.map((x) => x.id) }; let components = isPolymer ? [componentFor("A", entityA), componentFor("C", entityA), componentFor(entityA === "rna" ? "U" : "T", entityA)] : [componentFor(pair[0], entityA), componentFor(pair[1], entityB)];
  const state = scenario === "rnaCleavage" ? "cleaved" as const : "intact" as const; const target = scenario === "rnaCleavage" ? "cleavageSite" as const : "phosphodiester" as const; let connectivity = { termini: isPolymer ? [{ terminus: "fivePrime" as const, residueKey: "A:1" }, { terminus: "threePrime" as const, residueKey: "A:2" }] : [{ terminus: "fivePrime" as const, residueKey: "A:1" }, { terminus: "threePrime" as const, residueKey: "B:1" }], phosphodiesterLinks: isPolymer ? [{ linkId: "fixture-link", upstreamResidueKey: "A:1", downstreamResidueKey: "A:2", atomKeys: ["A:1:O3'", "A:2:P"], state }] : [] }; let chemistryRequests: LocalChemistryRequest[] = isPolymer ? [{ assertionId: "fixture-upstream-base", bindingId: "fixture-upstream", componentId: "A", target: "base" }, { assertionId: "fixture-downstream-base", bindingId: "fixture-downstream", componentId: "C", target: "base" }, { assertionId: "fixture-link", bindingId: "fixture-upstream", componentId: "A", target, linkId: "fixture-link" }, { assertionId: "fixture-five-prime", bindingId: "fixture-upstream", componentId: "A", target: "fivePrimeTerminus" }, { assertionId: "fixture-three-prime", bindingId: "fixture-downstream", componentId: "C", target: "threePrimeTerminus" }] : [{ assertionId: "fixture-base-a", bindingId: "fixture-base-a", componentId: pair[0], target: "base" }, { assertionId: "fixture-base-t", bindingId: "fixture-base-t", componentId: pair[1], target: "base" }];
  if (scenario === "ambiguousAssembly" || spec.assembly === "ambiguous") { inventory = { ...inventory, biologicalAssemblies: [{ assemblyId: "1", chainIds: ["A", "B"], modelNumbers: [1] }, { assemblyId: "2", chainIds: ["A", "B"], modelNumbers: [1] }] }; structureRequest = { assembly: { kind: "biologicalAssembly" }, modelNumber: 1, chainIds: ["A", "B"] }; } if (scenario === "ambiguousModel" || spec.model === "ambiguous") { inventory = { ...inventory, biologicalAssemblies: [{ assemblyId: "1", chainIds: ["A", "B"], modelNumbers: [1, 2] }] }; structureRequest = { assembly: { kind: "biologicalAssembly", assemblyId: "1" }, chainIds: ["A", "B"] }; } if (scenario === "excludedChain" || spec.chain === "excluded") { inventory = { ...inventory, biologicalAssemblies: [{ assemblyId: "1", chainIds: ["A"], modelNumbers: [1] }] }; structureRequest = { assembly: { kind: "biologicalAssembly", assemblyId: "1" }, modelNumber: 1, chainIds: ["A"] }; }
  if (scenario === "repeatedChainAmbiguity" || spec.chain === "repeatedAmbiguous") { structure = { ...structure, chains: [...structure.chains, { ...structure.chains[0]!, id: "A-copy" }] }; inventory = { ...inventory, asymmetricUnit: { ...inventory.asymmetricUnit, chainIds: ["A", "A-copy", "B"] }, biologicalAssemblies: [{ assemblyId: "1", chainIds: ["A", "A-copy", "B"], modelNumbers: [1] }] }; bindings = bindings.map((x) => x.bindingId === "fixture-base-a" ? { ...x, selector: { ...x.selector, chain: { namespace: "auth" as const, id: "A" } } } : x); structureRequest = { assembly: { kind: "biologicalAssembly", assemblyId: "1" }, modelNumber: 1, chainIds: ["A", "A-copy", "B"] }; }
  if (scenario === "missingResidue") structure = { ...structure, chains: structure.chains.map((x) => x.id === "A" ? { ...x, residues: x.residues.filter((r) => r.residueSequence !== 1) } : x) }; if (scenario === "missingAtom") { structure = { ...structure, chains: structure.chains.map((x) => ({ ...x, residues: x.residues.map((r) => ({ ...r, atoms: r.atoms.filter((a) => a.atomName !== "N6") })) })) }; bindings = bindings.map((x) => x.bindingId === "fixture-base-a" ? { ...x, selector: { kind: "atom" as const, structureId, chain: { namespace: "normalized" as const, id: "A" }, residue: { start: 1, end: 1, namespace: "auth" as const }, atomNames: ["N6"] } } : x); chemistryRequests.push({ assertionId: "fixture-donor-a", bindingId: "fixture-base-a", componentId: pair[0], target: "donor", atomName: "N6" }); } if (scenario === "missingComponent") components = components.slice(1); if (scenario === "malformedConnectivity") connectivity = { termini: [], phosphodiesterLinks: [{ linkId: "fixture-link", upstreamResidueKey: "A:1", downstreamResidueKey: "A:1", atomKeys: ["A:1:O3'"], state: "intact" }] }; if (scenario === "missingTerminus") { connectivity = { ...connectivity, termini: [] }; chemistryRequests.push({ assertionId: "fixture-five-prime", bindingId: isPolymer ? "fixture-upstream" : "fixture-base-a", componentId: pair[0], target: "fivePrimeTerminus" }); chemistryRequests = [chemistryRequests.at(-1)!]; } if (scenario === "oneSidedPhosphodiester") connectivity = { ...connectivity, phosphodiesterLinks: [{ ...connectivity.phosphodiesterLinks[0]!, atomKeys: ["A:1:O3'"] }] };
  const requirement = (sourceKind === "computed" ? "computedModel" : sourceKind === "constrainedSchematic" ? "constrainedModel" : sourceKind === "schematic" ? "schematic" : scenario === "fidelityMismatch" ? "schematic" : "depositedCoordinates") as any; const fidelity: ScientificFixtureWorld["fidelity"] = { grounding: { kind: sourceKind === "schematic" ? "educational" : "sourceSelected", confidence: .95 }, mechanismEvidence: sourceKind === "schematic" ? "educational" : "direct", representation: { requirement, ...(scenario === "fidelityMismatch" ? { requestedTier: "E0_DEPOSITED" } : {}), declaredBy: "evidence" } };
  if (!isPolymer && !["computedModel", "constrainedSchematic", "schematic", "invalidProvenance", "ambiguousAssembly", "ambiguousModel", "excludedChain", "missingResidue", "missingAtom", "missingComponent", "malformedConnectivity", "missingTerminus", "oneSidedPhosphodiester", "fidelityMismatch", "repeatedChainAmbiguity"].includes(scenario)) chemistryRequests.push({ assertionId: "fixture-donor-a", bindingId: "fixture-base-a", componentId: pair[0], target: "donor", atomName: componentFor(pair[0], entityA).donorAtomNames[0] }, { assertionId: "fixture-acceptor-t", bindingId: "fixture-base-t", componentId: pair[1], target: "acceptor", atomName: componentFor(pair[1], entityB).acceptorAtomNames[0] });
  const selectors = { schemaVersion: "1" as const, actorScene, structure, bindings }; return { provenance, actorScene, structure, inventory, structureRequest, selectors, fidelity, components, connectivity, chemistryRequests, handles: { sourceId: provenance.sourceId, structureId, strandA, strandB } };
}

const preset = (scenario: ScientificFixtureWorldScenario) => () => createScientificFixtureWorld({ scenario });
export const dnaAT = preset("dnaAT"); export const dnaGC = preset("dnaGC"); export const rnaAU = preset("rnaAU"); export const rnaGC = preset("rnaGC"); export const rnaDnaHybrid = preset("rnaDnaHybrid"); export const dnaPhosphodiester = preset("dnaPhosphodiester"); export const rnaPhosphodiester = preset("rnaPhosphodiester"); export const rnaCleavage = preset("rnaCleavage"); export const rnaExonuclease = preset("rnaExonuclease"); export const strandSeparation = preset("strandSeparation"); export const computedModel = preset("computedModel"); export const constrainedSchematic = preset("constrainedSchematic"); export const schematic = preset("schematic"); export const invalidProvenance = preset("invalidProvenance"); export const ambiguousAssembly = preset("ambiguousAssembly"); export const ambiguousModel = preset("ambiguousModel"); export const excludedChain = preset("excludedChain"); export const missingResidue = preset("missingResidue"); export const missingAtom = preset("missingAtom"); export const missingComponent = preset("missingComponent"); export const malformedConnectivity = preset("malformedConnectivity"); export const missingTerminus = preset("missingTerminus"); export const oneSidedPhosphodiester = preset("oneSidedPhosphodiester"); export const fidelityMismatch = preset("fidelityMismatch"); export const repeatedChainAmbiguity = preset("repeatedChainAmbiguity");

export type ScientificGroundingFixture = { substrate: Extract<GroundingSubstrateResult, { outcome: "RESOLVED" }>; chemistry: GroundedLocalChemistryResult; raw: { structure: Pick<NormalizedMolecularStructure, "structureId" | "chains"> }; handles: { actors: { strandA: ReturnType<typeof actorId>; strandB: ReturnType<typeof actorId> }; selectors: { baseA: string; baseT: string }; facts: { baseA: string; baseT: string; donorA: string; acceptorT: string } } };
export function createScientificGroundingFixture(kind: ScientificGroundingFixtureKind = "dnaAT"): ScientificGroundingFixture { const world = createScientificFixtureWorld(kind); const substrate = resolveGroundingSubstrate({ provenance: world.provenance, attachmentContext: { actorIds: [world.handles.strandA as ReturnType<typeof actorId>, world.handles.strandB as ReturnType<typeof actorId>], groupIds: [] }, inventory: world.inventory, structureRequest: world.structureRequest, selectors: world.selectors, fidelity: world.fidelity }); if (substrate.outcome !== "RESOLVED") throw new Error(`fixture substrate failed: ${substrate.reasons.join("; ")}`); const chemistry = groundAuthenticatedLocalChemistry({ schemaVersion: "1", substrate, structure: world.structure, components: world.components, connectivity: world.connectivity, requests: world.chemistryRequests }); if (!isAuthenticatedLocalChemistryResult(chemistry)) throw new Error(`fixture chemistry failed`); return { substrate, chemistry, raw: { structure: world.structure }, handles: { actors: { strandA: world.handles.strandA as ReturnType<typeof actorId>, strandB: world.handles.strandB as ReturnType<typeof actorId> }, selectors: { baseA: "fixture-base-a", baseT: "fixture-base-t" }, facts: { baseA: "fixture-base-a", baseT: "fixture-base-t", donorA: "fixture-donor-a", acceptorT: "fixture-acceptor-t" } } }; }
export type ConnectivityFixtureKind = "dnaPhosphodiester" | "rnaPhosphodiester" | "rnaCleavage" | "rnaExonuclease" | "strandSeparation";
export type ConnectivityFixture = ScientificGroundingFixture & { handles: ScientificGroundingFixture["handles"] & { selectors: ScientificGroundingFixture["handles"]["selectors"] & { upstream: string; downstream: string; phosphate: string; fivePrime: string; threePrime: string }; facts: ScientificGroundingFixture["handles"]["facts"] & { phosphodiester: string; cleavageSite?: string; fivePrime: string; threePrime: string } } };
export function createConnectivityFixture(kind: ConnectivityFixtureKind): ConnectivityFixture {
  if (kind === "strandSeparation") return createScientificGroundingFixture("dnaAT") as ConnectivityFixture;
  const world = createScientificFixtureWorld({ scenario: kind });
  const substrate = resolveGroundingSubstrate({ provenance: world.provenance, attachmentContext: { actorIds: [world.handles.strandA as ReturnType<typeof actorId>, world.handles.strandB as ReturnType<typeof actorId>], groupIds: [] }, inventory: world.inventory, structureRequest: world.structureRequest, selectors: world.selectors, fidelity: world.fidelity });
  if (substrate.outcome !== "RESOLVED") throw new Error(`fixture substrate failed: ${substrate.reasons.join("; ")}`);
  const chemistry = groundAuthenticatedLocalChemistry({ schemaVersion: "1", substrate, structure: world.structure, components: world.components, connectivity: world.connectivity, requests: world.chemistryRequests });
  if (!isAuthenticatedLocalChemistryResult(chemistry)) throw new Error("fixture chemistry failed");
  const cleavage = kind === "rnaCleavage" ? { cleavageSite: "fixture-link" } : {}; const facts = { baseA: "fixture-upstream-base", baseT: "fixture-base-t", donorA: "fixture-upstream-base", acceptorT: "fixture-base-t", phosphodiester: "fixture-link", ...cleavage, fivePrime: "fixture-five-prime", threePrime: "fixture-three-prime" };
  return { substrate, chemistry, raw: { structure: world.structure }, handles: { actors: { strandA: world.handles.strandA as ReturnType<typeof actorId>, strandB: world.handles.strandB as ReturnType<typeof actorId> }, selectors: { baseA: "fixture-upstream", baseT: "fixture-base-t", upstream: "fixture-upstream", downstream: "fixture-downstream", phosphate: "fixture-upstream", fivePrime: "fixture-upstream", threePrime: "fixture-downstream" }, facts } };
}
export type InvalidScientificGroundingFixtureKind = "invalidProvenance" | "ambiguousAssembly" | "ambiguousModel" | "excludedChain" | "missingResidue" | "missingAtom" | "fidelityMismatch" | "missingComponent" | "missingTerminus" | "malformedConnectivity" | "oneSidedPhosphodiester"; export type InvalidScientificGroundingFixture = { kind: InvalidScientificGroundingFixtureKind; owner: "P2-B" | "P2-C" | "P2-D" | "P2-F" | "P2-G"; result: GroundingSubstrateResult | ReturnType<typeof groundLocalChemistry> };
export function createInvalidScientificGroundingFixture(kind: InvalidScientificGroundingFixtureKind): InvalidScientificGroundingFixture { const world = createScientificFixtureWorld({ scenario: kind }); const substrate = resolveGroundingSubstrate({ provenance: world.provenance, attachmentContext: { actorIds: [world.handles.strandA as never, world.handles.strandB as never], groupIds: [] }, inventory: world.inventory, structureRequest: world.structureRequest, selectors: world.selectors, fidelity: world.fidelity }); const owner = kind === "invalidProvenance" ? "P2-B" : kind === "ambiguousAssembly" || kind === "ambiguousModel" ? "P2-D" : kind === "fidelityMismatch" ? "P2-F" : ["excludedChain", "missingResidue", "missingAtom"].includes(kind) ? "P2-C" : "P2-G"; if (owner !== "P2-G") return { kind, owner, result: substrate }; return { kind, owner, result: groundLocalChemistry({ schemaVersion: "1", substrate, structure: world.structure, components: world.components, connectivity: world.connectivity, requests: world.chemistryRequests }) }; }
