/** F2-E representative DNA/RNA scenes prove current scientific meaning fits one contract. */
import { actorId, groupId, type ScientificActor, type ScientificActorScene } from "./scientific-actor.ts";
import { claimId, provenanceSourceId, type ScientificFidelityProvenanceDocument, type ScientificProvenanceSource } from "./scientific-fidelity-provenance.ts";
import type { PresentationIntent } from "./presentation-intent.ts";
import type { ScientificSceneSpec } from "./scientific-scene-spec.ts";
import type { ScientificInteraction, ScientificState, TopologyGraph } from "./scientific-topology.ts";

type Kind = "canonical-duplex" | "at-pairing" | "gc-pairing" | "antiparallel-polarity" | "strand-separation" | "transcription-context" | "replication-context" | "nucleosome-packaging" | "local-phosphodiester" | "damage-repair-context" | "single-nucleotide" | "generic-rna" | "hairpin" | "pre-vs-mature" | "au-pairing" | "rna-dna-hybrid" | "cleavage" | "exonuclease-shortened" | "rna-dna-stability";
const a = actorId;

function source(id: string, type: "canonicalParameterSet" | "chemicalReference" | "depositedStructure" | "educationalSchematic" = "canonicalParameterSet"): ScientificProvenanceSource {
  return type === "depositedStructure"
    ? { sourceId: provenanceSourceId(id), sourceType: type, accessionOrEntryId: "6ALH", structure: { structureId: "6ALH", assemblyId: "1", chainIds: ["A"] }, provider: { id: "RCSB-PDB" }, citationReference: "pdb-6alh", licenseReference: "rcsb-pdb-data-policy", contentHash: "pending:pdb-6alh", quality: { sourceConfidence: 0.96 } }
    : { sourceId: provenanceSourceId(id), sourceType: type, citationReference: `${id}-citation`, contentHash: `pending:${id}`, quality: { sourceConfidence: type === "educationalSchematic" ? 0.72 : 0.9 } };
}

function makeScene(id: Kind, actors: ScientificActor[], groups: ScientificActorScene["groups"], interactions: ScientificInteraction[], states: ScientificState[], intent: PresentationIntent, fidelity: ScientificFidelityProvenanceDocument): ScientificSceneSpec {
  const topology: TopologyGraph = { graphId: `graph-${id}`, actorIds: actors.map((actor) => actor.actorId), interactions };
  return { schemaVersion: "1", sceneId: id, actors, groups, topology, states, constraints: [{ constraintId: `constraint-${id}`, kind: "requiresParticipant", actorIds: actors.slice(0, 2).map((actor) => actor.actorId), description: "Representative current scientific composition." }], fidelityProvenance: fidelity, presentationIntent: intent };
}

function dnaActors(extra: ScientificActor[] = []) {
  return [
    { actorId: a("dna-1"), semanticTypeId: "dna", scope: "polymer", childActorIds: [a("dna-template-1"), a("dna-coding-1")] },
    { actorId: a("dna-template-1"), semanticTypeId: "strand", role: "templateStrand", scope: "strand", parentActorId: a("dna-1"), anchors: [{ id: "five-prime", kind: "terminus" }, { id: "three-prime", kind: "terminus" }] },
    { actorId: a("dna-coding-1"), semanticTypeId: "strand", role: "codingStrand", scope: "strand", parentActorId: a("dna-1") },
    ...extra,
  ] as ScientificActor[];
}
function rnaActors(extra: ScientificActor[] = []) {
  return [{ actorId: a("rna-1"), semanticTypeId: "rna", scope: "polymer", anchors: [{ id: "five-prime", kind: "terminus" }, { id: "three-prime", kind: "terminus" }] }, ...extra] as ScientificActor[];
}
function intent(focus: ScientificActor[], mode: PresentationIntent["mode"] = "overview"): PresentationIntent {
  return { mode, focusActorIds: focus.map((actor) => actor.actorId), contextActorIds: [], contextSuppression: "nonFocus", regionOfInterest: focus.slice(0, 1).map((actor) => ({ kind: "actor" as const, actorId: actor.actorId })), annotationPriority: focus.slice(0, 2).map((actor) => ({ kind: "actor" as const, actorId: actor.actorId })), motion: "static", audience: "student", detail: "standard" };
}
function computedFidelity(actor: ScientificActor, id = "canonical-model"): ScientificFidelityProvenanceDocument {
  return { sources: [source(id)], attachments: [{ attachmentId: `fidelity-${actor.actorId}`, target: { kind: "actor", actorId: actor.actorId }, fidelity: "C0_COMPUTED", provenanceSourceId: provenanceSourceId(id), confidence: { sourceConfidence: 0.9, groundingConfidence: 0.8, mechanismEvidence: "supported", visualApproximation: "minor" }, visible: true }] };
}

const duplex = dnaActors([{ actorId: a("adenine-1"), semanticTypeId: "adenine", scope: "chemicalComponent" }, { actorId: a("thymine-1"), semanticTypeId: "thymine", scope: "chemicalComponent" }]);
const basePair: ScientificInteraction = { interactionId: "at-pair-1", kind: "noncovalent", type: "basePairing", participants: [{ actorId: a("adenine-1") }, { actorId: a("thymine-1") }], state: "present" };
const rnaNucleotide = rnaActors([{ actorId: a("rna-nucleotide-1"), semanticTypeId: "nucleotide", scope: "residue" }, { actorId: a("rna-ribose-1"), semanticTypeId: "ribose", scope: "chemicalComponent", anchors: [{ id: "two-prime-oh", kind: "atomGroup" }] }, { actorId: a("rna-phosphate-1"), semanticTypeId: "phosphate", scope: "chemicalComponent" }]);

export const scientificSceneSpecFixtures: Record<Kind, ScientificSceneSpec> = {
  "canonical-duplex": makeScene("canonical-duplex", duplex, [], [basePair], [{ stateId: "paired-duplex", kind: "paired", actorIds: [a("dna-1")], interactionIds: ["at-pair-1"] }], intent(duplex.slice(0, 1)), computedFidelity(duplex[0]!)),
  "at-pairing": makeScene("at-pairing", duplex, [{ groupId: groupId("group-at-pair"), kind: "basePair", memberActorIds: [a("adenine-1"), a("thymine-1")] }], [basePair], [{ stateId: "at-paired", kind: "paired", actorIds: [a("adenine-1"), a("thymine-1")], interactionIds: ["at-pair-1"] }], intent(duplex.slice(-2), "localFocus"), computedFidelity(duplex[3]!, "local-chemistry")),
  "gc-pairing": (() => { const actors = dnaActors([{ actorId: a("guanine-1"), semanticTypeId: "guanine", scope: "chemicalComponent" }, { actorId: a("cytosine-1"), semanticTypeId: "cytosine", scope: "chemicalComponent" }]); const bonds: ScientificInteraction[] = ["one", "two", "three"].map((site) => ({ interactionId: `gc-hbond-${site}`, kind: "noncovalent", type: "hydrogenBond", participants: [{ actorId: a("guanine-1") }, { actorId: a("cytosine-1") }], state: "present" })); return makeScene("gc-pairing", actors, [{ groupId: groupId("group-gc-pair"), kind: "basePair", memberActorIds: [a("guanine-1"), a("cytosine-1")] }], bonds, [{ stateId: "gc-paired", kind: "paired", actorIds: [a("guanine-1"), a("cytosine-1")], interactionIds: bonds.map((bond) => bond.interactionId) }], intent(actors.slice(-2), "localFocus"), computedFidelity(actors[0]!, "local-chemistry")); })(),
  "antiparallel-polarity": makeScene("antiparallel-polarity", dnaActors(), [], [], [{ stateId: "duplex-polarity", kind: "paired", actorIds: [a("dna-template-1"), a("dna-coding-1")] }], intent(dnaActors().slice(1), "localFocus"), computedFidelity(dnaActors()[0]!)),
  "strand-separation": makeScene("strand-separation", dnaActors([{ actorId: a("separation-site-1"), semanticTypeId: "localReactionCenter", scope: "molecularComplex" }]), [], [{ interactionId: "opened-pair-1", kind: "noncovalent", type: "basePairing", participants: [{ actorId: a("dna-template-1") }, { actorId: a("dna-coding-1") }], state: "absent" }], [{ stateId: "locally-open", kind: "open", actorIds: [a("dna-template-1"), a("dna-coding-1")], interactionIds: ["opened-pair-1"] }], intent([{ actorId: a("separation-site-1"), semanticTypeId: "localReactionCenter", scope: "molecularComplex" }], "mechanismFocus"), computedFidelity(dnaActors()[0]!)),
  "transcription-context": (() => { const actors = dnaActors([{ actorId: a("rnap-1"), semanticTypeId: "rnaPolymerase", role: "enzyme", scope: "molecularComplex" }, { actorId: a("nascent-rna-1"), semanticTypeId: "transcript", role: "nascentTranscript", scope: "polymer" }]); const fidelity = { sources: [source("pdb-6alh", "depositedStructure")], attachments: [{ attachmentId: "rnap-deposited", target: { kind: "actor" as const, actorId: a("rnap-1") }, fidelity: "E0_DEPOSITED" as const, provenanceSourceId: provenanceSourceId("pdb-6alh"), confidence: { sourceConfidence: .96, groundingConfidence: .93, mechanismEvidence: "direct" as const, visualApproximation: "minor" as const }, visible: true }] }; return makeScene("transcription-context", actors, [], [{ interactionId: "rnap-template", kind: "semanticRelation", type: "polymerContinuity", participants: [{ actorId: a("rnap-1") }, { actorId: a("dna-template-1") }], state: "present", explanatory: true }], [{ stateId: "nascent-transcription", kind: "nascent", actorIds: [a("rnap-1"), a("nascent-rna-1")] }], intent(actors.slice(-2), "mechanismFocus"), fidelity); })(),
  "replication-context": (() => { const actors = dnaActors([{ actorId: a("fork-1"), semanticTypeId: "replicationFork", scope: "molecularComplex" }, { actorId: a("daughter-rna-1"), semanticTypeId: "strand", role: "daughterStrand", scope: "strand" }]); return makeScene("replication-context", actors, [], [{ interactionId: "fork-continuity", kind: "semanticRelation", type: "polymerContinuity", participants: [{ actorId: a("fork-1") }, { actorId: a("daughter-rna-1") }], state: "forming", explanatory: true }], [{ stateId: "fork-open", kind: "open", actorIds: [a("fork-1"), a("dna-1")] }], intent(actors.slice(-2), "mechanismFocus"), computedFidelity(actors[0]!)); })(),
  "nucleosome-packaging": (() => { const actors = dnaActors([{ actorId: a("nucleosome-1"), semanticTypeId: "nucleosome", role: "packagingComplex", scope: "molecularComplex" }]); const fidelity = { sources: [source("pedagogical-nucleosome", "educationalSchematic")], attachments: [{ attachmentId: "nucleosome-schematic", target: { kind: "actor" as const, actorId: a("nucleosome-1") }, fidelity: "S2_SCHEMATIC" as const, provenanceSourceId: provenanceSourceId("pedagogical-nucleosome"), confidence: { sourceConfidence: .72, groundingConfidence: .64, mechanismEvidence: "educational" as const, visualApproximation: "schematic" as const }, visible: true }] }; return makeScene("nucleosome-packaging", actors, [{ groupId: groupId("group-nucleosome"), kind: "complexComposition", memberActorIds: [a("dna-1"), a("nucleosome-1")] }], [{ interactionId: "dna-packaging", kind: "semanticRelation", type: "polymerContinuity", participants: [{ actorId: a("dna-1") }, { actorId: a("nucleosome-1") }], state: "present", explanatory: true }], [{ stateId: "packaged", kind: "closed", actorIds: [a("dna-1"), a("nucleosome-1")] }], intent(actors.slice(-1)), fidelity); })(),
  "local-phosphodiester": makeScene("local-phosphodiester", duplex, [], [{ interactionId: "dna-phosphodiester", kind: "covalent", type: "phosphodiesterLinkage", participants: [{ actorId: a("dna-template-1") }, { actorId: a("dna-coding-1") }], state: "present" }], [{ stateId: "backbone-intact", kind: "intact", actorIds: [a("dna-1")], interactionIds: ["dna-phosphodiester"] }], intent(duplex.slice(1, 3), "localFocus"), computedFidelity(duplex[0]!, "local-chemistry")),
  "damage-repair-context": (() => { const actors = dnaActors([{ actorId: a("lesion-1"), semanticTypeId: "lesion", role: "lesion", scope: "chemicalComponent" }, { actorId: a("repair-complex-1"), semanticTypeId: "complex", role: "repairActor", scope: "molecularComplex" }]); return makeScene("damage-repair-context", actors, [{ groupId: groupId("group-repair-site"), kind: "localReactionCenter", memberActorIds: [a("lesion-1"), a("repair-complex-1")] }], [{ interactionId: "repair-recognition", kind: "semanticRelation", type: "repairRecognition", participants: [{ actorId: a("repair-complex-1") }, { actorId: a("lesion-1") }], state: "present", explanatory: true }], [{ stateId: "repair-context", kind: "intact", actorIds: [a("dna-1"), a("lesion-1"), a("repair-complex-1")], interactionIds: ["repair-recognition"] }], intent(actors.slice(-2), "mechanismFocus"), computedFidelity(actors[0]!, "local-chemistry")); })(),
  "single-nucleotide": makeScene("single-nucleotide", rnaNucleotide, [], [{ interactionId: "rna-nucleotide-assembly", kind: "covalent", type: "covalentBond", participants: [{ actorId: a("rna-ribose-1") }, { actorId: a("rna-phosphate-1") }], state: "present" }], [{ stateId: "rna-nucleotide-intact", kind: "intact", actorIds: [a("rna-nucleotide-1")] }], intent(rnaNucleotide.slice(1), "localFocus"), computedFidelity(rnaNucleotide[0]!, "canonical-rna")),
  "generic-rna": (() => { const actors = rnaActors(); return makeScene("generic-rna", actors, [], [], [{ stateId: "generic-rna-intact", kind: "intact", actorIds: [a("rna-1")] }], intent(actors), computedFidelity(actors[0]!, "canonical-rna")); })(),
  "hairpin": (() => { const actors = rnaActors([{ actorId: a("hairpin-left-1"), semanticTypeId: "nucleotide", scope: "residue" }, { actorId: a("hairpin-right-1"), semanticTypeId: "nucleotide", scope: "residue" }]); return makeScene("hairpin", actors, [{ groupId: groupId("group-hairpin"), kind: "pairedStem", memberActorIds: [a("hairpin-left-1"), a("hairpin-right-1")] }], [{ interactionId: "hairpin-pair", kind: "noncovalent", type: "basePairing", participants: [{ actorId: a("hairpin-left-1") }, { actorId: a("hairpin-right-1") }], state: "present" }], [{ stateId: "hairpin-folded", kind: "paired", actorIds: [a("rna-1")], interactionIds: ["hairpin-pair"] }], intent(actors.slice(-2)), computedFidelity(actors[0]!, "canonical-rna")); })(),
  "pre-vs-mature": (() => { const actors = rnaActors([{ actorId: a("pre-mrna-1"), semanticTypeId: "mRNA", scope: "polymer" }, { actorId: a("mature-mrna-1"), semanticTypeId: "mRNA", scope: "polymer" }, { actorId: a("intron-1"), semanticTypeId: "intron", role: "intron", scope: "polymer" }, { actorId: a("exon-1"), semanticTypeId: "exon", role: "exon", scope: "polymer" }]); const comparison: PresentationIntent = { ...intent(actors.slice(1, 3), "comparison"), comparison: { left: { kind: "actor", actorId: a("pre-mrna-1") }, right: { kind: "actor", actorId: a("mature-mrna-1") } } }; return makeScene("pre-vs-mature", actors, [{ groupId: groupId("group-pre-mature"), kind: "comparisonPair", memberActorIds: [a("pre-mrna-1"), a("mature-mrna-1")] }], [{ interactionId: "intron-span", kind: "semanticRelation", type: "intronSpan", participants: [{ actorId: a("pre-mrna-1") }, { actorId: a("intron-1") }], state: "present", explanatory: true }], [{ stateId: "pre-mrna", kind: "preMRNA", actorIds: [a("pre-mrna-1"), a("intron-1")] }, { stateId: "mature-mrna", kind: "matureMRNA", actorIds: [a("mature-mrna-1"), a("exon-1")] }], comparison, computedFidelity(actors[0]!, "canonical-rna")); })(),
  "au-pairing": (() => { const actors = rnaActors([{ actorId: a("adenine-rna-1"), semanticTypeId: "adenine", scope: "chemicalComponent" }, { actorId: a("uracil-rna-1"), semanticTypeId: "uracil", scope: "chemicalComponent" }]); return makeScene("au-pairing", actors, [{ groupId: groupId("group-au-pair"), kind: "basePair", memberActorIds: [a("adenine-rna-1"), a("uracil-rna-1")] }], [{ interactionId: "au-hbond", kind: "noncovalent", type: "hydrogenBond", participants: [{ actorId: a("adenine-rna-1") }, { actorId: a("uracil-rna-1") }], state: "present" }], [{ stateId: "au-paired", kind: "paired", actorIds: [a("adenine-rna-1"), a("uracil-rna-1")], interactionIds: ["au-hbond"] }], intent(actors.slice(-2), "localFocus"), computedFidelity(actors[0]!, "local-chemistry")); })(),
  "rna-dna-hybrid": (() => { const actors = rnaActors([{ actorId: a("dna-hybrid-1"), semanticTypeId: "dna", role: "complementaryStrand", scope: "polymer" }]); return makeScene("rna-dna-hybrid", actors, [], [{ interactionId: "rna-dna-hybridization", kind: "noncovalent", type: "hybridization", participants: [{ actorId: a("rna-1") }, { actorId: a("dna-hybrid-1") }], state: "present" }], [{ stateId: "hybridized", kind: "hybridized", actorIds: [a("rna-1"), a("dna-hybrid-1")], interactionIds: ["rna-dna-hybridization"] }], intent(actors, "mechanismFocus"), computedFidelity(actors[0]!, "canonical-rna")); })(),
  "cleavage": (() => { const actors = rnaActors([{ actorId: a("rna-fragment-left-1"), semanticTypeId: "cleavageFragment", scope: "polymer" }, { actorId: a("rna-fragment-right-1"), semanticTypeId: "cleavageFragment", scope: "polymer" }]); const scene = makeScene("cleavage", actors, [{ groupId: groupId("group-cleavage-fragments"), kind: "cleavageFragment", memberActorIds: [a("rna-fragment-left-1"), a("rna-fragment-right-1")] }], [{ interactionId: "cleaved-link", kind: "covalent", type: "phosphodiesterLinkage", participants: [{ actorId: a("rna-fragment-left-1") }, { actorId: a("rna-fragment-right-1") }], state: "absent" }, { interactionId: "fragment-relation", kind: "semanticRelation", type: "fragmentContinuity", participants: [{ actorId: a("rna-fragment-left-1") }, { actorId: a("rna-fragment-right-1") }], state: "present", explanatory: true }], [{ stateId: "rna-cleaved", kind: "cleaved", actorIds: actors.map((actor) => actor.actorId), interactionIds: ["cleaved-link", "fragment-relation"], continuityIds: ["continuity-before-cleavage", "continuity-left-fragment", "continuity-right-fragment"], topologyChangeIds: ["change-rna-cleavage"] }], intent(actors.slice(1), "mechanismFocus"), computedFidelity(actors[0]!, "canonical-rna")); return { ...scene, topology: { ...scene.topology, continuities: [{ continuityId: "continuity-before-cleavage", strandActorId: a("rna-1"), orderedActorIds: [a("rna-fragment-left-1"), a("rna-fragment-right-1")], state: "cleaved" }, { continuityId: "continuity-left-fragment", strandActorId: a("rna-fragment-left-1"), orderedActorIds: [a("rna-1"), a("rna-fragment-left-1")], state: "intact" }, { continuityId: "continuity-right-fragment", strandActorId: a("rna-fragment-right-1"), orderedActorIds: [a("rna-1"), a("rna-fragment-right-1")], state: "intact" }], changes: [{ changeId: "change-rna-cleavage", kind: "cleavage", actorIds: [a("rna-1"), a("rna-fragment-left-1"), a("rna-fragment-right-1")], interactionIds: ["cleaved-link"] }] } }; })(),
  "exonuclease-shortened": (() => { const actors = rnaActors([{ actorId: a("retained-rna-1"), semanticTypeId: "cleavageFragment", scope: "polymer", anchors: [{ id: "five-prime", kind: "terminus" }] }]); const scene = makeScene("exonuclease-shortened", actors, [], [{ interactionId: "terminal-shortening", kind: "semanticRelation", type: "terminalDegradation", participants: [{ actorId: a("rna-1"), anchorId: "five-prime" }, { actorId: a("retained-rna-1"), anchorId: "five-prime" }], state: "present", explanatory: true }], [{ stateId: "terminally-degraded", kind: "partiallyDegraded", actorIds: [a("rna-1"), a("retained-rna-1")], interactionIds: ["terminal-shortening"], topologyChangeIds: ["change-five-to-three-shortening"] }], intent(actors.slice(-1), "mechanismFocus"), computedFidelity(actors[0]!, "canonical-rna")); return { ...scene, topology: { ...scene.topology, changes: [{ changeId: "change-five-to-three-shortening", kind: "fragmentation", actorIds: [a("rna-1"), a("retained-rna-1")], interactionIds: ["terminal-shortening"], biochemicalDirection: "fiveToThree" }] } }; })(),
  "rna-dna-stability": (() => { const actors = rnaNucleotide.concat([{ actorId: a("dna-deoxyribose-1"), semanticTypeId: "deoxyribose", scope: "chemicalComponent", anchors: [{ id: "two-prime-position", kind: "atomGroup" }] }]); const comparison: PresentationIntent = { ...intent([actors[2]!, actors[3]!], "comparison"), comparison: { left: { kind: "actor", actorId: a("rna-ribose-1") }, right: { kind: "actor", actorId: a("dna-deoxyribose-1") } } }; const scene = makeScene("rna-dna-stability", actors, [{ groupId: groupId("group-rna-dna-stability"), kind: "comparisonPair", memberActorIds: [a("rna-ribose-1"), a("dna-deoxyribose-1")] }], [{ interactionId: "stability-comparison", kind: "semanticRelation", type: "chemicalComparison", participants: [{ actorId: a("rna-ribose-1") }, { actorId: a("dna-deoxyribose-1") }], state: "present", explanatory: true }], [{ stateId: "stability-intact", kind: "intact", actorIds: [a("rna-ribose-1"), a("dna-deoxyribose-1")] }], comparison, computedFidelity(actors[0]!, "local-chemistry")); return { ...scene, claimIds: [claimId("rna-two-prime-oh-susceptibility")] }; })(),
};
