/** Raw available data for P2-H execution; validation and scientific decisions remain upstream authorities. */
import type { StructureCoordinateInventory } from "./p2-d-structure-context.ts";
import type { SourceProvenanceResolverInput } from "./scientific-source-provenance-resolver.ts";
import type { NormalizedMolecularStructure } from "./biology-structure-grounding.ts";
import type { LocalChemicalComponent, LocalChemicalConnectivity } from "./p2-local-chemistry-grounding.ts";
import type { LocalChemistryRequest } from "./p2-local-chemistry-grounding.ts";
import type { GroundingSubstrateInput } from "./p2-bcdf-grounding-seam.ts";

export const scientificExecutionInventorySchemaVersion = "1" as const;
export type ScientificExecutionInventoryEntry = { source: SourceProvenanceResolverInput; structureInventory?: StructureCoordinateInventory; structure?: Pick<NormalizedMolecularStructure, "structureId" | "chains">; components: readonly LocalChemicalComponent[]; connectivity: LocalChemicalConnectivity };
export type ScientificExecutionInventoryV1 = { schemaVersion: "1"; entries: readonly ScientificExecutionInventoryEntry[] };
export type ScientificFixtureWorld = { provenance: GroundingSubstrateInput["provenance"]; actorScene: NonNullable<GroundingSubstrateInput["selectors"]>["actorScene"]; structure: Pick<NormalizedMolecularStructure, "structureId" | "chains">; inventory: StructureCoordinateInventory; structureRequest: NonNullable<GroundingSubstrateInput["structureRequest"]>; selectors: NonNullable<GroundingSubstrateInput["selectors"]>; fidelity: GroundingSubstrateInput["fidelity"]; components: readonly LocalChemicalComponent[]; connectivity: LocalChemicalConnectivity; chemistryRequests: readonly LocalChemistryRequest[]; handles: { sourceId: string; structureId: string; strandA: string; strandB: string } };
export const createScientificExecutionInventoryFromFixtureWorld = (world: ScientificFixtureWorld): ScientificExecutionInventoryV1 => ({ schemaVersion: "1", entries: [{ source: world.provenance, structureInventory: world.inventory, structure: world.structure, components: world.components, connectivity: world.connectivity }] });
export function validateScientificExecutionInventory(value: ScientificExecutionInventoryV1): { valid: true; issues: [] } | { valid: false; issues: readonly string[] } { const issues: string[] = []; if (!value || typeof value !== "object" || Object.keys(value).some((key) => !["schemaVersion", "entries"].includes(key))) issues.push("unknown inventory field"); if (value.schemaVersion !== "1" || !Array.isArray(value.entries)) issues.push("invalid inventory schema/entries"); const ids = new Set<string>(); for (const entry of value.entries ?? []) { if (!entry || typeof entry !== "object" || Object.keys(entry).some((key) => !["source", "structureInventory", "structure", "components", "connectivity"].includes(key))) { issues.push("malformed inventory entry"); continue; } if (!entry.source?.sourceId || ids.has(entry.source.sourceId)) issues.push("duplicate or missing source ID"); ids.add(entry.source?.sourceId); if (entry.structure && entry.source.structure?.structureId !== entry.structure.structureId) issues.push("dangling source/structure reference"); if (!Array.isArray(entry.components) || !entry.connectivity || !Array.isArray(entry.connectivity.termini) || !Array.isArray(entry.connectivity.phosphodiesterLinks)) issues.push("malformed component/connectivity inventory"); } return issues.length ? { valid: false, issues } : { valid: true, issues: [] }; }
/** Retrieval is deterministic and preserves ambiguity as multiple entries. */
export const executionInventoryEntries = (inventory: ScientificExecutionInventoryV1, sourceId?: string) => inventory.entries.filter((entry) => sourceId === undefined || entry.source.sourceId === sourceId);
