/** D-D production projection: display-only state copied from secretory science. */

import type { ScientificActorId } from "./scientific-actor.ts";
import type { TeachingPlan, TeachingReference } from "./teaching-plan.ts";
import { evaluateSecretoryPathwayAtTime, type SecretoryProgramV1, type SecretorySnapshotV1 } from "./secretory-pathway.ts";

export const secretoryProductionOwnerId = "SECRETORY_PATHWAY_CELLULAR_V1" as const;
export type SecretoryProductionFocus = "CELLULAR" | "ER_TARGETING" | "ER_LUMEN" | "ER_QUALITY" | "GOLGI" | "SECRETORY_VESICLE" | "EXOCYTOSIS";
export type SecretoryProductionProjectionV1 = Readonly<{
  schemaVersion: "1";
  ownerId: typeof secretoryProductionOwnerId;
  programId: string;
  timeSeconds: number;
  focus: SecretoryProductionFocus;
  fidelity: "S2_SCHEMATIC";
  compartments: Readonly<{ cytosol: "VISIBLE"; er: "VISIBLE"; erLumen: "VISIBLE"; golgi: "VISIBLE"; vesicle: "VISIBLE"; plasmaMembrane: "VISIBLE"; extracellular: "VISIBLE" }>;
  protein: Readonly<{ actorId: ScientificActorId; localization: SecretorySnapshotV1["proteinLocalization"]; stage: SecretorySnapshotV1["proteinIdentityStage"]; signalState: SecretorySnapshotV1["signalState"]; translatedResidueCount: number; cytosolicChainLength: number; translocatingChainLength: number; luminalChainLength: number; foldingState: SecretorySnapshotV1["foldingState"]; modificationState: SecretorySnapshotV1["modificationState"]; qualityState: SecretorySnapshotV1["qualityState"] }>;
  targeting: Readonly<{ srpState: SecretorySnapshotV1["srpState"]; transloconState: SecretorySnapshotV1["transloconState"]; erMembraneSide: "CYTOSOLIC"; erLumenSide: "LUMINAL" }>;
  vesicle: Readonly<{ id: ScientificActorId | null; state: SecretorySnapshotV1["vesicleState"]; cargoContained: boolean; docking: SecretorySnapshotV1["dockingState"]; snare: SecretorySnapshotV1["snareState"]; membraneContinuity: SecretorySnapshotV1["membraneContinuity"] }>;
  golgi: SecretorySnapshotV1["golgiCompartment"];
  extracellular: boolean;
  sourceEventIds: readonly string[];
}>;

export type SecretoryProductionResult = Readonly<{ ok: true; projection: SecretoryProductionProjectionV1 }> | Readonly<{ ok: false; code: "SECRETORY_PRODUCTION_INVALID" | "SECRETORY_SCIENCE_UNAVAILABLE"; reasons: readonly string[] }>;
const fail = (code: "SECRETORY_PRODUCTION_INVALID" | "SECRETORY_SCIENCE_UNAVAILABLE", ...reasons: string[]): SecretoryProductionResult => ({ ok: false, code, reasons });
function focus(snapshot: SecretorySnapshotV1): SecretoryProductionFocus { if (snapshot.extracellular) return "EXOCYTOSIS"; if (snapshot.vesicleId) return snapshot.dockingState === "DOCKED" || snapshot.membraneContinuity === "FUSED" ? "EXOCYTOSIS" : "SECRETORY_VESICLE"; if (snapshot.golgiCompartment !== "NONE") return "GOLGI"; if (snapshot.qualityState === "PASS") return "ER_QUALITY"; if (snapshot.proteinLocalization === "ER_LUMEN") return "ER_LUMEN"; if (snapshot.proteinLocalization !== "CYTOSOL") return "ER_TARGETING"; return "CELLULAR"; }

export function projectSecretoryProductionAtTime(program: SecretoryProgramV1, timeSeconds: number): SecretoryProductionResult {
  const evaluated = evaluateSecretoryPathwayAtTime(program, timeSeconds);
  if (!evaluated.ok) return fail("SECRETORY_SCIENCE_UNAVAILABLE", ...evaluated.reasons);
  const snapshot = evaluated.snapshot;
  return { ok: true, projection: { schemaVersion: "1", ownerId: secretoryProductionOwnerId, programId: program.programId, timeSeconds, focus: focus(snapshot), fidelity: "S2_SCHEMATIC", compartments: { cytosol: "VISIBLE", er: "VISIBLE", erLumen: "VISIBLE", golgi: "VISIBLE", vesicle: "VISIBLE", plasmaMembrane: "VISIBLE", extracellular: "VISIBLE" }, protein: { actorId: snapshot.proteinId, localization: snapshot.proteinLocalization, stage: snapshot.proteinIdentityStage, signalState: snapshot.signalState, translatedResidueCount: snapshot.translatedResidueCount, cytosolicChainLength: snapshot.cytosolicChainLength, translocatingChainLength: snapshot.translocatingChainLength, luminalChainLength: snapshot.luminalChainLength, foldingState: snapshot.foldingState, modificationState: snapshot.modificationState, qualityState: snapshot.qualityState }, targeting: { srpState: snapshot.srpState, transloconState: snapshot.transloconState, erMembraneSide: "CYTOSOLIC", erLumenSide: "LUMINAL" }, vesicle: { id: snapshot.vesicleId, state: snapshot.vesicleState, cargoContained: snapshot.cargoContained, docking: snapshot.dockingState, snare: snapshot.snareState, membraneContinuity: snapshot.membraneContinuity }, golgi: snapshot.golgiCompartment, extracellular: snapshot.extracellular, sourceEventIds: snapshot.appliedEventIds } };
}

export function validateSecretoryProductionProjection(program: SecretoryProgramV1, projection: SecretoryProductionProjectionV1): SecretoryProductionResult { const expected = projectSecretoryProductionAtTime(program, projection.timeSeconds); if (!expected.ok) return expected; if (JSON.stringify(expected.projection) !== JSON.stringify(projection)) return fail("SECRETORY_PRODUCTION_INVALID", "production projection contradicts canonical D-D state"); return { ok: true, projection }; }
export function secretoryProductionStateAtFrame(program: SecretoryProgramV1, frameIndex: number, fps: number): SecretoryProductionResult { if (!Number.isInteger(frameIndex) || frameIndex < 0 || !Number.isInteger(fps) || fps <= 0) return fail("SECRETORY_PRODUCTION_INVALID", "frameIndex and fps must be non-negative/integer values"); return projectSecretoryProductionAtTime(program, frameIndex / fps); }

const actor = (actorId: ScientificActorId): TeachingReference => ({ kind: "actor", actorId });
const compartment = (compartmentId: string): TeachingReference => ({ kind: "compartment", compartmentId });
const localization = (actorId: ScientificActorId, compartmentId: string): TeachingReference => ({ kind: "cellularLocalization", actorId, compartmentId });
const eventRef = (timelineEventId: string): TeachingReference => ({ kind: "timelineEvent", timelineEventId });
const chapterDefinitions = [["secretory-signal", "Secretory signal", "secretory-signal-recognized"], ["srp-targeting", "SRP recognition and ER targeting", "er-targeting-started"], ["translocon", "Translocon engagement", "translocon-engaged"], ["cotranslational-translocation", "Cotranslational translocation", "translocation-early"], ["er-release", "ER-lumen release", "er-lumen-released"], ["er-folding", "ER folding", "folding-complete"], ["er-modification", "ER modification and quality", "er-quality-pass"], ["er-exit", "ER exit vesicle", "er-exit-vesicle-formed"], ["golgi-transit", "cis to medial to trans Golgi", "golgi-trans-entry"], ["cargo-sorting", "Cargo sorting", "cargo-sorted"], ["secretory-vesicle", "Secretory vesicle", "secretory-vesicle-formed"], ["docking", "Vesicle docking", "vesicle-docked"], ["fusion", "SNARE and membrane fusion", "membrane-fusion"], ["secretion", "Extracellular secretion", "exocytosis-completed"]] as const;

export function createSecretoryTeachingPlan(program: SecretoryProgramV1, requestMode: TeachingPlan["requestMode"] = "explain"): TeachingPlan {
  const refs = [actor(program.actors.proteinId), actor(program.actors.srpId), actor(program.actors.transloconId), actor(program.actors.erChaperoneId), actor(program.actors.secretoryVesicleId), compartment("cytosol"), compartment("rough-er"), compartment("er-lumen"), compartment("cis-golgi"), compartment("medial-golgi"), compartment("trans-golgi"), compartment("extracellular-space"), localization(program.actors.proteinId, "er-lumen"), localization(program.actors.proteinId, "extracellular-space")];
  const chapters = chapterDefinitions.map(([chapterId, title, timelineEventId], index) => ({ chapterId, order: index + 1, title, focus: [eventRef(timelineEventId), actor(program.actors.proteinId)], context: [compartment("cytosol"), compartment("er-lumen"), actor(program.actors.srpId)], chapterRole: index === 0 ? "IDENTIFY" as const : index === chapterDefinitions.length - 1 ? "SUMMARIZE" as const : "EXPLAIN" as const, ...(index ? { dependsOnChapterIds: [chapterDefinitions[index - 1]![0]] } : {}), disclosure: { primaryFocusRefs: [eventRef(timelineEventId)], secondaryContextRefs: [actor(program.actors.proteinId), compartment("er-lumen")], suppressedContextRefs: [], detail: index < 3 ? "STRUCTURAL" as const : "MECHANISTIC" as const }, timelineMapping: { eventIds: [timelineEventId], chapterIds: [], transitionIds: [] }, narrationCueIds: [`cue-${chapterId}`] }));
  return { schemaVersion: "3", planId: "secretory-pathway-production-teaching", sceneId: program.cellularScene.scene.sceneId, requestMode, learningObjective: "Follow one polypeptide from secretory signal recognition through ER quality control, Golgi sorting, vesicle fusion, and extracellular secretion.", objectiveTrace: { objectiveKind: requestMode === "why" ? "EXPLAIN_CAUSE" : requestMode === "misconceptionCorrection" ? "CORRECT_MISCONCEPTION" : "EXPLAIN_MECHANISM", capabilityId: "exocytosis", phenomenon: "secretory protein lifecycle", mechanism: "ER to Golgi to extracellular secretion", targetActorIds: [program.actors.proteinId], requestMode }, prerequisiteAssumptions: [], chapters, narrationCues: chapters.map((chapter) => ({ cueId: `cue-${chapter.chapterId}`, target: chapter.focus[0]!, purpose: requestMode === "why" ? "explain" as const : requestMode === "misconceptionCorrection" ? "correct" as const : "orient" as const })), annotations: [{ annotationId: "persistent-secretory-protein", kind: "identity", target: actor(program.actors.proteinId), text: "The same polypeptide actor remains the cargo as it moves from the ER to the extracellular space." }], causalSteps: [{ stepId: "quality-before-export", order: 1, cause: compartment("er-lumen"), effect: compartment("cis-golgi"), explanation: "ER quality control must pass before the protein enters export traffic." }, { stepId: "fusion-before-secretion", order: 2, cause: eventRef("membrane-fusion"), effect: compartment("extracellular-space"), explanation: "Membrane fusion changes the compartment relationship so soluble vesicle cargo becomes extracellular." }], ...(requestMode === "misconceptionCorrection" ? { misconceptionCorrection: { misconception: "Secreted proteins simply diffuse through the plasma membrane.", correction: "A secretory vesicle docks and fuses with the plasma membrane; its lumen becomes continuous with the extracellular space.", chapterIds: chapters.map((chapter) => chapter.chapterId), evidence: [...refs, eventRef("membrane-fusion"), eventRef("exocytosis-completed")] } } : {}), projections: [{ audience: "beginner", chapterIds: chapters.map((chapter) => chapter.chapterId), revealedAnnotationIds: ["persistent-secretory-protein"] }, { audience: "intermediate", chapterIds: chapters.map((chapter) => chapter.chapterId), revealedAnnotationIds: ["persistent-secretory-protein"] }, { audience: "advanced", chapterIds: chapters.map((chapter) => chapter.chapterId), revealedAnnotationIds: ["persistent-secretory-protein"] }], };
}

export function serializeSecretoryProductionProjection(projection: SecretoryProductionProjectionV1): string { return JSON.stringify(projection); }
